import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{executablePath:process.env.CHROMIUM_PATH,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!));
const point=(id:string,lng:number,lat:number,type='alert')=>({id,name:id,type,lng,lat,color:'#ef8877'});
const seed={version:1,theme:{pitch:0,bearing:0,threeD:false},camera:{center:[-73.579,45.5195],zoom:17,pitch:0,bearing:0,locked:true},overrides:{},points:[point('destination',-73.578,45.52),point('qg',-73.58,45.519,'hq')],scene:{zoneColors:{watch:'#cc77dd',patrol:'#55cc88'},travelSpeed:30,ambience:{light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12},agents:[{id:'hero1',hero:'nyx',position:[-73.58,45.519],order:'ready',duty:false,hp:6,mental:8,energy:75,color:'#78dcde'}],vehicles:[],zones:[{id:'sector1',name:'Est',color:'#bc8be8',order:'patrol',ring:[[-73.5786,45.5194],[-73.5774,45.5194],[-73.5774,45.5206],[-73.5786,45.5206],[-73.5786,45.5194]]}],window:{open:false,x:.02,y:.04,width:280,height:570}}};
const roads=[[[-73.58,45.519],[-73.578,45.519],[-73.578,45.52],[-73.578,45.521]],[[-73.579,45.52],[-73.578,45.52],[-73.577,45.52]],[[-73.578,45.5197],[-73.5777,45.5197],[-73.5777,45.5203],[-73.578,45.5203]]];
test.beforeEach(async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.addInitScript(s=>{if(window===top&&!localStorage.getItem('vigilante-map-gym-v1'))localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));},seed);
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{buildings:{type:'geojson',data:{type:'FeatureCollection',features:[{type:'Feature',id:11,properties:{height:20},geometry:{type:'Polygon',coordinates:[[[-73.57915,45.51935],[-73.57885,45.51935],[-73.57885,45.51965],[-73.57915,45.51965],[-73.57915,45.51935]]]}}]}},streets:{type:'geojson',data:{type:'FeatureCollection',features:roads.map(coordinates=>({type:'Feature',properties:{class:'street'},geometry:{type:'LineString',coordinates}}))}}},layers:[{id:'background',type:'background',paint:{'background-color':'#17252d'}},{id:'building-fixture',type:'fill',source:'buildings',paint:{'fill-color':'#778888'}},{id:'road-fixture',type:'line',source:'streets',paint:{'line-color':'#708696','line-width':6}}]}}));
 await page.goto('/map-gym.html');await expect(page.locator('#status')).toContainText('Carte prête');
});
async function exported(page:Page,style=false){const pending=page.waitForEvent('download');if(style)await page.locator('#style-export').evaluate((el:HTMLButtonElement)=>el.click());else await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);return JSON.parse(Buffer.concat(chunks).toString());}

test('HQ heals all resources, shows its task, square residents and three readable dock rows',async({page})=>{
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!);Object.assign(s.scene.agents[0],{point:'qg',duty:true,idle:{order:'ready'},hp:3,mental:2,energy:40});localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));});await page.reload();await page.locator('.hero-preview-open').click();const f=page.frameLocator('#hero-frame');await expect(f.locator('.hero-state strong')).toHaveText('Au QG');await expect(f.locator('.map-rest')).toContainText('Récupération');await expect.poll(async()=>(await saved(page)).scene.agents[0].hp).toBeGreaterThan(3.1);const a=(await saved(page)).scene.agents[0];expect(a.mental).toBeGreaterThan(2.1);expect(a.energy).toBeGreaterThan(40);await expect(f.locator('.meter.hp .track')).toHaveAttribute('aria-valuenow',/3\./);await expect(page.locator('.preview-info>strong')).toHaveCount(0);await expect(page.locator('.preview-meter svg')).toHaveCount(3);const rows=await page.locator('.preview-meter').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().y));expect(rows[1]).toBeGreaterThan(rows[0]);expect(rows[2]).toBeGreaterThan(rows[1]);const b=(await page.locator('.poi-resident').boundingBox())!;expect(b.width).toBe(b.height);await page.screenshot({path:'/tmp/map-feedback-hq.png'});
});
test('New point popup keeps its marker visible',async({page})=>{
 await page.locator('#center').click();await expect(page.locator('#selection')).toBeVisible();const panel=(await page.locator('#selection').boundingBox())!,point=(await page.locator('.poi').last().boundingBox())!;expect(Math.max(0,Math.min(panel.x+panel.width,point.x+point.width)-Math.max(panel.x,point.x))*Math.max(0,Math.min(panel.y+panel.height,point.y+point.height)-Math.max(panel.y,point.y))).toBe(0);
});
test('Hover previews adjoining block; heights, destruction and full JSON retain the whole block',async({page})=>{
 const ring=(l:number,r:number)=>[[l,45.51935],[r,45.51935],[r,45.51965],[l,45.51965],[l,45.51935]];const shapes=[{height:20,ring:ring(-73.5792,-73.57895)},{height:45,ring:ring(-73.57895,-73.5787)},{height:30,ring:ring(-73.5783,-73.5781)}];await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{buildings:{type:'geojson',data:{type:'FeatureCollection',features:shapes.map(p=>({type:'Feature',properties:{height:p.height},geometry:{type:'Polygon',coordinates:[p.ring]}}))}}},layers:[{id:'building-fill',type:'fill',source:'buildings',paint:{'fill-color':'#394c62'}}]}}));await page.reload();await page.locator('#pick-building').click();const box=(await page.locator('.maplibregl-canvas').boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(150);let style=await exported(page,true);expect(style.sources['scene-block-hover'].data.features).toHaveLength(2);await page.mouse.click(box.x+box.width/2,box.y+box.height/2);const blocks=(await saved(page)).scene.buildings;expect(blocks).toHaveLength(1);expect(blocks[0].parts).toHaveLength(2);expect(blocks[0].geometry.type).toBe('MultiPolygon');style=await exported(page,true);expect(style.sources['scene-buildings'].data.features.map((p:any)=>p.properties.height).sort()).toEqual([20,45]);await page.locator('#settings-tab').click();const details=page.getByText('Sauvegarde & export',{exact:true});if(!(await page.locator('#export').isVisible()))await details.click();const backup=await exported(page);await page.locator('#import').setInputFiles({name:'block.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.buildings[0].parts).toHaveLength(2);
});
test('Continuous Juice starts immediately and resolves concurrent hero conditions',async({page})=>{
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!);Object.assign(s.scene.agents[0],{hp:1,mental:1,energy:10});s.scene.juice={version:2,focusVersion:1,buildingVersion:1,events:['idle','low_hp','low_mental','low_energy','moving','focus'],rules:[{id:'lowhp',type:'hero',event:'low_hp',config:{effects:['glow'],color:'#ff1111',intensity:1,duration:900}},{id:'lowenergy',type:'hero',event:'low_energy',config:{effects:['glow'],color:'#ffff11',intensity:1,duration:900}},{id:'lowmental',type:'hero',event:'low_mental',config:{effects:['objectShake'],color:'#aa44cc',intensity:1,duration:900}},{id:'moving',type:'hero',event:'moving',config:{effects:['pulse'],color:'#78dcde',intensity:1,duration:900}}]};localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));});await page.reload();const token=page.locator('.agent-token');await expect(token).toHaveAttribute('data-juice-states','low_hp low_mental');await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('point:alert');await page.locator('#juice-trigger').selectOption('idle');await page.locator('[data-juice-effect=pulse]').check();await expect(page.locator('[data-poi=destination]')).toHaveAttribute('data-juice-states','idle');await expect(page.locator('#juice-delete-event')).toBeDisabled();const colors=await token.locator('.token-portrait').evaluate(el=>el.getAnimations().flatMap(a=>(a.effect as KeyframeEffect).getKeyframes()).map(k=>k.boxShadow).filter(Boolean));expect(JSON.stringify(colors)).toContain('255, 17, 17');expect(JSON.stringify(colors)).not.toContain('255, 255, 17');await page.locator('.hero-preview-open').click();await page.locator('[data-poi=destination]').click();await page.locator('#move-to-point').click();await expect(token).toHaveAttribute('data-juice-states','low_hp low_mental moving');await page.locator('#settings-tab').click();const details=page.getByText('Sauvegarde & export',{exact:true});if(!(await page.locator('#export').isVisible()))await details.click();const backup=await exported(page);await page.locator('#import').setInputFiles({name:'juice.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.juice.rules).toEqual(backup.scene.juice.rules);
});
test('Rain impacts are map ground features below building volumes',async({page})=>{
 await page.getByText('Direction artistique',{exact:true}).click();await page.locator('#rain-enabled').check();await page.waitForTimeout(900);await page.getByText('Sauvegarde & export',{exact:true}).click();const style=await exported(page,true);const layer=style.layers.find((l:any)=>l.id==='scene-rain-splashes');expect(layer.type).toBe('circle');expect(layer.paint['circle-pitch-alignment']).toBe('map');expect(style.sources['scene-rain-splashes'].data.features.length).toBeGreaterThan(0);expect(style.layers.findIndex((l:any)=>l.id==='scene-rain-splashes')).toBeLessThan(style.layers.findIndex((l:any)=>l.type==='fill-extrusion'));await page.screenshot({path:'/tmp/map-feedback-rain.png'});
});

test('Points beneath empty dock space are clickable; relocation is explicit and cancellable',async({page})=>{
 const marker=page.locator('[data-poi=qg]');
 await marker.evaluate(el=>{el.style.transform='translate(650px, 790px)';});
 await marker.click();await expect(page.locator('#edit-name')).toHaveValue('qg');await page.locator('#unselect').click();
 const before=(await saved(page)).points.find((p:any)=>p.id==='qg');const b=(await marker.boundingBox())!;
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+100,b.y-70,{steps:8});await page.mouse.up();expect((await saved(page)).points.find((p:any)=>p.id==='qg')).toEqual(before);
 await page.locator('[data-select=qg]').click();await page.locator('#relocate-point').click();await page.keyboard.press('Escape');expect((await saved(page)).points.find((p:any)=>p.id==='qg')).toEqual(before);await expect(page.locator('#selection')).toBeVisible();
 await page.locator('#relocate-point').click();const box=(await page.locator('.maplibregl-canvas').boundingBox())!;await page.mouse.click(box.x+box.width*.55,box.y+box.height*.4);
 await expect(page.locator('#selection')).toBeVisible();const after=(await saved(page)).points.find((p:any)=>p.id==='qg');expect(after.lng).not.toBe(before.lng);expect(after.lat).not.toBe(before.lat);await expect(page.locator('#status')).toHaveText('Point déplacé.');
});

test('Destruction leaves footprint rubble, restores cleanly and exports explosion controls',async({page})=>{
 await page.locator('#pick-building').click();const box=(await page.locator('.maplibregl-canvas').boundingBox())!;await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await expect(page.locator('#building-editor')).toBeVisible();
 await page.getByText('Sauvegarde & export',{exact:true}).click();let style=await exported(page,true);expect(style.layers.find((l:any)=>l.id==='scene-building-volume').filter).toEqual(['==',['get','destroyed'],true]);
 await page.locator('#building-destroy').click();await expect(page.locator('.destruction-vfx')).toBeVisible();style=await exported(page,true);expect(style.sources['scene-rubble'].data.features.length).toBeGreaterThan(5);await page.screenshot({path:'/tmp/map-destruction-preview.png'});
 await page.locator('#building-restore').click();style=await exported(page,true);expect(style.sources['scene-rubble'].data.features).toHaveLength(0);
 await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('building');await page.locator('#juice-trigger').selectOption('destroyed');await page.locator('[data-explosion=scale]').fill('1.75');await page.locator('[data-explosion=smoke]').fill('0.5');await page.locator('#juice-test').click();await expect(page.locator('.destruction-vfx')).toBeVisible();
 await page.locator('#settings-tab').click();const backup=await exported(page);const rule=backup.scene.juice.rules.find((r:any)=>r.type==='building'&&r.event==='destroyed');expect(rule.config.explosion).toMatchObject({scale:1.75,smoke:.5});await page.locator('#import').setInputFiles({name:'explosion.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.juice.rules.find((r:any)=>r.id===rule.id).config.explosion).toEqual(rule.config.explosion);
});

test('Default point colors persist per type without recoloring existing points',async({page})=>{
 const before=(await saved(page)).points;
 await page.locator('#point-type').selectOption('alert');await page.locator('#point-color').fill('#3366aa');await page.locator('#point-type').selectOption('hq');await expect(page.locator('#point-color')).toHaveValue('#edc25d');await page.locator('#point-type').selectOption('alert');await expect(page.locator('#point-color')).toHaveValue('#3366aa');await page.reload();await expect(page.locator('#status')).toContainText('Carte prête');await page.locator('#point-type').selectOption('alert');await expect(page.locator('#point-color')).toHaveValue('#3366aa');expect((await saved(page)).points).toEqual(before);
 await page.locator('#center').click();expect((await saved(page)).points.at(-1).color).toBe('#3366aa');await page.getByText('Sauvegarde & export',{exact:true}).click();const backup=await exported(page);expect(backup.pointColors.alert).toBe('#3366aa');await page.locator('#point-color').fill('#112233');await page.locator('#import').setInputFiles({name:'colors.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.locator('#status')).toHaveText('Atelier importé.');await expect(page.locator('#point-color')).toHaveValue('#3366aa');
});

test('Point names follow their type until customized, and blank restores automatic naming',async({page})=>{
 await page.locator('#point-type').selectOption('alert');await expect(page.locator('#point-name')).toHaveAttribute('placeholder','Alerte');await page.locator('#center').click();await expect(page.locator('#edit-name')).toHaveValue('Alerte');await page.locator('#edit-type').selectOption('police');await expect(page.locator('#edit-name')).toHaveValue('Police');await page.locator('#edit-name').fill('Poste du quartier');await page.locator('#edit-type').selectOption('hq');await expect(page.locator('#edit-name')).toHaveValue('Poste du quartier');await page.locator('#edit-name').fill('');await page.locator('#edit-type').focus();await expect(page.locator('#edit-name')).toHaveValue('QG');await page.locator('#edit-type').selectOption('clue');await expect(page.locator('#edit-name')).toHaveValue('Indice');expect((await saved(page)).points.at(-1).name).toBe('Indice');
});

test('Single building selection keeps adjoining buildings separate and block mode remains available',async({page})=>{
 const ring=(l:number,r:number)=>[[l,45.51935],[r,45.51935],[r,45.51965],[l,45.51965],[l,45.51935]];
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{buildings:{type:'geojson',data:{type:'FeatureCollection',features:[{type:'Feature',properties:{height:20},geometry:{type:'MultiPolygon',coordinates:[[ring(-73.5792,-73.57895)],[ring(-73.57895,-73.5787)]]}}]}}},layers:[{id:'building-fill',type:'fill',source:'buildings',paint:{'fill-color':'#394c62'}}]}}));await page.reload();await page.locator('#pick-single-building').click();await expect(page.locator('#pick-building')).toHaveAttribute('aria-pressed','false');await expect(page.locator('#pick-single-building')).toHaveAttribute('aria-pressed','true');const box=(await page.locator('.maplibregl-canvas').boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(150);let style=await exported(page,true);expect(style.sources['scene-block-hover'].data.features).toHaveLength(1);await page.mouse.click(box.x+box.width/2,box.y+box.height/2);let b=(await saved(page)).scene.buildings[0];expect(b.name).toBe('Bâtiment 1');expect(b.geometry.type).toBe('Polygon');expect(b.parts).toHaveLength(1);await page.locator('#building-forget').click();await page.locator('#pick-building').click();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);b=(await saved(page)).scene.buildings[0];expect(b.name).toBe('Bloc 1');expect(b.parts).toHaveLength(2);
});
