import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{executablePath:process.env.CHROMIUM_PATH,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!));
const point=(id:string,lng:number,lat:number,type='alert')=>({id,name:id,type,lng,lat,color:'#ef8877'});
const seed={version:1,theme:{pitch:0,bearing:0,threeD:false},camera:{center:[-73.579,45.5195],zoom:17,pitch:0,bearing:0,locked:true},overrides:{},points:[point('destination',-73.578,45.52),point('qg',-73.58,45.519,'hq')],scene:{zoneColors:{watch:'#cc77dd',patrol:'#55cc88'},travelSpeed:30,ambience:{light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12},agents:[{id:'hero1',hero:'nyx',position:[-73.58,45.519],order:'ready',hp:6,mental:8,energy:75,color:'#78dcde'}],vehicles:[],zones:[{id:'sector1',name:'Est',color:'#bc8be8',order:'patrol',ring:[[-73.5786,45.5194],[-73.5774,45.5194],[-73.5774,45.5206],[-73.5786,45.5206],[-73.5786,45.5194]]}],window:{open:false,x:.02,y:.04,width:280,height:570}}};
const roads=[[[-73.58,45.519],[-73.578,45.519],[-73.578,45.52],[-73.578,45.521]],[[-73.579,45.52],[-73.578,45.52],[-73.577,45.52]],[[-73.578,45.5197],[-73.5777,45.5197],[-73.5777,45.5203],[-73.578,45.5203]]];
test.beforeEach(async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.addInitScript(s=>{if(window===top&&!localStorage.getItem('vigilante-map-gym-v1'))localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));},seed);
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{streets:{type:'geojson',data:{type:'FeatureCollection',features:roads.map(coordinates=>({type:'Feature',properties:{class:'street'},geometry:{type:'LineString',coordinates}}))}}},layers:[{id:'background',type:'background',paint:{'background-color':'#17252d'}},{id:'road-fixture',type:'line',source:'streets',paint:{'line-color':'#708696','line-width':6}}]}}));
 await page.goto('/map-gym.html');await expect(page.locator('#status')).toContainText('Carte prête');
});
test('Selected hero follows streets to a point, centers without closing, then returns to QG',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await expect(sheet.locator('.identity h1')).toHaveText('NYX');
 await page.locator('[data-poi=destination]').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.path.length).toBeGreaterThan(2);
 const journey=(await saved(page)).scene.agents[0].journey;expect(journey.path.some((p:number[])=>Math.abs(p[0]+73.578)<1e-6&&Math.abs(p[1]-45.519)<1e-6)).toBeTruthy();await expect(sheet.locator('.hero-state strong')).toHaveText('En trajet');
 await page.locator('#hero-center').click();await expect(page.locator('#hero-window')).toBeVisible();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey,{timeout:10000}).toBeUndefined();let p=(await saved(page)).scene.agents[0].position;expect(p[0]).toBeCloseTo(-73.578,6);expect(p[1]).toBeCloseTo(45.52,6);
 await sheet.locator('[data-idle=rest]').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.destination).toBe('qg');await expect.poll(async()=>(await saved(page)).scene.agents[0].journey,{timeout:10000}).toBeUndefined();p=(await saved(page)).scene.agents[0].position;expect(p[0]).toBeCloseTo(-73.58,6);expect(p[1]).toBeCloseTo(45.519,6);await page.waitForTimeout(900);expect((await saved(page)).scene.agents[0].position).toEqual(p);expect(errors).toEqual([]);
});
test('Shared sheet sector dropdown starts patrol and keeps subsequent legs in the sector',async({page})=>{
 await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await sheet.locator('[data-idle=patrol]').click();await sheet.locator('#hero-sector').selectOption('sector1');await expect.poll(async()=>(await saved(page)).scene.agents[0].zone).toBe('sector1');await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.destination).toBe('Est');
 await expect.poll(async()=>{const a=(await saved(page)).scene.agents[0];return a.journey?.path.every((p:number[])=>p[0]>-73.5786&&p[0]<-73.5774&&p[1]>45.5194&&p[1]<45.5206)??false;},{timeout:15000}).toBe(true);
 await sheet.locator('[data-idle=watch]').click();await expect(sheet.locator('#hero-sector')).toHaveValue('sector1');await expect.poll(async()=>(await saved(page)).scene.zones[0].order).toBe('watch');const label=page.locator('[data-zone=sector1].zone-label');await label.hover({force:true});expect(await label.evaluate(el=>getComputedStyle(el).color)).not.toBe('rgb(120, 220, 222)');await expect(label.locator('img')).toHaveCount(1);
 await sheet.locator('#sheet').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'test-results/map-patrol-shared-sheet.png'});
});
test('Juice settings and active routes survive full JSON export/import',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('#juice-tab').click();await page.locator('#juice-target').selectOption('hero:hero1');for(const effect of ['squash','flash','shake','zoom','travel','burst','rain'])await page.locator(`[data-juice-effect=${effect}]`).check();await page.locator('#juice-trigger').selectOption('arrival');await page.locator('#juice-test').click();await expect(page.locator('#juice-feedback')).toContainText('8 effet');await page.waitForTimeout(300);await page.screenshot({path:'test-results/map-juice.png'});await page.locator('#juice-stop').click();
 const config=(await saved(page)).scene.juice;expect(config['hero:hero1'].effects).toHaveLength(8);await page.locator('#settings-tab').click();await page.locator('#travel-speed').evaluate(el=>{(el as HTMLInputElement).value='2';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('[data-agent=hero1]').click();await page.locator('[data-poi=destination]').click();
 await page.getByText('Sauvegarde & export',{exact:true}).click();const pending=page.waitForEvent('download');await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);const exported=JSON.parse(Buffer.concat(chunks).toString());expect(exported.scene.juice).toEqual(config);expect(exported.scene.agents[0].journey).toBeTruthy();
 await page.locator('#import').setInputFiles({name:'juice.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.juice).toEqual(config);await page.reload();await expect(page.locator('#status')).toContainText('Carte prête');await page.locator('#juice-tab').click();await page.locator('#juice-target').selectOption('hero:hero1');await expect(page.locator('[data-juice-effect=burst]')).toBeChecked();await expect(page.locator('#juice-trigger')).toHaveValue('arrival');expect(errors).toEqual([]);
});
test('Vehicle selection replaces hero selection and follows the road route',async({page})=>{
 await page.locator('[data-agent=hero1]').click();await page.locator('#add-vehicle').click();await expect(page.locator('#hero-window')).toBeHidden();await page.locator('[data-poi=destination]').click();await expect.poll(async()=>(await saved(page)).scene.vehicles[0].journey?.path.length).toBeGreaterThan(1);expect((await saved(page)).scene.agents[0].position).toEqual(seed.scene.agents[0].position);await expect.poll(async()=>(await saved(page)).scene.vehicles[0].journey,{timeout:10000}).toBeUndefined();const p=(await saved(page)).scene.vehicles[0].position;expect(p[0]).toBeCloseTo(-73.578,6);expect(p[1]).toBeCloseTo(45.52,6);
});
