import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{executablePath:process.env.CHROMIUM_PATH,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!));
const input=async(page:Page,key:string,value:string)=>page.locator(`[data-theme=${key}]`).evaluate((el,v)=>{(el as HTMLInputElement).value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);
test.beforeEach(async({page})=>{await page.setViewportSize({width:1280,height:900});await page.addInitScript(()=>localStorage.setItem('vigilante-map-gym-v1',JSON.stringify({version:1,theme:{pitch:45,bearing:-70,edgeCooldown:0,zoomRebound:0},points:[],camera:{center:[-73.579,45.519],zoom:15,pitch:45,bearing:-70,locked:true}})));await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#273e49'}}]}}));await page.goto('/map-gym.html');await expect(page.locator('#add-agent')).toBeEnabled();await page.evaluate(()=>{(window as any).edgeHits=[];const animate=Element.prototype.animate;Element.prototype.animate=function(...args:Parameters<typeof animate>){if(this instanceof HTMLElement&&this.dataset.boundary)(window as any).edgeHits.push(this.dataset.boundary);return animate.apply(this,args);};});});
test('Blocked keyboard and drag attempts illuminate the correct edges, free pan and disabled feedback do not',async({page})=>{
 await page.getByText('Lieu & caméra',{exact:true}).click();for(const side of ['left','right','top','bottom'])await page.locator(`[data-pan-bound=${side}]`).click();const before=(await saved(page)).camera.center,canvas=page.locator('.maplibregl-canvas');for(const [key,side] of [['ArrowLeft','left'],['ArrowRight','right'],['ArrowUp','top'],['ArrowDown','bottom']]){await canvas.focus();await page.evaluate(()=>(window as any).edgeHits=[]);await page.keyboard.press(key);await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits)).toContain(side);expect([...new Set(await page.evaluate(()=>(window as any).edgeHits))]).toEqual([side]);}expect((await saved(page)).camera.center[0]).toBeCloseTo(before[0],8);expect((await saved(page)).camera.center[1]).toBeCloseTo(before[1],8);
 await page.waitForTimeout(500);await page.evaluate(()=>(window as any).edgeHits=[]);const b=(await canvas.boundingBox())!;await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await page.mouse.down();await page.mouse.move(b.x+b.width*.5-90,b.y+b.height*.5,{steps:5});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits)).toContain('right');
 await page.getByText('Direction artistique',{exact:true}).click();await page.locator('[data-theme=edgeFeedback]').uncheck();await page.evaluate(()=>(window as any).edgeHits=[]);await canvas.focus();await page.keyboard.press('ArrowUp');await page.waitForTimeout(300);expect(await page.evaluate(()=>(window as any).edgeHits)).toEqual([]);await page.locator('[data-theme=edgeFeedback]').check();for(const side of ['left','right','top','bottom'])await page.locator(`[data-pan-bound=${side}]`).click();await page.evaluate(()=>(window as any).edgeHits=[]);await canvas.focus();await page.keyboard.press('ArrowLeft');await page.waitForTimeout(400);expect(await page.evaluate(()=>(window as any).edgeHits)).toEqual([]);
});
test('Zoom limit pulses on wheel and keyboard but not on programmatic camera changes',async({page})=>{
 await page.getByText('Lieu & caméra',{exact:true}).click();await page.locator('#zoom-lock-min').click();const canvas=page.locator('.maplibregl-canvas');await canvas.hover({position:{x:400,y:300}});await page.mouse.wheel(0,300);await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits)).toContain('zoom');expect((await saved(page)).camera.zoom).toBe(15);await page.waitForTimeout(500);await page.evaluate(()=>(window as any).edgeHits=[]);await canvas.focus();await page.keyboard.press('-');await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits)).toContain('zoom');await page.waitForTimeout(500);await page.evaluate(()=>(window as any).edgeHits=[]);await page.locator('#camera-zoom').evaluate(el=>{(el as HTMLInputElement).value='17';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(200);expect(await page.evaluate(()=>(window as any).edgeHits)).toEqual([]);
});
test('DA vignette and limit settings plus Juice vignette roundtrip, previews stop cleanly',async({page})=>{
 await page.getByText('Direction artistique',{exact:true}).click();for(const [key,value] of Object.entries({vignette:'.7',vignetteColor:'#422040',vignetteSize:'30',vignetteSoftness:'65',vignetteRoundness:'.7',vignetteX:'40',vignetteY:'60',edgeColor:'#aabbff',edgeStrength:'.4',edgeWidth:'22',edgeDuration:'1200',edgeCooldown:'1500'}))await input(page,key,value);await expect(page.locator('.vignette')).toHaveCSS('opacity','0.7');expect(await page.locator('.vignette').evaluate(el=>getComputedStyle(el).backgroundImage)).toContain('rgb(66, 32, 64)');await page.locator('#preview-boundary').click();await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits.length)).toBe(5);await page.screenshot({path:'/tmp/vignette-boundary.png',timeout:10000});
 await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('map');await page.locator('#juice-trigger').selectOption('manual');await page.locator('[data-juice-effect=vignette]').check();await page.locator('#juice-test').click();await expect(page.locator('.juice-vignette')).toHaveCount(1);await page.locator('#juice-stop').click();await expect(page.locator('.juice-vignette')).toHaveCount(0);await expect(page.locator('.vignette')).toHaveCSS('opacity','0.7');await page.locator('#settings-tab').click();await page.getByText('Sauvegarde & export',{exact:true}).click();const pending=page.waitForEvent('download');await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);const buffer=Buffer.concat(chunks),exported=JSON.parse(buffer.toString());await input(page,'vignette','.1');await page.locator('#import').setInputFiles({name:'screen.json',mimeType:'application/json',buffer});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).theme).toEqual(exported.theme);expect((await saved(page)).scene.juice).toEqual(exported.scene.juice);await expect(page.locator('.vignette')).toHaveCSS('opacity','0.7');
});
test('Pinch at minimum zoom signals the perimeter and Juice focus vignette ends on deselection',async({page,context})=>{
 await page.getByText('Lieu & caméra',{exact:true}).click();await page.locator('#zoom-lock-min').click();const box=(await page.locator('.maplibregl-canvas').boundingBox())!,x=box.x+box.width*.6,y=box.y+box.height*.5,cdp=await context.newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true});const fingers=(spread:number)=>[{x:x-spread,y,id:1},{x:x+spread,y,id:2}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:fingers(90)});for(const spread of [80,65,50,35]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:fingers(spread)});await page.waitForTimeout(35);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>page.evaluate(()=>(window as any).edgeHits)).toContain('zoom');await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});
 await page.locator('#add-agent').click();await page.locator('#juice-tab').click();await page.locator('#juice-trigger').selectOption('focus');await page.locator('[data-juice-effect=vignette]').check();await expect(page.locator('.juice-vignette')).toHaveCount(1);expect(await page.locator('.juice-vignette').evaluate(el=>el.getAnimations()[0].effect?.getTiming().iterations===Infinity)).toBe(true);await page.locator('#hero-window-close').click();await expect(page.locator('.juice-vignette')).toHaveCount(0);await expect(page.locator('.vignette')).toHaveCSS('opacity','0.3');
});
test('Zoom rebounds inward at both limits and boundary cooldown suppresses repeated triggers',async({page})=>{
 await page.getByText('Direction artistique',{exact:true}).click();await input(page,'zoomRebound','.12');await input(page,'zoomReboundDuration','300');await input(page,'edgeCooldown','1500');await page.getByText('Lieu & caméra',{exact:true}).click();await page.locator('#zoom-lock-min').click();const canvas=page.locator('.maplibregl-canvas');await canvas.focus();await page.keyboard.press('-');await expect.poll(async()=>(await saved(page)).camera.zoom).toBeCloseTo(15.12,2);expect(await page.evaluate(()=>(window as any).edgeHits)).toEqual(['zoom']);await canvas.focus();await page.keyboard.press('-');await page.waitForTimeout(600);expect(await page.evaluate(()=>(window as any).edgeHits)).toEqual(['zoom']);await page.locator('#zoom-lock-min').click();await page.locator('#zoom-lock-max').click();const max=(await saved(page)).camera.zoom;await canvas.focus();await page.keyboard.press('+');await expect.poll(async()=>(await saved(page)).camera.zoom).toBeCloseTo(max-.12,2);
});
