import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{executablePath:process.env.CHROMIUM_PATH,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!));
const point=(id:string,lng:number,lat:number,type='alert')=>({id,name:id,type,lng,lat,color:'#ef8877'});
const seed={version:1,theme:{pitch:0,bearing:0,threeD:false},camera:{center:[-73.579,45.5195],zoom:17,pitch:0,bearing:0,locked:true},overrides:{},points:[point('destination',-73.578,45.52),point('qg',-73.58,45.519,'hq')],scene:{zoneColors:{watch:'#cc77dd',patrol:'#55cc88'},travelSpeed:30,ambience:{light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12},agents:[{id:'hero1',hero:'nyx',position:[-73.58,45.519],order:'ready',duty:false,hp:6,mental:8,energy:75,color:'#78dcde'}],vehicles:[],zones:[{id:'sector1',name:'Est',color:'#bc8be8',order:'patrol',ring:[[-73.5786,45.5194],[-73.5774,45.5194],[-73.5774,45.5206],[-73.5786,45.5206],[-73.5786,45.5194]]}],window:{open:false,x:.02,y:.04,width:280,height:570}}};
const roads=[[[-73.58,45.519],[-73.578,45.519],[-73.578,45.52],[-73.578,45.521]],[[-73.579,45.52],[-73.578,45.52],[-73.577,45.52]],[[-73.578,45.5197],[-73.5777,45.5197],[-73.5777,45.5203],[-73.578,45.5203]]];
test.beforeEach(async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.addInitScript(s=>{if(window===top&&!localStorage.getItem('vigilante-map-gym-v1'))localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));},seed);
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{streets:{type:'geojson',data:{type:'FeatureCollection',features:roads.map(coordinates=>({type:'Feature',properties:{class:'street'},geometry:{type:'LineString',coordinates}}))}}},layers:[{id:'background',type:'background',paint:{'background-color':'#17252d'}},{id:'road-fixture',type:'line',source:'streets',paint:{'line-color':'#708696','line-width':6}}]}}));
 await page.goto('/map-gym.html');await expect(page.locator('#status')).toContainText('Carte prête');
});
test('Selected hero follows streets to a point, centers without closing, then returns to QG',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await expect(sheet.locator('.identity h1')).toHaveText('NYX');
 await page.locator('[data-poi=destination]').click();await page.locator('#move-to-point').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.path.length).toBeGreaterThan(2);
 const journey=(await saved(page)).scene.agents[0].journey;expect(journey.path.some((p:number[])=>Math.abs(p[0]+73.578)<1e-6&&Math.abs(p[1]-45.519)<1e-6)).toBeTruthy();await expect(sheet.locator('.hero-state strong')).toHaveText('En trajet');
 await page.locator('#hero-center').click();await expect(page.locator('#hero-window')).toBeVisible();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey,{timeout:10000}).toBeUndefined();let p=(await saved(page)).scene.agents[0].position;expect(p[0]).toBeCloseTo(-73.578,6);expect(p[1]).toBeCloseTo(45.52,6);
 await sheet.locator('[data-idle=rest]').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.destination).toBe('qg');await expect.poll(async()=>(await saved(page)).scene.agents[0].journey,{timeout:10000}).toBeUndefined();p=(await saved(page)).scene.agents[0].position;expect(p[0]).toBeCloseTo(-73.58,6);expect(p[1]).toBeCloseTo(45.519,6);await page.waitForTimeout(900);expect((await saved(page)).scene.agents[0].position).toEqual(p);expect(errors).toEqual([]);
});
test('Shared sheet sector dropdown starts patrol and keeps subsequent legs in the sector',async({page})=>{
 await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await sheet.locator('[data-idle=watch]').click();await sheet.locator('#hero-sector').selectOption('sector1');await expect.poll(async()=>(await saved(page)).scene.agents[0].zone).toBe('sector1');await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.destination).toBe('Est');
 await expect(sheet.locator('.hero-state strong')).toHaveText('Surveillance');await expect(sheet.locator('[data-idle=patrol]')).toHaveCount(0);
 await sheet.locator('[data-idle=watch]').click();await expect(sheet.locator('#hero-sector')).toHaveValue('sector1');await expect.poll(async()=>(await saved(page)).scene.zones[0].order).toBe('watch');const label=page.locator('[data-zone=sector1].zone-label');await label.hover({force:true});expect(await label.evaluate(el=>getComputedStyle(el).color)).not.toBe('rgb(120, 220, 222)');await expect(label.locator('img')).toHaveCount(1);
 await sheet.locator('#sheet').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'test-results/map-patrol-shared-sheet.png'});
});
test('Vehicle selection replaces hero selection and follows the road route',async({page})=>{
 await page.locator('[data-agent=hero1]').click();await page.locator('#add-vehicle').click();await expect(page.locator('#hero-window')).toBeHidden();await page.locator('[data-poi=destination]').click();await page.locator('#move-to-point').click();await expect.poll(async()=>(await saved(page)).scene.vehicles[0].journey?.path.length).toBeGreaterThan(1);expect((await saved(page)).scene.agents[0].position).toEqual(seed.scene.agents[0].position);await expect.poll(async()=>(await saved(page)).scene.vehicles[0].journey,{timeout:10000}).toBeUndefined();const p=(await saved(page)).scene.vehicles[0].position;expect(p[0]).toBeCloseTo(-73.578,6);expect(p[1]).toBeCloseTo(45.52,6);
});
test('Clicks inspect points; explicit movement and status cancellation require confirmation',async({page})=>{
 await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await expect(sheet.locator('#hero-move')).toBeVisible();await page.locator('[data-poi=destination]').click();expect((await saved(page)).scene.agents[0].journey).toBeUndefined();await expect(page.locator('#move-to-point')).toContainText('Nyx');await page.locator('#unselect').click();
 await page.locator('#travel-speed').evaluate(el=>{(el as HTMLInputElement).value='1';el.dispatchEvent(new Event('input',{bubbles:true}));});await sheet.locator('#hero-move').click();await expect(sheet.locator('#hero-move')).toHaveAttribute('aria-pressed','true');await page.locator('[data-poi=destination]').click();await expect.poll(async()=>!!(await saved(page)).scene.agents[0].journey).toBe(true);
 await sheet.locator('#cancel-action').click();await expect(sheet.locator('dialog')).toBeVisible();await sheet.locator('#keep-mission').click();expect((await saved(page)).scene.agents[0].journey).toBeTruthy();await sheet.locator('#cancel-action').click();await sheet.locator('#confirm-cancel').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey).toBeUndefined();await expect(sheet.locator('.hero-state strong')).toHaveText('Disponible');const p=(await saved(page)).scene.agents[0].position;await page.waitForTimeout(500);expect((await saved(page)).scene.agents[0].position).toEqual(p);
 await sheet.locator('[data-idle=watch]').click();await sheet.locator('#hero-sector').selectOption('sector1');await expect(sheet.locator('.hero-state strong')).toHaveText('Surveillance');await sheet.locator('#cancel-action').click();await sheet.locator('#confirm-cancel').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].zone).toBeUndefined();expect((await saved(page)).scene.zones[0].agent).toBeUndefined();
});
test('Type rules, custom triggers, rain and sector tolerance roundtrip through JSON',async({page})=>{
 test.setTimeout(60_000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-zone=sector1].zone-row').click();await page.locator('#zone-tolerance').evaluate(el=>{(el as HTMLInputElement).value='50';el.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('#close-zone').click();
 await page.getByText('Direction artistique',{exact:true}).click();await page.locator('#rain-enabled').check();for(const [key,value] of Object.entries({intensity:'.8',speed:'1.5',wind:'-.4',opacity:'.65',color:'#aabbdd'}))await page.locator(`[data-rain=${key}]`).evaluate((el,v)=>{(el as HTMLInputElement).value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.locator('[data-rain=splashes]').uncheck();await page.locator('#lightning-enabled').check();for(const [key,value] of Object.entries({strength:'.7',minInterval:'12',maxInterval:'40',color:'#ffccbb'}))await page.locator(`[data-lightning=${key}]`).evaluate((el,v)=>{(el as HTMLInputElement).value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.locator('[data-route=useActorColor]').uncheck();for(const [key,value] of Object.entries({color:'#ff66bb',width:'6',opacity:'.65',pattern:'dotted'}))await page.locator(`[data-route=${key}]`).evaluate((el,v)=>{(el as HTMLInputElement).value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.locator('[data-route=flow]').check();await expect(page.locator('.weather-rain')).toBeVisible();
 await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('hero');await page.locator('#juice-new-event').fill('blessure');await page.locator('#juice-add-event').click();await page.locator('[data-juice-effect=burst]').check();await page.locator('#juice-target').selectOption('hero:hero1');await page.locator('#juice-test').click();await expect(page.locator('#juice-feedback')).toContainText('blessure · 1 cible');await expect(page.locator('.juice-canvas')).toHaveCount(1);await page.locator('#juice-stop').click();await expect(page.locator('.juice-canvas')).toHaveCount(0);await expect(page.locator('.weather-rain')).toBeVisible();
 await page.locator('#juice-type').selectOption('point:alert');await page.locator('#juice-trigger').selectOption('solved');await page.locator('[data-juice-effect=flash]').check();await page.evaluate(()=>window.dispatchEvent(new CustomEvent('vigilante:juice',{detail:{type:'point:alert',event:'solved'}})));await expect(page.locator('.juice-canvas')).toHaveCount(1);await page.locator('#juice-stop').click();
 const before=await saved(page);expect(before.scene.juice.rules.every((r:any)=>!r.target)).toBe(true);expect(before.scene.juice.rules.find((r:any)=>r.event==='blessure').type).toBe('hero');expect(before.scene.zones[0].tolerance).toBe(50);
 await page.locator('#settings-tab').click();await page.getByText('Sauvegarde & export',{exact:true}).click();const pending=page.waitForEvent('download');await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);const exported=JSON.parse(Buffer.concat(chunks).toString());expect(exported.scene).toEqual(before.scene);
 await page.locator('#rain-enabled').uncheck();await page.locator('#import').setInputFiles({name:'all.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene).toEqual(exported.scene);
 await page.reload();await expect(page.locator('#add-agent')).toBeEnabled();await expect(page.locator('.weather-rain')).toBeVisible();await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('hero');await page.locator('#juice-trigger').selectOption('blessure');await expect(page.locator('[data-juice-effect=burst]')).toBeChecked();await page.screenshot({path:'test-results/juice-type-rain.png'});expect(errors).toEqual([]);
});

test('Point popovers avoid hero sheet, travel counts down, and arrival portraits persist',async({page})=>{
 test.setTimeout(60000);await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await page.locator('[data-poi=destination]').hover();expect(await page.locator('[data-poi=destination]').evaluate(el=>getComputedStyle(el).cursor)).toBe('pointer');await page.locator('[data-poi=destination]').click();const a=await page.locator('#hero-window').boundingBox(),b=await page.locator('#selection').boundingBox();expect(Math.max(0,Math.min(a!.x+a!.width,b!.x+b!.width)-Math.max(a!.x,b!.x))*Math.max(0,Math.min(a!.y+a!.height,b!.y+b!.height)-Math.max(a!.y,b!.y))).toBe(0);
 await page.locator('#move-to-point').click();await expect(sheet.locator('#map-travel-progress')).toBeVisible();const seconds=Number(await sheet.locator('#map-travel-seconds').textContent());expect(seconds).toBeGreaterThan(0);await expect.poll(async()=>Number(await sheet.locator('#map-travel-seconds').textContent())).toBeLessThan(seconds);await expect.poll(async()=>(await saved(page)).scene.agents[0].point,{timeout:12000}).toBe('destination');await expect(page.locator('[data-poi=destination] [data-resident=hero1]')).toBeVisible();await expect(page.locator('.agent-token[data-actor=hero1]')).toBeHidden();
 await page.reload();await expect(page.locator('[data-resident=hero1]')).toBeVisible();await page.locator('[data-resident=hero1]').click();await sheet.locator('[data-idle=rest]').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.targetPoint).toBe('qg');await expect.poll(async()=>(await saved(page)).scene.agents[0].point,{timeout:12000}).toBe('qg');await expect(page.locator('[data-poi=qg] [data-resident=hero1]')).toBeVisible();
});
test('Juice focus ends on deselection; centered fires after camera; Temporary Zoom restores camera',async({page})=>{
 test.setTimeout(60000);await page.locator('[data-agent=hero1]').click();await expect.poll(()=>page.locator('.token-portrait').evaluate(el=>el.getAnimations().filter(a=>a.effect?.getTiming().iterations===Infinity).length)).toBe(2);await page.locator('#hero-window-close').click();await expect.poll(()=>page.locator('.token-portrait').evaluate(el=>el.getAnimations().filter(a=>a.effect?.getTiming().iterations===Infinity).length)).toBe(0);
 await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('point:alert');await page.locator('#juice-trigger').selectOption('centered');await page.locator('[data-juice-effect=pinpoint]').check();await page.locator('#juice-duration').evaluate(el=>{(el as HTMLInputElement).value='2000';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#settings-tab').click();await page.locator('[data-poi=destination]').click();await page.locator('#center-point').click();await expect(page.locator('.juice-canvas')).toHaveCount(1);await page.locator('#unselect').click();
 await page.locator('#juice-tab').click();await page.locator('#juice-stop').click();await page.locator('#juice-type').selectOption('hero');await page.locator('#juice-trigger').selectOption('manual');await page.locator('[data-juice-effect=temporaryZoom]').check();await page.locator('[data-juice-effect=objectShake]').check();await page.locator('[data-juice-effect=pinpoint]').check();const before=(await saved(page)).camera;await page.locator('#juice-test').click();await expect.poll(async()=>(await saved(page)).camera.zoom).toBeGreaterThan(before.zoom+.2);await expect.poll(async()=>Math.abs((await saved(page)).camera.zoom-before.zoom),{timeout:6000}).toBeLessThan(.001);const after=(await saved(page)).camera;expect(after.center[0]).toBeCloseTo(before.center[0],6);expect(after.center[1]).toBeCloseTo(before.center[1],6);
});
test('Rain splashes render and lightning can be previewed independently',async({page})=>{
 await page.getByText('Direction artistique',{exact:true}).click();await page.locator('#rain-enabled').check();await page.locator('[data-rain=intensity]').evaluate(el=>{(el as HTMLInputElement).value='1';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.evaluate(()=>{(window as any).splashCount=0;const ellipse=CanvasRenderingContext2D.prototype.ellipse;CanvasRenderingContext2D.prototype.ellipse=function(...args:Parameters<typeof ellipse>){if(this.canvas.classList.contains('weather-rain'))(window as any).splashCount++;return ellipse.apply(this,args);};});await expect.poll(()=>page.evaluate(()=>(window as any).splashCount)).toBeGreaterThan(5);await page.locator('[data-rain=splashes]').uncheck();const count=await page.evaluate(()=>(window as any).splashCount);await page.waitForTimeout(300);expect(await page.evaluate(()=>(window as any).splashCount)).toBe(count);await page.locator('#lightning-test').click();await expect.poll(()=>page.locator('.weather-lightning').evaluate(el=>Number(getComputedStyle(el).opacity))).toBeGreaterThan(.01);await page.screenshot({path:'test-results/map-v4-weather.png'});
});

test('Surveillance loops continuously with no further routing, hidden path and JSON resume',async({page})=>{
 test.setTimeout(60000);
 await page.evaluate(async()=>{const module=await import(/* @vite-ignore */ '/src/map-roads.ts' as string);(window as any).routeCalls=0;for(const key of ['route','sector','patrolPath'] as const){const original=module.RoadNetwork.prototype[key];(module.RoadNetwork.prototype as any)[key]=function(...args:any[]){(window as any).routeCalls++;return (original as any).apply(this,args);};}});
 await page.locator('[data-agent=hero1]').click();const sheet=page.frameLocator('#hero-frame');await sheet.locator('[data-idle=watch]').click();await sheet.locator('#hero-sector').selectOption('sector1');await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.loopActive,{timeout:15000}).toBe(true);await expect(sheet.locator('#map-travel-progress')).toHaveCount(0);await expect(sheet.locator('.hero-state strong')).toHaveText('Surveillance');const initial=(await saved(page)).scene.agents[0].journey,calls=await page.evaluate(()=>(window as any).routeCalls);await page.waitForTimeout(12000);const current=(await saved(page)).scene.agents[0].journey;expect(current.loopActive).toBe(true);expect(current.path).toEqual(initial.path);expect(await page.evaluate(()=>(window as any).routeCalls)).toBe(calls);
 await page.getByText('Sauvegarde & export',{exact:true}).click();const stylePending=page.waitForEvent('download');await page.locator('#style-export').click();const styleStream=await(await stylePending).createReadStream(),styleChunks:Buffer[]=[];for await(const c of styleStream!)styleChunks.push(c);expect(JSON.parse(Buffer.concat(styleChunks).toString()).sources['scene-routes'].data.features).toHaveLength(0);
 const pending=page.waitForEvent('download');await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);const buffer=Buffer.concat(chunks),exported=JSON.parse(buffer.toString());await page.locator('#import').setInputFiles({name:'loop.json',mimeType:'application/json',buffer});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.agents[0].journey.path).toEqual(exported.scene.agents[0].journey.path);await page.reload();await expect(page.locator('#add-agent')).toBeEnabled();expect((await saved(page)).scene.agents[0].journey.path).toEqual(initial.path);await sheet.locator('#cancel-action').click();await sheet.locator('#confirm-cancel').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey).toBeUndefined();
});
