import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{executablePath:process.env.CHROMIUM_PATH,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!));
const point=(id:string,lng:number,lat:number,type='alert')=>({id,name:id,type,lng,lat,color:'#ef8877'});
const seed={version:1,theme:{pitch:0,bearing:0,threeD:false},camera:{center:[-73.579,45.5195],zoom:17,pitch:0,bearing:0,locked:true},overrides:{},points:[point('destination',-73.578,45.52),point('qg',-73.58,45.519,'hq')],scene:{zoneColors:{watch:'#cc77dd',patrol:'#55cc88'},travelSpeed:30,ambience:{light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12},agents:[{id:'hero1',hero:'nyx',position:[-73.58,45.519],order:'ready',duty:false,hp:6,mental:8,energy:75,color:'#78dcde'}],vehicles:[],zones:[{id:'sector1',name:'Est',color:'#bc8be8',order:'patrol',ring:[[-73.5786,45.5194],[-73.5774,45.5194],[-73.5774,45.5206],[-73.5786,45.5206],[-73.5786,45.5194]]}],window:{open:false,x:.02,y:.04,width:280,height:570}}};
const roads=[[[-73.58,45.519],[-73.578,45.519],[-73.578,45.52],[-73.578,45.521]],[[-73.579,45.52],[-73.578,45.52],[-73.577,45.52]],[[-73.578,45.5197],[-73.5777,45.5197],[-73.5777,45.5203],[-73.578,45.5203]]];
test.beforeEach(async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.addInitScript(s=>{if(window===top&&!localStorage.getItem('vigilante-map-gym-v1'))localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));},seed);
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{buildings:{type:'geojson',data:{type:'FeatureCollection',features:[{type:'Feature',id:11,properties:{height:20},geometry:{type:'Polygon',coordinates:[[[-73.57915,45.51935],[-73.57885,45.51935],[-73.57885,45.51965],[-73.57915,45.51965],[-73.57915,45.51935]]]}}]}},streets:{type:'geojson',data:{type:'FeatureCollection',features:roads.map(coordinates=>({type:'Feature',properties:{class:'street'},geometry:{type:'LineString',coordinates}}))}}},layers:[{id:'background',type:'background',paint:{'background-color':'#17252d'}},{id:'building-fixture',type:'fill',source:'buildings',paint:{'fill-color':'#778888'}},{id:'road-fixture',type:'line',source:'streets',paint:{'line-color':'#708696','line-width':6}}]}}));
 await page.goto('/map-gym.html');await expect(page.locator('#status')).toContainText('Carte prête');
});
test('Squad bar opens shared sheet, quick travel matches, surveillance reports sector and energy',async({page})=>{
 await expect(page.locator('#hero-dock .hero-preview')).toHaveCount(1);await expect(page.locator('[data-value=energy]')).toHaveText('75');await page.locator('.hero-preview-open').click();const sheet=page.frameLocator('#hero-frame');await expect(sheet.locator('.identity h1')).toHaveText('NYX');await page.locator('[data-poi=destination]').click();await page.locator('#move-to-point').click();await expect(sheet.locator('[data-quick-progress]')).toBeVisible();const quick=Number(await sheet.locator('[data-quick-seconds]').textContent()),large=Number(await sheet.locator('#map-travel-seconds').textContent());expect(Math.abs(quick-large)).toBeLessThan(.4);
 await sheet.locator('[data-idle=watch]').click();await sheet.locator('#hero-sector').selectOption('sector1');await expect(sheet.locator('.map-watch')).toContainText('Surveillance · Est');await expect(sheet.locator('.map-watch')).toContainText('0,15 énergie/s');await expect(sheet.locator('#map-travel-progress')).toHaveCount(0);await expect(page.locator('#hero-dock [data-task]')).toHaveText('Surveillance');await expect.poll(async()=>Number(await page.locator('[data-value=energy]').textContent())).toBeLessThan(75);await page.screenshot({path:'/tmp/v6-squad.png',animations:'disabled',timeout:10000});await page.locator('#hero-window-close').click();await page.locator('[data-center-hero=hero1]').click();await expect(page.locator('#hero-window')).toBeHidden();
});
test('Connected triggers work while editing, pinpoint behind markers and double click never zooms',async({page})=>{
 await page.locator('#juice-tab').click();await page.locator('#juice-type').selectOption('point:alert');await page.locator('#juice-trigger').selectOption('click');await expect(page.locator('#juice-delete-event')).toBeDisabled();await page.locator('[data-juice-effect=pinpoint]').check();await page.locator('#juice-duration').evaluate(el=>{(el as HTMLInputElement).value='2000';el.dispatchEvent(new Event('input',{bubbles:true}));});await expect(page.locator('#juice-feedback')).toContainText('automatiquement');await page.locator('[data-poi=destination]').click();await expect(page.locator('.maplibregl-canvas-container>.juice-ground')).toHaveCount(1);expect(await page.locator('.juice-ground').evaluate(el=>getComputedStyle(el).zIndex)).toBe('0');await page.locator('#unselect').click();const before=(await saved(page)).camera.zoom;await page.locator('#map canvas.maplibregl-canvas').dblclick({position:{x:160,y:130}});await page.waitForTimeout(600);expect((await saved(page)).camera.zoom).toBeCloseTo(before,5);await expect(page.locator('.maplibregl-ctrl-zoom-in,.maplibregl-ctrl-scale,.maplibregl-ctrl-attrib-button')).toHaveCount(0);await expect(page.locator('#map-place')).toHaveText('Montréal · Canada');
});
test('Building color association destruction and restoration survive full JSON roundtrip',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('#pick-building').click();const box=await page.locator('#map canvas.maplibregl-canvas').boundingBox();await page.mouse.click(box!.x+box!.width/2,box!.y+box!.height/2);await expect(page.locator('#building-editor')).toBeVisible();await page.locator('#building-name').fill('Tour test');await page.locator('#building-color').fill('#aa55ee');await expect(page.locator('#building-effect')).toHaveCount(0);await page.locator('#building-point').selectOption('destination');await page.locator('#building-destroy').click();await expect(page.locator('.destruction-vfx')).toHaveCount(1);await expect.poll(async()=>(await saved(page)).scene.buildings[0].destroyed).toBe(true);
 await page.getByText('Sauvegarde & export',{exact:true}).click();const pending=page.waitForEvent('download');await page.locator('#export').click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(c);const buffer=Buffer.concat(chunks),exported=JSON.parse(buffer.toString());expect(exported.scene.buildings[0]).toMatchObject({name:'Tour test',color:'#aa55ee',effect:'none',point:'destination',destroyed:true});await page.locator('#building-restore').click();expect((await saved(page)).scene.buildings[0].destroyed).toBe(false);await page.locator('#import').setInputFiles({name:'building.json',mimeType:'application/json',buffer});await expect(page.locator('#status')).toHaveText('Atelier importé.');expect((await saved(page)).scene.buildings).toEqual(exported.scene.buildings);await page.locator('[data-building]').click();await expect(page.locator('#building-destroy')).toBeDisabled();await page.locator('#building-restore').click();await page.locator('#building-forget').click();expect((await saved(page)).scene.buildings).toEqual([]);expect(errors).toEqual([]);
});
test('Idle QG chooses nearest QG on load and explicit cancellation stops return',async({page})=>{
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('vigilante-map-gym-v1')!);s.scene.agents[0].position=[-73.578,45.52];delete s.scene.agents[0].duty;s.points.push({id:'near',name:'QG proche',type:'hq',lng:-73.578,lat:45.5197,color:'#88aa99'});s.scene.travelSpeed=1;localStorage.setItem('vigilante-map-gym-v1',JSON.stringify(s));});await page.reload();await expect.poll(async()=>(await saved(page)).scene.agents[0].journey?.targetPoint,{timeout:15000}).toBe('near');await page.locator('.hero-preview-open').click();const sheet=page.frameLocator('#hero-frame');await sheet.locator('#cancel-action').click();await sheet.locator('#confirm-cancel').click();await expect.poll(async()=>(await saved(page)).scene.agents[0].duty).toBe(false);const p=(await saved(page)).scene.agents[0].position;await page.waitForTimeout(1500);expect((await saved(page)).scene.agents[0].position).toEqual(p);
});
test('Lightning preview has two distinct flashes',async({page})=>{
 await page.getByText('Direction artistique',{exact:true}).click();await page.locator('#lightning-test').click();const frames=await page.locator('.weather-lightning').evaluate(el=>el.getAnimations()[0]?.effect instanceof KeyframeEffect?(el.getAnimations()[0].effect as KeyframeEffect).getKeyframes():[]);expect(frames.filter((f:any)=>Number(f.opacity)>.1)).toHaveLength(2);expect(frames.some((f:any)=>f.offset!>0&&f.offset!<1&&Number(f.opacity)===0)).toBe(true);
});
test('Rain splashes stay behind a building covering the viewport',async({page})=>{
 await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({json:{version:8,sources:{buildings:{type:'geojson',data:{type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[-73.7,45.4],[-73.4,45.4],[-73.4,45.7],[-73.7,45.7],[-73.7,45.4]]]}}]}}},layers:[{id:'building-fill',type:'fill',source:'buildings',paint:{'fill-color':'#887766'}}]}}));await page.reload();await expect(page.locator('#add-agent')).toBeEnabled();await page.evaluate(()=>{(window as any).splashes=0;const ellipse=CanvasRenderingContext2D.prototype.ellipse;CanvasRenderingContext2D.prototype.ellipse=function(...args:Parameters<typeof ellipse>){if(this.canvas.classList.contains('weather-rain'))(window as any).splashes++;return ellipse.apply(this,args);};});await page.getByText('Direction artistique',{exact:true}).click();await page.locator('#rain-enabled').check();await page.waitForTimeout(1200);expect(await page.evaluate(()=>(window as any).splashes)).toBe(0);
});
