import {icon as sourceIcon} from './icons';
const icon=(name:string)=>sourceIcon(name as Parameters<typeof sourceIcon>[0]);
import './hero-gym.css';
type Theme='dossier'|'bulletin';
const defaults={dossier:{accent:'#e6bd57',hp:'#83dcb6',mental:'#b88af1',energy:'#eaba53',surface:'#162630',background:'#0c151e',text:'#eff0e9'},bulletin:{accent:'#efad3e',hp:'#e65650',mental:'#81b0ed',energy:'#efad3e',surface:'#181e21',background:'#0c1012',text:'#eee5d2'}};
let theme:Theme='dossier',tab='Fiche',status='travel',idle='rest',hp=6,mental=8,energy=75,remaining=12,running=false;
const palettes=structuredClone(defaults);let texture=.12;
const root=document.querySelector<HTMLDivElement>('#hero-gym')!;
root.innerHTML=`<header class="lab"><a href="./gyms.html">← Tous les gyms</a><strong>GYM HÉROS</strong><span>Fiche complète</span></header><div class="workspace"><aside class="tools"><h2>Atelier</h2><div class="design-switch"><button data-theme="dossier">A · Dossier</button><button data-theme="bulletin">B · Bulletin</button></div><details open><summary>Couleurs et matière</summary><div id="colors"></div><label>Texture <input id="texture" type="range" min="0" max="0.4" step="0.01" value=".12"></label><button id="reset-colors">Palette d’origine</button><button id="export">Exporter les couleurs CSS</button></details><details><summary>Tester la fiche</summary><label>État<select id="state"><option value="travel">En trajet</option><option value="working">En intervention</option><option value="rest">Repos au QG</option><option value="patrol">Patrouille</option></select></label><label>HP <input data-meter="hp" type="range" min="0" max="8" value="6"></label><label>Mental <input data-meter="mental" type="range" min="0" max="10" value="8"></label><label>Énergie <input data-meter="energy" type="range" min="0" max="100" value="75"></label><button id="bark">Faire parler Malik</button><button id="animate">Jouer le trajet</button></details><details><summary>Assets réutilisables</summary><div class="asset-links">${['portrait-dossier','portrait-bulletin','gare'].map(x=>`<a href="./assets/heroes/${x}.webp" download>${x} · WebP</a>`).join('')}<a href="./assets/heroes/grain.svg" download>Grain neutre · SVG</a><a href="./assets/heroes/scuffs.svg" download>Usure neutre · SVG</a></div></details></aside><main id="sheet" class="sheet"></main></div><p id="notice" role="status"></p>`;
const sheet=document.querySelector<HTMLElement>('#sheet')!;
const meter=(label:string,value:number,max:number,key:string,ico:string)=>`<div class="meter ${key}"><span>${icon(ico)}<b>${label}</b></span><div class="track" role="meter" aria-label="${label}" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="${max}">${key==='energy'?`<i style="width:${value}%"></i>`:Array.from({length:max},(_,i)=>`<i class="${i<value?'filled':''}"></i>`).join('')}</div><strong>${value}<small>${key==='energy'?' %':` / ${max}`}</small></strong></div>`;
function applyPalette(){Object.entries(palettes[theme]).forEach(([k,v])=>sheet.style.setProperty('--'+k,v));sheet.style.setProperty('--texture',String(texture));}
function colors(){document.querySelector('#colors')!.innerHTML=Object.entries(palettes[theme]).map(([k,v])=>`<label>${({accent:'Accent',hp:'HP',mental:'Mental',energy:'Énergie',surface:'Panneaux',background:'Fond',text:'Texte'} as Record<string,string>)[k]}<input type="color" data-color="${k}" value="${v}"></label>`).join('');}
function render(){sheet.dataset.theme=theme;applyPalette();document.querySelectorAll<HTMLButtonElement>('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===theme)));
const active=status==='travel'||status==='working';
const stateLabel={travel:'En trajet',working:'En intervention',rest:'Repos au QG',patrol:'Patrouille'}[status];
sheet.innerHTML=`<div class="sheet-brand"><span>VIGILANTE SQUAD</span><small>${theme==='dossier'?'A · DOSSIER OPÉRATIONNEL':'B · BULLETIN DE TERRAIN'}</small></div><section class="identity"><div class="portrait-wrap"><img class="portrait" src="./assets/heroes/portrait-${theme}.webp" alt="Portrait de Malik"><div id="speech" class="speech" hidden>Je vous tiens au courant.</div></div><div class="identity-info"><h1>MALIK</h1><div class="hero-state">${icon(status==='rest'?'home':'route')}<div><strong>${stateLabel}</strong><span>${active?'Vers Gare Est':'Les Halles'}</span>${active?'<small>Protéger les civils</small>':''}</div></div></div></section><div class="attributes">${[['Corps',6,'barbell'],['Esprit',4,'brain'],['Âme',8,'heart']].map(([name,value,ico])=>`<div>${icon(String(ico))}<span>${name}<b>${value}</b></span></div>`).join('')}</div><nav class="tabs" aria-label="Fiche du héros">${['Fiche','Équipement','Véhicule','Journal'].map(t=>`<button data-tab="${t}" aria-pressed="${t===tab}">${t}</button>`).join('')}</nav><div class="tab-content">${tab==='Fiche'?`<section class="condition panel">${meter('HP',hp,8,'hp','first-aid-kit')}${meter('Mental',mental,10,'mental','brain')}${meter('Énergie',energy,100,'energy','battery')}<div class="tags"><span>${icon('users')}Médiation</span><span>${icon('shield')}Protection</span><span class="negative">${icon('alert-triangle')}Impulsif</span></div></section>${active?`<section class="mission panel"><div class="mission-info"><div class="countdown"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="44"/><circle class="ring" cx="50" cy="50" r="44" stroke-dasharray="276.46" stroke-dashoffset="${276.46*(1-remaining/30)}"/></svg><div><b id="seconds">${remaining}</b><span>s</span><small>${status==='travel'?'ARRIVÉE DANS':'FIN DANS'}</small></div></div><div><h2>Altercation à la gare</h2><p>${icon('map-pin')}Gare Est</p><p>Protéger les civils</p><div class="journey"><span>${status==='travel'?'Trajet':'Action'}</span><progress id="progress" max="30" value="${30-remaining}"></progress></div></div></div><button id="view-mission">${icon('target')}Voir la mission</button></section>`:`<section class="panel free-state"><h2>${stateLabel}</h2><p>${status==='rest'?'Récupération au quartier général.':'Dans les Halles. Réaffectable.'}</p></section>`}<section class="idle"><h2>Idle</h2><div>${[['rest','home','QG','+ énergie'],['patrol','walk','Patrouille','− énergie']].map(([k,ico,name,rate])=>`<button data-idle="${k}" aria-pressed="${idle===k}">${icon(ico)}<span><b>${name}</b><small>${rate}</small></span></button>`).join('')}</div></section>`:`<section class="panel future"><h2>${tab}</h2><p>${tab==='Équipement'?'Emplacements, objets et charges : contenu à définir.':tab==='Véhicule'?'Véhicule assigné, état et capacité : contenu à définir.':'Historique des missions, décisions et événements : contenu à définir.'}</p><span>Exploration du gym</span></section>`}</div>`;}
let barkTimer:ReturnType<typeof setTimeout>;let barkIndex=0;
root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.dataset.theme){theme=b.dataset.theme as Theme;colors();render();}if(b.dataset.tab){tab=b.dataset.tab;render();}if(b.dataset.idle){idle=b.dataset.idle;render();}if(b.id==='reset-colors'){palettes[theme]={...defaults[theme]};texture=.12;(document.querySelector('#texture') as HTMLInputElement).value='.12';colors();applyPalette();}if(b.id==='bark'){const s=document.querySelector<HTMLElement>('#speech')!;s.textContent=['Je vous tiens au courant.','J’arrive sur place.','On reste ensemble.'][barkIndex++%3];s.hidden=false;clearTimeout(barkTimer);barkTimer=setTimeout(()=>s.hidden=true,2800);}if(b.id==='animate'){status='travel';remaining=30;running=true;(document.querySelector('#state') as HTMLSelectElement).value='travel';render();}if(b.id==='view-mission')window.location.href='./index.html?incident=gare';if(b.id==='export'){const text=`/* ${theme} */\n[data-theme="${theme}"] {\n${Object.entries(palettes[theme]).map(([k,v])=>`  --${k}: ${v};`).join('\n')}\n  --texture: ${texture};\n}`;const url=URL.createObjectURL(new Blob([text],{type:'text/css'}));const a=document.createElement('a');a.href=url;a.download=`vigilante-${theme}.css`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
root.addEventListener('input',e=>{const x=e.target as HTMLInputElement;if(x.dataset.color){(palettes[theme] as Record<string,string>)[x.dataset.color]=x.value;applyPalette();}if(x.id==='texture'){texture=Number(x.value);applyPalette();}if(x.dataset.meter){if(x.dataset.meter==='hp')hp=+x.value;if(x.dataset.meter==='mental')mental=+x.value;if(x.dataset.meter==='energy')energy=+x.value;render();}});
root.addEventListener('change',e=>{const x=e.target as HTMLSelectElement;if(x.id==='state'){status=x.value;running=false;remaining=12;render();}});
setInterval(()=>{if(!running)return;remaining=Math.max(0,remaining-1);if(!remaining){running=false;status='working';remaining=10;}render();},1000);
colors();render();
