import morphdom from 'morphdom';
import './style.css';
import {icon,gauge,statIcon,statColor,chanceTone} from './icons';
import {Simulation,NIGHT,choices,route,type Agent,type IdleTask,type Stat,type Incident,type Choice} from './simulation';
import {createMap} from './map';
let sim=new Simulation(), selectedIncident='gare',selected=new Set<string>(),speed=1,paused=false,seed=42;
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><div class="brand">VIGILANTE <b>SQUAD</b><small>PREMIÈRE NUIT · PROTO WEB 0.9</small></div><div class="clock"><strong id="clock">22:00</strong><span>LES HALLES</span></div><button id="help" class="quiet" aria-label="Comment jouer">?</button></header>
<main><section class="city"><div class="map-heading"><span>QUARTIER SOUS SURVEILLANCE</span><span class="live">● DIRECT</span></div><div id="map" aria-label="Carte du quartier, agents et interventions. Les alertes sont aussi accessibles dans la liste."></div><div class="map-tools"><span><i class="legend crew"></i> Équipe <i class="legend police"></i> Police <i class="legend alert"></i> Alerte</span><div><button id="map-reset" aria-label="Voir tout le quartier">${icon('target')}</button><button id="zoomout" aria-label="Réduire la carte">−</button><button id="zoomin" aria-label="Agrandir la carte">+</button></div></div><div id="alerts" class="alert-list"></div></section>
<aside><div class="section-title">INTERVENTION <span id="count"></span></div><div id="decision-timer" hidden></div><div id="incident"></div><div id="incident-actions"></div><section id="dispatch-panel" aria-labelledby="dispatch-title" hidden><div class="panel-heading"><h2 id="dispatch-title">Préparer l’intervention</h2><button id="dispatch-back" aria-label="Retour à l’événement">${icon('arrow-left')}Retour</button></div><div class="prep-scroll"><div id="dispatch-context"></div><div id="dispatch-heroes"></div><div id="dispatch-comparison"></div></div><div class="dispatch-footer"><span id="dispatch-message"></span><button id="confirm-dispatch" class="primary">Envoyer l’équipe →</button></div></section></aside>
<section class="squad"><div class="section-title">VOTRE ÉQUIPE <span id="selection-label">Toucher pour sélectionner</span><button id="profiles" class="text-button">Profils</button></div><div id="agents"></div><div class="assign hint">Clique sur un héros pour préparer son intervention.</div></section>
</main>
<nav id="mobile-nav" aria-label="Vues du jeu"><button id="view-map" data-view="map" aria-pressed="true">${icon('map-pin')}Carte <span id="nav-alerts"></span></button><button id="view-intervention" data-view="intervention" aria-pressed="false">${icon('target')}Intervention <span id="nav-decisions"></span></button></nav>

<dialog id="intro"><span class="eyebrow">TEST 01 / UNE NUIT AUX HALLES</span><h1>On prend<br>la relève.</h1><p>Trois personnes. Un quartier. Les alertes continuent pendant vos interventions.</p><ol><li>Ouvre une alerte et clique sur Intervenir.</li><li>Compare les héros, compose ton équipe, puis confirme l’envoi.</li><li>À leur arrivée, choisis une approche selon leur profil.</li></ol><p class="muted">Nuit de 4 minutes. Les outils de test sont rangés dans cette aide. La police intervient aussi.</p><details class="test-settings"><summary>Outils de prototype</summary><div class="test-tools"><button id="radio">Radio <span id="radio-count">0</span></button><span class="lab-label">LABO <b id="remaining">4 min / nuit</b></span><div><button id="pause">Pause test</button><button id="speed">×1</button><button id="replay">Rejouer</button><button id="finish">Bilan</button></div></div></details><button id="start" class="primary">Commencer la nuit <span>→</span></button></dialog>
<dialog id="summary"></dialog><dialog id="radio-dialog"><div class="dialog-heading"><h2>Radio du quartier</h2><button data-close="radio-dialog" aria-label="Fermer la radio">×</button></div><p id="impact"></p><div id="logs" role="log" aria-live="off"></div></dialog><dialog id="profiles-dialog"><div class="dialog-heading"><h2>Profils de l’équipe</h2><button data-close="profiles-dialog" aria-label="Fermer les profils">×</button></div><div id="profile-content"></div></dialog><div id="toast" role="status"></div>`;
const el=(id:string)=>document.getElementById(id)!;
// Morph existing elements instead of destroying pressed/focused controls at each tick.
function html(id:string,content:string){const target=el(id);const next=document.createElement('div');next.innerHTML=content;morphdom(target,next,{childrenOnly:true,onBeforeElUpdated:(from,to)=>{if(from.tagName==='DETAILS'&&from.hasAttribute('open'))to.setAttribute('open','');return !from.isEqualNode(to);}});}
let mobileView:'map'|'intervention'='map';
function setMobileView(view:'map'|'intervention'){mobileView=view;app.dataset.view=view;el('view-map').setAttribute('aria-pressed',String(view==='map'));el('view-intervention').setAttribute('aria-pressed',String(view==='intervention'));}
setMobileView('map');
let toastTimer=0;
function feedback(button:HTMLElement){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;button.animate([{filter:'brightness(1.35)'},{filter:'brightness(1)'}],{duration:180});}

const clock=()=>{const mins=(22*60+Math.floor(sim.time/NIGHT*480))%(24*60);return `${Math.floor(mins/60).toString().padStart(2,'0')}:${(mins%60).toString().padStart(2,'0')}`;};
function heroStatus(a:Agent){
 const mission=sim.incidents.find(i=>i.id===a.target);
 const eta=a.path.length?Math.ceil((a.path.length-a.move)*5/(a.id==='silas'?.85:1)):0;
 if(a.task==='travel')return {label:'Occupé · trajet',tone:'busy',detail:`→ ${mission?.place??'Déplacement'} · arrivée ${eta} s`};
 if(a.task==='mission')return mission?.phase==='decision'?{label:'À décider',tone:'decision',detail:mission.place}:{label:'Occupé · action',tone:'busy',detail:`${mission?.place??'Intervention'} · ${Math.max(0,Math.ceil((mission?.finishAt??sim.time)-sim.time))} s`};
 if(a.task==='return')return {label:'Retour au QG',tone:'duty',detail:eta?`Arrivée dans ${eta} s`:'Arrivée au QG'};
 if(a.task==='patrol')return {label:'Patrouille',tone:'duty',detail:a.path.length?`→ ${sim.incidents.find(i=>i.node===a.path[a.path.length-1])?.place??'Prochaine rue'} · ${eta} s`:'Réaffectable'};
 if(a.task==='investigate')return {label:'Enquête',tone:'duty',detail:'Réaffectable'};
 if(a.energy<15)return {label:a.node===5?'Récupération':'Épuisé',tone:'tired',detail:a.node===5?'Au QG':'Retour au QG possible'};
 return {label:a.node===5?'Repos au QG':'Disponible',tone:'ready',detail:a.node===5?'Disponible':sim.incidents.find(i=>i.node===a.node)?.place??'Dans le quartier'};
}
function vitals(a:Agent){return `<div class="vitals">${([{key:'hp',label:'HP',value:a.hp,max:a.maxHp,icon:'first-aid-kit'},{key:'sanity',label:'Santé mentale',value:a.sanity,max:a.maxSanity,icon:'brain'}] as const).map(v=>`<div class="vital vital-${v.key}" role="meter" aria-label="${v.label} de ${a.name}" aria-valuemin="0" aria-valuemax="${v.max}" aria-valuenow="${Math.round(v.value*10)/10}" title="${v.label} : ${Math.round(v.value*10)/10} / ${v.max}">${icon(v.icon)}<span class="segments">${Array.from({length:v.max},(_,n)=>`<i><em style="width:${Math.max(0,Math.min(1,v.value-n))*100}%"></em></i>`).join('')}</span></div>`).join('')}</div>`;}
function idleToggle(a:Agent){return `<div class="idle-setting" role="group" aria-label="Idle de ${a.name}"><span>Idle</span>${(['rest','patrol'] as const).map(task=>`<button id="idle-${a.id}-${task}" data-idle="${a.id}" data-task="${task}" aria-label="${task==='rest'?'Retour et repos au QG':'Patrouille'} — ${a.name}" title="${task==='rest'?'Retour et repos au QG':'Patrouille'}" aria-pressed="${a.idleTask===task}">${icon(task==='rest'?'home':'walk')}</button>`).join('')}</div>`;}
function toast(s:string){el('toast').textContent=s;el('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>el('toast').classList.remove('visible'),2400);}
let preparing=false;
let dispatchIncident='gare',dispatchIntent:'observe'|'intervene'='intervene';
const stats:Stat[]=['Corps','Esprit','Âme'];
const eventIcon={conflict:'shield',rescue:'lifebuoy',tech:'bolt',media:'speakerphone'} as const;
const objectives={conflict:'Mettre les civils à l’abri',rescue:'Secourir les résidents',tech:'Neutraliser le danger électrique',media:'Faire entendre notre version'};
function statBars(team:Agent[],i:Incident){return `<div class="comparison-chart" role="img" aria-label="Attributs de l’équipe comparés à la difficulté"><div class="chart-key"><span>Équipe</span><span>│ Difficulté</span></div>${stats.map(stat=>{const total=team.reduce((n,a)=>n+a.stats[stat],0),need=i.requirements[stat],used=choices[i.type].some(c=>c.stat===stat);return `<div class="stat-row ${used?'':'unused'}" style="--stat:${statColor[stat]}"><span class="stat-label">${icon(statIcon[stat])}${stat}</span><div class="bullet-track" aria-label="${stat} : équipe ${total}, difficulté ${need}${used?'':', non utilisé ici'}"><span class="bullet-fill" style="width:${Math.min(100,total/24*100)}%"></span>${used?`<i class="difficulty-marker" style="left:${need/24*100}%"></i>`:''}</div><b data-total="${stat}">${total}</b><small>${used?`/ ${need}`:'—'}</small></div>`;}).join('')}</div>`;}
function approachVisual(i:Incident,c:Choice,team:Agent[],selectable=false){const chance=sim.chance(i,c,team),tone=chanceTone(chance);return `<${selectable?'button':'div'} ${selectable?`id="choice-${i.id}-${c.id}" data-choice="${c.id}"`:''} class="visual-approach ${selectable?'choice':''}"><span class="approach-main"><strong>${c.label}</strong><span class="approach-metrics"><span style="color:${statColor[c.stat]}">${icon(statIcon[c.stat])}${c.stat}</span><span>${icon('clock')}${c.duration} s</span><span class="${c.risk?'danger':'good'}">${icon(c.risk?'first-aid-kit':'shield-check')}${c.risk?'Blessure possible':'Sans blessure'}</span></span></span>${team.length?gauge(chance,'Chance de réussite',tone):'<span class="empty-dial">—</span>'}</${selectable?'button':'div'}>`;}
function eventSummary(i:Incident){
 const remaining=Math.max(0,Math.ceil(i.deadline-sim.time)),fraction=remaining/(i.deadline-i.at),urgent=fraction<.25;
 const policeHere=sim.police.target===i.id;
 return `<div class="event-dashboard"><div class="urgency-block ${urgent?'danger':'caution'}"><span class="countdown-ring" style="--remaining:${fraction*100}%" role="img" aria-label="${remaining} secondes avant expiration"><b>${remaining}<small>s</small></b></span><span><b>Avant expiration</b><small>${icon('alert-triangle')}Inaction : confiance −1</small></span></div><div class="objective-line">${icon('target')}<span>${objectives[i.type]}</span></div><div class="event-flags"><span class="${i.known?'good':'caution'}">${icon(i.known?'eye':'eye-off')}${i.known?'Renseigné':'Infos partielles'}</span>${policeHere?`<span class="police-flag">${icon('shield')}${sim.police.path.length?'Police en route':'Police sur place'}</span>`:''}</div></div>`;
}
function openDispatch(intent:'observe'|'intervene',hero?:string){
 setMobileView('intervention');dispatchIntent=intent;selected=new Set(hero?[hero]:[]);
 dispatchIncident=selectedIncident;
 const current=sim.visible().find(i=>i.id===dispatchIncident);
 if(!current||!['signal','decision'].includes(current.phase))dispatchIncident=sim.visible().find(i=>['signal','decision'].includes(i.phase))?.id??selectedIncident;
 selectedIncident=dispatchIncident;preparing=true;render();el('dispatch-back').focus({preventScroll:true});
}
function renderDispatch(){
 el('dispatch-panel').hidden=!preparing;el('incident').hidden=preparing;if(preparing)el('incident-actions').hidden=true;app.classList.toggle('preparing',preparing);if(!preparing)return;
 const i=sim.visible().find(i=>i.id===dispatchIncident);
 const valid=!!i&&['signal','decision'].includes(i.phase)&&!sim.ended;
 const team=sim.agents.filter(a=>selected.has(a.id)&&sim.available(a));
 const onSite=i?sim.team(i):[];const combined=[...onSite,...team];
 el('dispatch-title').textContent=dispatchIntent==='observe'?'Préparer l’enquête':'Préparer l’intervention';
 html('dispatch-context',`<label class="event-select">Événement<select id="dispatch-event">${sim.visible().filter(e=>['signal','decision'].includes(e.phase)||e.id===dispatchIncident).map(e=>`<option value="${e.id}" ${e.id===dispatchIncident?'selected':''}>${e.title}${!['signal','decision'].includes(e.phase)?' — indisponible':''}</option>`).join('')}</select></label>${i?`<p class="prep-location">${icon('map-pin')}${i.place}<span class="caution">${icon('clock')}${valid?`${Math.max(0,Math.ceil((i.phase==='signal'?i.deadline:i.decisionAt+30)-sim.time))} s`:'Envoi fermé'}</span></p>`:'<p>Aucune alerte disponible.</p>'}`);
 html('dispatch-heroes',sim.agents.map((a,k)=>{const available=sim.available(a),state=heroStatus(a),picked=selected.has(a.id)&&available;const eta=i?Math.ceil(route(a.node,i.node).length*5/(a.id==='silas'?.85:1)):0;const talents=i?choices[i.type].filter(c=>a.tags.includes(c.tag)).map(c=>c.tag):[];return `<button id="pick-${a.id}" data-pick="${a.id}" class="dispatch-hero ${picked?'selected':''}" aria-label="${a.name}, ${state.label}, ${a.energy.toFixed(0)}% énergie, ${available?`arrivée ${eta} secondes`:state.detail}" aria-pressed="${picked}" ${!available?'disabled':''}><div class="hero-pick-head"><div class="portrait portrait-${k}"></div><strong>${a.name}</strong><span class="pick-state">${icon(picked?'check':available?'users':'x')}</span></div><span class="pick-status ${available?'good':'caution'}">${available?`${icon('route')}${eta} s`:state.label}</span>${vitals(a)}<div class="pick-attributes">${stats.map(stat=>`<span style="--stat:${statColor[stat]}" title="${stat}">${icon(statIcon[stat])}<i><em style="width:${a.stats[stat]*10}%"></em></i><b>${a.stats[stat]}</b></span>`).join('')}</div><span class="pick-talent ${talents.length?'good':''}">${a.injured?`${icon('first-aid-kit')}Blessé`:talents.length?`${icon('check')}${[...new Set(talents)].join(' · ')}`:'Polyvalent'}</span></button>`;}).join(''));
 html('dispatch-comparison',i?`<div class="chart-heading"><h3>${icon('users')} Équipe / difficulté</h3><small>${combined.length} héros</small></div>${statBars(combined,i)}${onSite.length?`<small class="onsite-note">${icon('map-pin')}${onSite.map(a=>a.name).join(', ')} sur place, inclus</small>`:''}<h3 class="approach-heading">${icon('target')} Chances par approche</h3><div class="approach-preview">${choices[i.type].map(c=>approachVisual(i,c,combined)).join('')}</div><details id="difficulty-help"><summary>${icon('info-circle')} Lire les graphiques</summary><p>Barre colorée : total de l’équipe. Trait blanc : difficulté. Échelle commune 0–24. Attribut grisé : non utilisé par ces approches.</p><p>À égalité : 50 % avant bonus et malus. Chaque point d’écart vaut 5 points de pourcentage. Talents, fatigue et blessures modifient la chance. Valeurs estimées avant l’arrivée.</p></details>${dispatchIntent==='observe'?`<p class="muted">${icon('search')} Enquête : trajet jusqu’au lieu, révélation immédiate des renseignements (+10 points de réussite), puis retour à la tâche Idle. Ne résout pas l’alerte.</p>`:''}`:'');
 const eta=i&&team.length?Math.max(...team.map(a=>Math.ceil(route(a.node,i.node).length*5/(a.id==='silas'?.85:1)))):0;
 el('dispatch-message').textContent=!valid?'Cet événement n’accepte plus d’envoi.':team.length?`${team.length} héros · trajet jusqu’à ${eta} s`:'Choisis au moins un héros disponible.';
 (el('confirm-dispatch') as HTMLButtonElement).disabled=!valid||!team.length;
 el('confirm-dispatch').textContent=dispatchIntent==='observe'?'Envoyer enquêter →':'Envoyer l’équipe →';
}
function phaseTrack(i:Incident){
 const travelling=sim.agents.some(a=>a.target===i.id&&a.task==='travel');
 const active=['resolved','missed'].includes(i.phase)?3:i.phase==='working'?2:i.phase==='decision'?1:travelling?0:-1;
 return `<ol class="phase-track" aria-label="Déroulement de l’intervention">${['Trajet','Choix','Action','Bilan'].map((name,k)=>`<li class="${k===active?'current':k<active?'passed':''}" ${k===active?'aria-current="step"':''}>${icon((['route','list-check','player-play','flag'] as const)[k])}<span>${name}</span></li>`).join('')}</ol>`;
}
function historyMarkup(i:Incident){return i.history.length?`<ol class="event-history">${i.history.map(h=>`<li><time>+${Math.floor(h.time-i.at)} s</time><span>${h.text}</span></li>`).join('')}</ol>`:'';}
function actionDescription(i:Incident){const descriptions:Record<string,string>={talk:'L’équipe négocie avec les agresseurs pour libérer les civils.',secure:'L’équipe s’interpose et met les civils à l’abri.',evacuate:'L’équipe accompagne les résidents par les escaliers.',guide:'L’équipe guide les résidents vers le toit.',repair:'L’équipe isole le circuit pour supprimer le danger électrique.',cordon:'L’équipe éloigne les passants et bloque l’accès dangereux.',explain:'L’équipe donne sa version des faits à la journaliste.',evidence:'L’équipe présente les éléments recueillis à la journaliste.'};return descriptions[i.choice?.id??'']??'';}
function render(){
 el('clock').textContent=clock();el('remaining').textContent=`${Math.max(0,Math.ceil(NIGHT-sim.time))} s avant la relève`;el('impact').textContent=`${sim.saved} civils aidés · confiance ${sim.trust>0?'+':''}${sim.trust}`;
 const visible=sim.visible();el('nav-alerts').textContent=String(visible.filter(i=>!['resolved','missed'].includes(i.phase)).length);el('nav-decisions').textContent=visible.some(i=>i.phase==='decision')?'À décider':'';el('count').textContent=`${visible.filter(i=>!['resolved','missed'].includes(i.phase)).length} actives`;
 html('alerts',visible.map(i=>`<button id="alert-${i.id}" data-incident="${i.id}" class="alert-pill ${i.id===selectedIncident?'selected':''} ${['resolved','missed'].includes(i.phase)?'done':''}"><span>${i.phase==='resolved'?'✓':i.phase==='missed'?'—':'!'}</span>${i.title}${i.phase==='decision'?'<b>CHOIX</b>':i.phase==='working'?`<b>${Math.floor(sim.progress(i))}%</b>`:''}</button>`).join(''));
 html('agents',sim.agents.map((a,k)=>{const state=heroStatus(a),mission=sim.incidents.find(i=>i.id===a.target);return `<article id="slot-${a.id}" class="agent-slot"><button id="agent-${a.id}" class="agent ${selected.has(a.id)?'selected':''} state-${state.tone}" data-agent="${a.id}" aria-pressed="${selected.has(a.id)}" aria-label="${a.name}, ${state.label}, ${state.detail}${mission?', '+mission.title:''}"><div class="agent-top"><div id="portrait-${a.id}" class="portrait portrait-${k}"></div><strong class="agent-name">${a.name}</strong></div>${vitals(a)}<div class="hero-current status-${state.tone}"><strong class="hero-status">${icon(a.task==='travel'?'route':a.task==='return'?'home':a.task==='patrol'?'walk':a.task==='mission'?'target':'check')}${state.label}</strong><span class="hero-activity">${state.detail}${mission?`<small>${mission.title}</small>`:''}</span></div></button>${idleToggle(a)}</article>`;}).join(''));
 html('profile-content',sim.agents.map((a,k)=>`<article class="profile"><div class="portrait portrait-${k}"></div><h3>${a.name} <small>${a.role}</small></h3><p><b>${heroStatus(a).label}</b> · ${heroStatus(a).detail}${a.injured?' · Blessé':''}</p>${vitals(a)}${idleToggle(a).replace(/ id="[^"]+"/g,'')}<p>Énergie ${Math.round(a.energy)} %</p><p>Corps ${a.stats.Corps} · Esprit ${a.stats.Esprit} · Âme ${a.stats['Âme']}</p><div class="tags">${a.tags.map((t,n)=>`<span class="${n===2?'flaw':''}">${t}</span>`).join('')}</div></article>`).join(''));
 el('radio-count').textContent=String(sim.logs.length);

 const i=visible.find(i=>i.id===selectedIncident)||visible[0];if(i){selectedIncident=i.id;const team=sim.team(i);const enroute=sim.agents.filter(a=>a.target===i.id&&a.task==='travel');const usable=sim.agents.filter(a=>selected.has(a.id)&&sim.available(a));
 let controls='',dispatchControls='';if(i.phase==='signal'||i.phase==='decision')dispatchControls=`<div id="dispatch" class="dispatch">${!i.known?'<p class="recon-hint">Enquêter : révéler les infos · +10 points de réussite</p>':''}<div class="actions"><button id="send-observe" data-prepare="observe" ${i.known?'disabled title="Renseignements déjà obtenus"':''}>${icon('search')}Enquêter</button><button id="send-intervene" data-prepare="intervene" class="primary">${icon('users')}${team.length?'Renforcer':'Intervenir'} →</button></div></div>`;
 if(i.phase==='decision')controls=`<div id="decision-${i.id}" class="decision"><span class="eyebrow">SUR PLACE · ${team.map(a=>a.name).join(' + ')}</span><p>${i.reveal}</p>${choices[i.type].map(c=>approachVisual(i,c,team,true)).join('')}</div>`+controls;
 if(i.phase==='working')controls=`<div class="working"><span class="eyebrow">INTERVENTION EN COURS</span><h3>${i.choice!.label}</h3><p class="action-description">${actionDescription(i)}</p><div class="progress" role="progressbar" aria-label="Résolution de l’intervention" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.floor(sim.progress(i))}"><span style="width:${sim.progress(i)}%"></span></div><p><b>${Math.floor(sim.progress(i))}% résolu</b> · ${Math.max(0,Math.ceil(i.finishAt-sim.time))} s restantes · ${team.map(a=>a.name).join(' + ')}</p><p class="muted">Résultat à la fin de cette action. Aucune autre décision pendant son exécution.</p></div>`;
 if(['resolved','missed'].includes(i.phase))controls=`<div class="outcome ${i.phase==='missed'?'bad':''}"><span class="eyebrow">${i.police?'POLICE':i.phase==='missed'?'ALERTE TERMINÉE':'INTERVENTION TERMINÉE'}</span><h3>${i.outcome?.replace(/ · jet \d+ \/ \d+%/, '')??''}</h3>${i.report?`<p><b>${i.report.names.join(' + ')}</b> · ${i.choice!.label} · ${i.choice!.duration} s d’action</p><div class="report-impact"><span>${icon('users')}<b>${i.report.civils}</b><small>Civils aidés</small></span><span>${icon('heart')}<b>${i.report.trust>=0?'+':''}${i.report.trust}</b><small>Confiance</small></span><span class="${i.report.injured.length?'danger':'good'}">${icon('first-aid-kit')}<b>${i.report.injured.length}</b><small>Blessure(s)</small></span></div><p>${i.report.injured.length?`Blessure : ${i.report.injured.join(', ')}.`:'Aucune blessure durant cette action.'} Les héros reprennent leur tâche par défaut.</p><details id="result-calculation-${i.id}"><summary>Détail du résultat</summary><p>Chance finale : ${i.report.chance} %. Tirage : ${i.report.roll}/100. Le tirage doit être inférieur ou égal à la chance.</p></details>`:''}</div>${historyMarkup(i)}`;
 const decisionRemaining=Math.max(0,Math.min(30,i.decisionAt+30-sim.time));
 el('decision-timer').hidden=i.phase!=='decision';
 html('decision-timer',i.phase==='decision'?`<div class="decision-countdown ${decisionRemaining<=10?'urgent':''}"><div class="decision-countdown-label">${icon('clock')}<span>Décision automatique dans</span><strong>${Math.ceil(decisionRemaining)} s</strong></div><div class="decision-time-track" role="progressbar" aria-label="Temps restant pour choisir" aria-valuemin="0" aria-valuemax="30" aria-valuenow="${decisionRemaining.toFixed(1)}" aria-valuetext="${Math.ceil(decisionRemaining)} secondes restantes"><span style="width:${decisionRemaining/30*100}%"></span></div></div>`:'');
 html('incident-actions',dispatchControls);el('incident-actions').hidden=preparing||!dispatchControls;
 html('incident',`<div id="incident-head" class="incident-head"><span class="eyebrow event-place">${icon(eventIcon[i.type])}${i.place.toUpperCase()}</span><h2>${i.title}</h2>${phaseTrack(i)}${i.phase==='signal'?`${eventSummary(i)}<p class="event-brief">${i.brief}</p>`:''}</div>${i.known&&i.phase==='signal'?`<div class="intel"><b>RENSEIGNEMENTS +10%</b><p>${i.reveal}</p></div>`:''}${enroute.length?`<div class="arrival">${enroute.map(a=>`<p>${a.name} en route → <b>${i.place}</b> · arrivée ${Math.ceil((a.path.length-a.move)*5/(a.id==='silas'?.85:1))} s</p>`).join('')}</div>`:''}${controls}`);
 }
 html('logs',sim.logs.slice(0,14).map(l=>`<div><time>+${Math.floor(l.time)}s</time><span>${l.text}</span></div>`).join('')||'<p class="muted">La radio est silencieuse.</p>');
 el('selection-label').textContent=`${sim.agents.filter(a=>sim.available(a)).length} disponibles`;renderDispatch();
 el('pause').textContent=paused?'Reprendre':'Pause test';el('speed').textContent=`×${speed}`;
}
function reset(){setMobileView('map');preparing=false;sim=new Simulation(seed);selectedIncident='gare';selected=new Set<string>();paused=false;sim.start();render();}
function summary(){preparing=false;renderDispatch();const d=el('summary') as HTMLDialogElement;d.innerHTML=`<span class="eyebrow">FIN DE SERVICE / ${clock()}</span><h1>La nuit laisse<br>des traces.</h1><div class="results"><div><b>${sim.saved}</b>Civils aidés</div><div><b>${sim.trust>0?'+':''}${sim.trust}</b>Confiance</div><div><b>${sim.agents.filter(a=>a.injured).length}</b>Blessé(s)</div></div>${sim.incidents.map(i=>`<div class="report"><b>${i.title}</b><p>${i.outcome||'Pas encore signalée.'}</p></div>`).join('')}<p class="muted">À observer : choix des agents, utilité de l’enquête, temps morts et décisions prises par défaut.</p><button id="same-night" class="primary">Rejouer la même nuit</button><button id="new-night">Varier les jets</button>`;d.showModal();el('same-night').onclick=()=>{d.close();reset();};el('new-night').onclick=()=>{seed++;d.close();reset();};}
app.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('button');if(!b)return;feedback(b);
 if(b.dataset.idle){sim.setIdleTask(b.dataset.idle,b.dataset.task as IdleTask);render();}
 if(b.dataset.view)setMobileView(b.dataset.view as 'map'|'intervention');
 if(b.dataset.incident){setMobileView('intervention');preparing=false;selected.clear();selectedIncident=b.dataset.incident;render();map.focus();}
 if(b.dataset.agent){const a=sim.agents.find(a=>a.id===b.dataset.agent)!;if(a.target&&['travel','mission'].includes(a.task)){setMobileView('intervention');preparing=false;selected.clear();selectedIncident=a.target;render();map.focus();}else openDispatch('intervene',a.id);}
 if(b.id==='dispatch-back'){preparing=false;selected.clear();render();el('send-intervene')?.focus({preventScroll:true});}
 if(b.dataset.close)(el(b.dataset.close) as HTMLDialogElement).close();
 if(b.dataset.prepare)openDispatch(b.dataset.prepare as 'observe'|'intervene');
 if(b.dataset.pick){const a=sim.agents.find(a=>a.id===b.dataset.pick)!;if(sim.available(a)){selected.has(a.id)?selected.delete(a.id):selected.add(a.id);}render();}
 if(b.id==='confirm-dispatch'){
  const ok=sim.dispatch(dispatchIncident,[...selected],dispatchIntent);
  if(ok){selectedIncident=dispatchIncident;selected.clear();preparing=false;el('incident').scrollTop=0;toast(dispatchIntent==='observe'?'Enquête assignée. Agents en route.':'Ordre reçu. Agents en route.');map.focus();}else toast('Envoi impossible : vérifie l’événement et les héros disponibles.');render();
 }
 if(b.dataset.choice){if(sim.choose(selectedIncident,b.dataset.choice))toast('Approche confirmée. Intervention en cours.');render();}
 if(b.dataset.duty){let n=0;for(const id of selected)if(b.dataset.duty==='investigate'?sim.assign(id,'investigate'):sim.setIdleTask(id,b.dataset.duty==='patrol'?'patrol':'rest'))n++;toast(n?`${n} agent(s) réaffecté(s).`:'Sélectionne un agent disponible.');render();}
});
app.addEventListener('change',e=>{const select=e.target as HTMLSelectElement;if(select.id==='dispatch-event'){dispatchIncident=select.value;selectedIncident=dispatchIncident;render();map.focus();}if(select.dataset.idle){sim.setIdleTask(select.dataset.idle,select.value as IdleTask);render();}});
el('radio').onclick=()=>{(el('intro') as HTMLDialogElement).close();(el('radio-dialog') as HTMLDialogElement).showModal();};
el('profiles').onclick=()=>{(el('profiles-dialog') as HTMLDialogElement).showModal();};
el('start').onclick=()=>{(el('intro') as HTMLDialogElement).close();sim.start();render();};
el('help').onclick=()=>{el('start').textContent=sim.started?'Retour au quartier':'Commencer la nuit →';(el('intro') as HTMLDialogElement).showModal();};
el('pause').onclick=()=>{paused=!paused;render();};el('speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;render();};el('replay').onclick=()=>{(el('intro') as HTMLDialogElement).close();reset();};el('finish').onclick=()=>{(el('intro') as HTMLDialogElement).close();sim.finish();render();summary();};
const map=createMap('map',()=>sim,id=>{setMobileView('intervention');preparing=false;selected.clear();selectedIncident=id;render();},()=>selectedIncident);el('map-reset').onclick=()=>map.reset();el('zoomin').onclick=()=>map.zoom(.2);el('zoomout').onclick=()=>map.zoom(-.2);
render();(el('intro') as HTMLDialogElement).showModal();
let last=performance.now(),acc=0;function loop(now:number){const dt=Math.min((now-last)/1000,.5);last=now;const was=sim.ended;if(!paused)sim.tick(dt*speed);map.update();acc+=dt;if(acc>.2){render();acc=0;}if(!was&&sim.ended)summary();requestAnimationFrame(loop);}requestAnimationFrame(loop);
// Read-only snapshot for automated prototype checks. No account or remote state.
Object.defineProperty(window,'vigilante',{get:()=>({time:sim.time,started:sim.started,ended:sim.ended,agents:sim.agents,incidents:sim.incidents,logs:sim.logs})});
