import type {Map as MapLibreMap,GeoJSONSource} from 'maplibre-gl';
export type Lightning={enabled:boolean;strength:number;color:string;minInterval:number;maxInterval:number;minFlashes?:number;maxFlashes?:number;minGap?:number;maxGap?:number;flashDuration?:number};
export const defaultLightning:Lightning={enabled:false,strength:.35,color:'#cadcff',minInterval:8,maxInterval:24,minFlashes:2,maxFlashes:2,minGap:180,maxGap:360,flashDuration:280};
export type Weather={enabled:boolean;intensity:number;speed:number;wind:number;opacity:number;color:string;splashes:boolean;lightning?:Lightning};
export const defaultWeather:Weather={enabled:false,intensity:.45,speed:1,wind:.2,opacity:.4,color:'#a6c5dd',splashes:true,lightning:{...defaultLightning}};
export function readWeather(value:unknown):Weather{if(value===undefined)return structuredClone(defaultWeather);const w=value as Weather;if(!w||typeof w.enabled!=='boolean'||typeof w.splashes!=='boolean'||!/^#[0-9a-f]{6}$/i.test(w.color)||!Number.isFinite(w.intensity)||w.intensity<0||w.intensity>1||!Number.isFinite(w.opacity)||w.opacity<0||w.opacity>1||!Number.isFinite(w.speed)||w.speed<.25||w.speed>2||!Number.isFinite(w.wind)||Math.abs(w.wind)>1)throw Error('Pluie invalide');const l={...defaultLightning,...w.lightning};if(typeof l.enabled!=='boolean'||!Number.isFinite(l.strength)||l.strength<0||l.strength>1||!/^#[0-9a-f]{6}$/i.test(l.color)||!Number.isFinite(l.minInterval)||!Number.isFinite(l.maxInterval)||l.minInterval<2||l.maxInterval>120||l.maxInterval<l.minInterval)throw Error('Éclairs invalides');if(!Number.isInteger(l.minFlashes)||!Number.isInteger(l.maxFlashes)||l.minFlashes!<1||l.maxFlashes!>8||l.maxFlashes!<l.minFlashes!||!Number.isFinite(l.minGap)||!Number.isFinite(l.maxGap)||l.minGap!<50||l.maxGap!>1500||l.maxGap!<l.minGap!||!Number.isFinite(l.flashDuration)||l.flashDuration!<100||l.flashDuration!>1000)throw Error('Rafale d’éclairs invalide');return {...structuredClone(w),lightning:{...l}};}
export function createRain(viewport:HTMLElement,parent:HTMLElement,state:()=>Weather,changed:()=>void,map?:MapLibreMap){
 const panel=document.createElement('section');panel.className='rain-controls';parent.append(panel);
 const canvas=document.createElement('canvas');canvas.className='weather-rain';canvas.setAttribute('aria-hidden','true');viewport.append(canvas);const ctx=canvas.getContext('2d')!;
 const flash=document.createElement('div');flash.className='weather-lightning';flash.setAttribute('aria-hidden','true');viewport.append(flash);let lightningTimer:ReturnType<typeof setTimeout>|undefined,flashAnimation:Animation|undefined;
 function strike(){if(!state().lightning?.enabled||document.hidden)return;const l=state().lightning!,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,sequence=lightningSequence(l);flash.style.background=l.color;flashAnimation?.cancel();flashAnimation=flash.animate(reduced?[{opacity:0},{opacity:l.strength*.1,offset:.4},{opacity:0}]:sequence.frames,{duration:reduced?1000:sequence.duration});}

 function scheduleLightning(){clearTimeout(lightningTimer);const l=state().lightning;if(!l?.enabled||document.hidden)return;lightningTimer=setTimeout(()=>{strike();scheduleLightning();},1000*(l.minInterval+Math.random()*(l.maxInterval-l.minInterval)));}
 const splashSource='scene-rain-splashes';let lastSplashUpdate=0;
 function groundLayer(){if(!map)return;if(!map.getSource(splashSource))map.addSource(splashSource,{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer(splashSource)){map.addLayer({id:splashSource,type:'circle',source:splashSource,paint:{'circle-radius':['get','radius'],'circle-color':state().color,'circle-opacity':0,'circle-stroke-color':state().color,'circle-stroke-width':1.5,'circle-stroke-opacity':['get','opacity'],'circle-pitch-alignment':'map','circle-pitch-scale':'viewport'}},map.getStyle().layers.find(l=>l.type==='fill-extrusion')?.id);}}
 function clearGround(){lastSplashUpdate=0;}
 function updateSplashes(now:number,clear=false){if(!map)return;groundLayer();if(!clear&&now-lastSplashUpdate<50)return;lastSplashUpdate=now;const w=state();(map.getSource(splashSource) as GeoJSONSource).setData({type:'FeatureCollection',features:clear||!w.enabled||!w.splashes?[]:drops.filter(d=>d.splash>0&&d.coord).map(d=>({type:'Feature',properties:{radius:2+(1-d.splash/.65)*8,opacity:Math.min(1,w.opacity*2.4)*(d.splash/.65)},geometry:{type:'Point',coordinates:d.coord!}}))});map.setPaintProperty(splashSource,'circle-stroke-color',w.color);}
 viewport.addEventListener('buildings-updated',()=>{if(map?.getLayer(splashSource)){const first=map.getStyle().layers.find(l=>l.type==='fill-extrusion');if(first)map.moveLayer(splashSource,first.id);}});
 let raf=0,last=0,width=0,height=0,drops:{x:number;y:number;depth:number;ground:number;splash:number;coord?:[number,number]}[]=[];
 function resize(){clearGround();width=viewport.clientWidth;height=viewport.clientHeight;const ratio=Math.min(devicePixelRatio,1.5);canvas.width=width*ratio;canvas.height=height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);drops=[];}
 function controls(){const w=state();panel.innerHTML=`<h2>Pluie</h2><label class="check"><input id="rain-enabled" data-rain="enabled" type="checkbox" ${w.enabled?'checked':''}>Pluie sur la carte</label>${[['intensity','Densité',0,1,.05],['speed','Vitesse',.25,2,.05],['wind','Vent',-1,1,.05],['opacity','Visibilité',0,1,.05]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-rain-out="${key}">${w[key as keyof Weather]}</output><input data-rain="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${w[key as keyof Weather]}"></label>`).join('')}<label class="color-row">Teinte<input data-rain="color" type="color" value="${w.color}"></label><label class="check"><input data-rain="splashes" type="checkbox" ${w.splashes?'checked':''}>Éclaboussures au sol</label><h2>Éclairs</h2><label class="check"><input id="lightning-enabled" data-lightning="enabled" type="checkbox" ${w.lightning?.enabled?'checked':''}>Flashs d’éclairs</label>${[['strength','Force',0,1,.05],['minInterval','Intervalle minimum (s)',2,120,1],['maxInterval','Intervalle maximum (s)',2,120,1],['minFlashes','Flashs minimum par éclair',1,8,1],['maxFlashes','Flashs maximum par éclair',1,8,1],['flashDuration','Durée d’un flash (ms)',100,1000,20],['minGap','Pause minimum entre flashs (ms)',50,1500,10],['maxGap','Pause maximum entre flashs (ms)',50,1500,10]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-lightning-out="${key}">${w.lightning?.[key as keyof Lightning]}</output><input data-lightning="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${w.lightning?.[key as keyof Lightning]}"></label>`).join('')}<label class="color-row">Couleur de l’éclair<input data-lightning="color" type="color" value="${w.lightning?.color}"></label><button id="lightning-test">Tester un éclair</button>`;}
 function tick(now:number){raf=0;const w=state();ctx.clearRect(0,0,width,height);if(!w.enabled||document.hidden)return;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,dt=Math.min(.05,(now-(last||now))/1000);last=now;const count=Math.min(550,Math.round(width*height/2800*w.intensity*(reduced?.3:1)));while(drops.length<count)drops.push({x:Math.random()*width,y:Math.random()*height,depth:.3+Math.random()*.7,ground:height*(.15+Math.random()*.85),splash:0});drops.length=count;ctx.strokeStyle=w.color;ctx.lineWidth=1;for(const d of drops){const fall=(280+400*d.depth)*w.speed*(reduced?.35:1),dx=w.wind*fall*.4,dy=fall;if(d.splash>0){d.splash-=dt;if(w.splashes&&!map){const t=1-d.splash/.65;ctx.globalAlpha=Math.min(1,w.opacity*1.8)*(1-t);ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(d.x,d.ground,1+t*5,.5+t*2,0,0,Math.PI*2);ctx.stroke();}if(d.splash<=0){d.y=-20;d.x=Math.random()*width;d.ground=height*(.15+Math.random()*.85);}continue;}d.x+=dx*dt;d.y+=dy*dt;if(d.y>d.ground){d.splash=.65;if(map){const c=map.unproject([d.x,d.ground]);d.coord=[c.lng,c.lat];}continue;}if(d.x<-50)d.x=width+30;if(d.x>width+50)d.x=-30;ctx.globalAlpha=w.opacity*(.25+.65*d.depth);const length=(6+16*d.depth)*w.speed;ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(d.x-dx/dy*length,d.y-length);ctx.stroke();}ctx.globalAlpha=1;updateSplashes(now);raf=requestAnimationFrame(tick);}
 function refresh(){updateSplashes(performance.now(),true);scheduleLightning();cancelAnimationFrame(raf);raf=0;last=0;canvas.hidden=!state().enabled;controls();if(state().enabled)raf=requestAnimationFrame(tick);else ctx.clearRect(0,0,width,height);}
 panel.addEventListener('click',e=>{if((e.target as HTMLElement).closest('#lightning-test')){const l=state().lightning!;const was=l.enabled;l.enabled=true;strike();l.enabled=was;}});
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement;if(el.dataset.lightning){const key=el.dataset.lightning as keyof Lightning,l=state().lightning!;(l as unknown as Record<string,unknown>)[key]=el.type==='checkbox'?el.checked:el.type==='color'?el.value:Number(el.value);if(key==='minInterval')l.maxInterval=Math.max(l.maxInterval,l.minInterval);if(key==='maxInterval')l.minInterval=Math.min(l.minInterval,l.maxInterval);for(const [min,max] of [['minFlashes','maxFlashes'],['minGap','maxGap']] as const){if(key===min)l[max]=Math.max(l[max]!,l[min]!);if(key===max)l[min]=Math.min(l[min]!,l[max]!);}for(const k of ['minInterval','maxInterval','strength','minFlashes','maxFlashes','minGap','maxGap','flashDuration'] as const){panel.querySelector<HTMLOutputElement>(`[data-lightning-out="${k}"]`)!.value=String(l[k]);panel.querySelector<HTMLInputElement>(`[data-lightning="${k}"]`)!.value=String(l[k]);}scheduleLightning();if(!l.enabled)flashAnimation?.cancel();changed();return;}const key=el.dataset.rain as keyof Weather;if(!key)return;(state() as unknown as Record<string,unknown>)[key]=el.type==='checkbox'?el.checked:el.type==='color'?el.value:Number(el.value);const out=panel.querySelector(`[data-rain-out="${key}"]`);if(out)out.textContent=el.value;canvas.hidden=!state().enabled;updateSplashes(performance.now(),true);cancelAnimationFrame(raf);raf=0;last=0;if(state().enabled)raf=requestAnimationFrame(tick);else ctx.clearRect(0,0,width,height);changed();});
 new ResizeObserver(resize).observe(viewport);document.addEventListener('visibilitychange',()=>{scheduleLightning();last=0;cancelAnimationFrame(raf);raf=0;if(!document.hidden&&state().enabled)raf=requestAnimationFrame(tick);});resize();refresh();return {refresh};
}

export function lightningSequence(lightning:Lightning,random= Math.random){const l={...defaultLightning,...lightning},count=l.minFlashes!+Math.floor(random()*(l.maxFlashes!-l.minFlashes!+1)),points:{time:number;opacity:number}[]=[{time:0,opacity:0}];let time=0;for(let i=0;i<count;i++){points.push({time:time+l.flashDuration!*.25,opacity:l.strength*(i===0?.65:.5)});time+=l.flashDuration!;points.push({time,opacity:0});if(i<count-1){time+=l.minGap!+random()*(l.maxGap!-l.minGap!);points.push({time,opacity:0});}}return {count,duration:time,frames:points.map(p=>({offset:p.time/time,opacity:p.opacity}))};}
