import {connectedBuildingBlock,type BuildingPart} from './map-building-block';
import {convertFilter} from '@maplibre/maplibre-gl-style-spec';
import type {Map as MapLibreMap,GeoJSONSource,FilterSpecification,LayerSpecification} from 'maplibre-gl';
import type {Feature,Polygon,MultiPolygon} from 'geojson';
import {buildingCenter,buildingSelector,buildingParts,polygonContains,pickBuildingPart,type BuildingEdit} from './map-building-state';
import {rubbleFeatures} from './map-rubble';
import {icon} from './icons';
import type {JuiceTarget} from './map-juice';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createBuildings(map:MapLibreMap,viewport:HTMLElement,parent:HTMLElement,state:()=>BuildingEdit[],points:()=>{id:string;name:string}[],changed:()=>void,event:(id:string,event:string)=>void=()=>{},select:(id?:string)=>void=()=>{}){
 let picking=false,single=false,selected:string|undefined;const handled=new WeakSet<Event>(),original=new Map<string,FilterSpecification|undefined>(),anchors=new Map<string,HTMLElement>();let repaintTimer:ReturnType<typeof setTimeout>|undefined;
 const sourceShapes=new Map<string,Map<string,Feature>>();
 const layers=()=>map.getStyle().layers.filter(l=>!l.id.startsWith('scene-')&&((('source-layer'in l)&&l['source-layer']==='building')||/building/i.test(l.id))&&['fill','fill-extrusion','line'].includes(l.type));
 for(const l of layers())original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);
 const panel=document.createElement('details');panel.id='building-tools';panel.open=true;panel.innerHTML='<summary>Bâtiments interactifs</summary><div class="fields"><div class="pair"><button id="pick-building">Choisir un bloc</button><button id="pick-single-building">Choisir un bâtiment unique</button></div><div id="building-list"></div><div id="building-editor"></div><p class="hint">Effets : onglet Juice → Bâtiments. Détruire déclenche « destroyed ».</p></div>';parent.append(panel);
 map.addSource('scene-buildings',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addSource('scene-building-remainders',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 const color:any=['coalesce',['feature-state','juiceColor'],['get','color']];
 map.addLayer({id:'scene-building-ground',type:'fill',source:'scene-buildings',paint:{'fill-color':color,'fill-opacity':['case',['get','destroyed'],1,.07]}});
 map.addLayer({id:'scene-building-volume',type:'fill-extrusion',source:'scene-buildings',filter:['==',['get','destroyed'],true],paint:{'fill-extrusion-color':color,'fill-extrusion-height':['get','height'],'fill-extrusion-opacity':1}});
 map.addLayer({id:'scene-building-edge',type:'line',source:'scene-buildings',paint:{'line-color':color,'line-width':2,'line-opacity':.85}});
 map.addSource('scene-block-hover',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-block-hover-volume',type:'fill',source:'scene-block-hover',paint:{'fill-color':'#78dcde','fill-opacity':.08}});
 map.addSource('scene-rubble',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-rubble',type:'fill-extrusion',source:'scene-rubble',paint:{'fill-extrusion-color':['get','color'],'fill-extrusion-height':['get','height'],'fill-extrusion-base':0,'fill-extrusion-opacity':1}});
 map.addLayer({id:'scene-block-hover-edge',type:'line',source:'scene-block-hover',paint:{'line-color':'#b8ffff','line-width':2.5}});
 let hoverParts:BuildingPart[]=[],hoverStamp=0,poolCache=new Map<string,BuildingPart[]>();
 const clearHover=()=>{hoverParts=[];(map.getSource('scene-block-hover') as GeoJSONSource).setData({type:'FeatureCollection',features:[]});};
 function pick(point:{x:number;y:number}){
  const feature=map.queryRenderedFeatures([point.x,point.y],{layers:[...layers().map(l=>l.id),...layers().map(l=>`scene-building-copy-${l.id}`),'scene-building-volume','scene-building-ground'].filter(id=>!!map.getLayer(id))}).find(f=>['Polygon','MultiPolygon'].includes(f.geometry.type));if(!feature)return;
  if(feature.source==='scene-buildings'){const edit=state().find(b=>b.id===String(feature.properties.editId||feature.id));if(edit)return {edit,parts:edit.parts||buildingParts(edit.geometry).map(coordinates=>({geometry:{type:'Polygon' as const,coordinates},height:edit.height})),source:edit.source,sourceLayer:edit.sourceLayer};return;}
  if(!feature.source.startsWith('scene-')){const key=`${feature.source}:${feature.sourceLayer||''}`;if(!sourceShapes.has(key))sourceShapes.set(key,new Map());sourceShapes.get(key)!.set(JSON.stringify(feature.geometry),{type:'Feature',properties:feature.properties,geometry:feature.geometry});}
  const copy=feature.source==='scene-building-remainders',origin=copy?layers().find(l=>`scene-building-copy-${l.id}`===feature.layer.id):feature.layer;if(!origin||!('source'in origin))return;
  const height=Math.max(0,Math.min(1000,Number(feature.properties.render_height??feature.properties.height??8)||8)),factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1,lat=map.unproject([point.x,point.y]).lat,lift=feature.layer.type==='fill-extrusion'?height*factor*Math.sin(map.getPitch()*Math.PI/180)/(156543.03*Math.cos(lat*Math.PI/180)/2**map.getZoom()):0,geometry=pickBuildingPart(feature.geometry as Polygon|MultiPolygon,[point.x,point.y],p=>{const q=map.project(p as [number,number]);return [q.x,q.y];},lift),source=origin.source,sourceLayer='source-layer'in origin?origin['source-layer']:undefined,key=`${source}:${sourceLayer||''}`;
  let pool=poolCache.get(key);if(!pool){pool=[];for(const f of map.querySourceFeatures(source,sourceLayer?{sourceLayer}:{})){if(!['Polygon','MultiPolygon'].includes(f.geometry.type))continue;const h=Math.max(0,Math.min(1000,Number(f.properties?.render_height??f.properties?.height??8)||8));for(const coordinates of buildingParts(f.geometry as Polygon|MultiPolygon))pool.push({geometry:{type:'Polygon',coordinates},height:h});}poolCache.set(key,pool);}
  return {parts:single?[{geometry,height}]:connectedBuildingBlock({geometry,height},pool),source,sourceLayer};
 }
 map.on('mousemove',e=>{if(!picking||performance.now()-hoverStamp<80)return;hoverStamp=performance.now();const hit=pick(e.point);hoverParts=hit?.parts||[];const factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1;(map.getSource('scene-block-hover') as GeoJSONSource).setData({type:'FeatureCollection',features:hoverParts.map(part=>({type:'Feature',properties:{height:part.height*factor+.3},geometry:part.geometry}))});map.getCanvas().style.cursor=hit?'pointer':'crosshair';});
 map.getCanvas().addEventListener('mouseleave',clearHover);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&picking){picking=false;clearHover();map.getCanvas().style.cursor='';render();}});
 function render(){panel.querySelector('#pick-building')!.setAttribute('aria-pressed',String(picking&&!single));panel.querySelector('#pick-single-building')!.setAttribute('aria-pressed',String(picking&&single));panel.querySelector('#building-list')!.innerHTML=state().map(b=>`<button class="building-row" data-building="${esc(b.id)}">${icon(b.destroyed?'x':'target')}${esc(b.name)}${b.destroyed?' · détruit':''}</button>`).join('');const b=state().find(b=>b.id===selected),editor=panel.querySelector<HTMLElement>('#building-editor')!;editor.hidden=!b;if(!b)return;editor.innerHTML=`<label>Nom<input id="building-name" maxlength="80" value="${esc(b.name)}"></label><label class="color-row">Couleur<input id="building-color" type="color" value="${b.color}"></label><label class="color-row">Couleur détruite<input id="building-destroyed-color" type="color" value="${b.destroyedColor||'#34302d'}"></label><label>Point associé<select id="building-point"><option value="">Aucun</option>${points().map(p=>`<option value="${esc(p.id)}" ${b.point===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><div class="pair"><button id="building-center">${icon('target')}Centrer</button><button id="building-destroy" ${b.destroyed?'disabled':''}>${icon('bolt')}Détruire</button></div><button id="building-restore" ${b.destroyed?'':'disabled'}>Restaurer le bâtiment</button><button id="building-forget">Retirer la personnalisation</button>`;}
 function paint(){const remainder:Feature<Polygon|MultiPolygon>[]=[],groups=new Map<string,{features:Feature<Polygon|MultiPolygon>[];masks:any[]}>();for(const l of layers()){if(!('source'in l))continue;if(!original.has(l.id))original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);const sourceLayer='source-layer'in l?l['source-layer']:undefined,key=`${l.source}:${sourceLayer||''}`,edits=state().filter(b=>b.destroyed&&b.source===l.source&&b.sourceLayer===sourceLayer);let group=groups.get(key);if(!group){group={features:[],masks:[]};groups.set(key,group);if(edits.length){const seen=new Set<string>();let fs:Feature[]=[];try{let cache=sourceShapes.get(key);if(!cache){cache=new Map();sourceShapes.set(key,cache);}for(const f of map.queryRenderedFeatures({layers:layers().filter(v=>'source'in v&&v.source===l.source&&('source-layer'in v?v['source-layer']:undefined)===sourceLayer).map(v=>v.id)})){if(['Polygon','MultiPolygon'].includes(f.geometry.type))cache.set(JSON.stringify(f.geometry),{type:'Feature',properties:f.properties,geometry:f.geometry});}fs=[...cache.values()];}catch{}for(const f of fs){if(!['Polygon','MultiPolygon'].includes(f.geometry.type))continue;const signature=JSON.stringify(f.geometry);if(seen.has(signature))continue;seen.add(signature);const parts=buildingParts(f.geometry as Polygon|MultiPolygon),kept=parts.filter(r=>!edits.some(b=>buildingParts(b.geometry).some(er=>polygonContains(buildingCenter({geometry:{type:'Polygon',coordinates:r}} as BuildingEdit),er))));if(kept.length===parts.length)continue;group.masks.push(buildingSelector({geometry:f.geometry} as BuildingEdit));if(kept.length)group.features.push({type:'Feature',properties:{...f.properties,__group:key},geometry:{type:'MultiPolygon',coordinates:kept}});}}remainder.push(...group.features);}
 const base=original.get(l.id),filters=[...edits.map(buildingSelector),...group.masks].map(v=>['!',v]);map.setFilter(l.id,(filters.length?['all',...(base?[convertFilter(base)]:[]),...filters]:base) as FilterSpecification|undefined);
 const cloneId=`scene-building-copy-${l.id}`,spec:any={...structuredClone(l),id:cloneId,source:'scene-building-remainders',filter:['all',['==',['get','__group'],key],...(base?[convertFilter(base)]:[])]};delete spec['source-layer'];if(!map.getLayer(cloneId))map.addLayer(spec as LayerSpecification,l.id);else{for(const [k,v] of Object.entries(spec.paint||{}))map.setPaintProperty(cloneId,k as any,v);map.setLayoutProperty(cloneId,'visibility',map.getLayoutProperty(l.id,'visibility')||'visible');}}
 (map.getSource('scene-building-remainders') as GeoJSONSource).setData({type:'FeatureCollection',features:remainder});const volume=layers().some(l=>l.type==='fill-extrusion'&&map.getLayoutProperty(l.id,'visibility')!=='none'),visible=layers().some(l=>map.getLayoutProperty(l.id,'visibility')!=='none'),factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1;map.setLayoutProperty('scene-building-volume','visibility',volume?'visible':'none');map.setLayoutProperty('scene-rubble','visibility',visible?'visible':'none');(map.getSource('scene-rubble') as GeoJSONSource).setData({type:'FeatureCollection',features:state().filter(b=>b.destroyed).flatMap(rubbleFeatures)});for(const id of ['scene-building-ground','scene-building-edge'])map.setLayoutProperty(id,'visibility',visible?'visible':'none');
 (map.getSource('scene-buildings') as GeoJSONSource).setData({type:'FeatureCollection',features:state().flatMap(b=>(b.parts||[{geometry:b.geometry,height:b.height}]).map((part,i)=>({type:'Feature',id:b.parts?`${b.id}:${i}`:b.id,properties:{editId:b.id,color:b.destroyed?(b.destroyedColor||'#34302d'):b.color,height:b.destroyed?Math.min(1.4,part.height*.06):part.height*factor,destroyed:b.destroyed},geometry:part.geometry})))});viewport.dispatchEvent(new Event('buildings-updated'));}
 function focus(id?:string){selected=id;select(id);render();}
 panel.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;if(button.id==='pick-building'||button.id==='pick-single-building'){const nextSingle=button.id==='pick-single-building';picking=!(picking&&single===nextSingle);single=nextSingle;clearHover();map.getCanvas().style.cursor=picking?'crosshair':'';render();return;}if(button.dataset.building){focus(button.dataset.building);return;}const b=state().find(b=>b.id===selected);if(!b)return;if(button.id==='building-center'){map.once('moveend',()=>event(b.id,'centered'));map.easeTo({center:buildingCenter(b)});}if(button.id==='building-destroy'&&!b.destroyed){b.destroyed=true;paint();event(b.id,'destroyed');}if(button.id==='building-restore'){b.destroyed=false;event(b.id,'restored');}if(button.id==='building-forget'){state().splice(state().indexOf(b),1);focus(undefined);}paint();render();changed();});
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement,b=state().find(b=>b.id===selected);if(!b)return;if(el.id==='building-name')b.name=el.value.slice(0,80);if(el.id==='building-color')b.color=el.value;if(el.id==='building-destroyed-color')b.destroyedColor=el.value;if(el.id==='building-point')b.point=el.value||undefined;paint();changed();});
 map.on('click',e=>{if(!picking)return;handled.add(e.originalEvent);const hit=pick(e.point);if(!hit)return;let b=hit.edit;if(!b){if(state().length>=100)return;const parts=hit.parts;const geometry:Polygon|MultiPolygon=parts.length===1?parts[0].geometry:{type:'MultiPolygon',coordinates:parts.map(p=>p.geometry.coordinates)};b={id:crypto.randomUUID(),source:hit.source,sourceLayer:hit.sourceLayer,geometry,parts,name:`${single?'Bâtiment':'Bloc'} ${state().length+1}`,color:'#edc25d',destroyedColor:'#34302d',height:Math.max(...parts.map(p=>p.height)),effect:'none',destroyed:false};state().push(b);}focus(b.id);event(b.id,'click');picking=false;clearHover();map.getCanvas().style.cursor='';paint();render();changed();});
 map.on('sourcedata',e=>{if(e.sourceId&&!e.sourceId.startsWith('scene-')&&e.sourceDataType==='content')poolCache.clear();if(!e.sourceId||e.sourceId.startsWith('scene-')||e.sourceDataType!=='content'||!state().some(b=>b.source===e.sourceId))return;clearTimeout(repaintTimer);repaintTimer=setTimeout(paint,150);});
 function targets():JuiceTarget[]{return state().map(b=>{if(!anchors.has(b.id))anchors.set(b.id,document.createElement('span'));return {key:`building:${b.id}`,type:'building',name:b.name,position:()=>buildingCenter(b),element:()=>anchors.get(b.id)!,footprint:()=>b.geometry,apply:(amount:number,color:string)=>{if(!map.getSource('scene-buildings'))return;const ids=b.parts?b.parts.map((_,i)=>`${b.id}:${i}`):[b.id];if(amount<=0){for(const id of ids)map.removeFeatureState({source:'scene-buildings',id},'juiceColor');return;}const base=b.destroyed?(b.destroyedColor||'#34302d'):b.color,blend=(i:number)=>Math.round(parseInt(base.slice(i,i+2),16)*(1-amount)+parseInt(color.slice(i,i+2),16)*amount).toString(16).padStart(2,'0');for(const id of ids)map.setFeatureState({source:'scene-buildings',id},{juiceColor:`#${blend(1)}${blend(3)}${blend(5)}`});}};});}
 paint();render();return {targets,paint,refresh(){selected=undefined;picking=false;clearHover();poolCache.clear();sourceShapes.clear();paint();render();},pointsChanged:render,focusPoint(id?:string){select(state().find(b=>b.point===id)?.id);},picking:()=>picking,handled:(event:Event)=>handled.has(event)};
}
