import {heroResources,resourceSegmentBackground} from './hero-resource-style';
import {heroAsset,heroRoster} from './hero-roster';
import {icon} from './icons';
export type HeroPreview={id:string;hero:string;hp:number;mental:number;energy:number;task:string;detail:string;idleLabel:string;selected:boolean};
export function createHeroDock(viewport:HTMLElement,heroes:()=>HeroPreview[],open:(id:string)=>void,center:(id:string)=>void){
 const bar=document.createElement('nav');bar.id='hero-dock';bar.setAttribute('aria-label','Équipe sur le terrain');viewport.append(bar);let ids='';
 function refresh(){const list=heroes();bar.hidden=!list.length;const key=list.map(a=>a.id).join('|');if(key!==ids){ids=key;bar.replaceChildren();for(const a of list){const card=document.createElement('article');card.className='hero-preview';card.dataset.preview=a.id;const button=document.createElement('button');button.className='hero-preview-open';button.setAttribute('aria-label',`Ouvrir la fiche de ${heroRoster.find(h=>h.id===a.hero)!.name}`);button.innerHTML=`<img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span class="preview-info"><span data-task></span><small data-detail></small><small class="preview-idle" data-idle-label></small><span class="preview-resources">${Object.entries(heroResources).map(([k,r])=>`<span class="preview-meter ${k}" style="--resource:${r.color}"><span>${icon(r.icon)}<span>${r.label}</span><b data-value="${k}"></b></span><span class="preview-track" data-meter="${k}" role="meter" aria-label="${r.label}" aria-valuemin="0" aria-valuemax="${r.max}">${k==='energy'?'<i></i>':Array.from({length:r.max},()=>'<i></i>').join('')}</span></span>`).join('')}</span></span>`;button.onclick=()=>open(a.id);const target=document.createElement('button');target.className='hero-preview-center';target.dataset.centerHero=a.id;target.setAttribute('aria-label',`Centrer sur ${heroRoster.find(h=>h.id===a.hero)!.name}`);target.innerHTML=icon('target');target.onclick=()=>center(a.id);card.append(button,target);bar.append(card);}}
 for(const a of list){const card=bar.querySelector<HTMLElement>(`[data-preview="${a.id}"]`)!;card.classList.toggle('selected',a.selected);card.querySelector<HTMLButtonElement>('.hero-preview-open')!.title=`${heroRoster.find(h=>h.id===a.hero)!.name} · ${a.task}\n${a.detail}\nHP ${a.hp}/8 · Mental ${a.mental}/10 · Énergie ${Math.round(a.energy)} %\nIdle · ${a.idleLabel}`;card.querySelector('[data-task]')!.innerHTML=`${icon(a.task==='Surveillance'?'eye':a.task==='Au QG'?'home':a.task.includes('déplacement')||a.task==='Retour au QG'?'route':'check')}<b>${a.task}</b>`;card.querySelector('[data-idle-label]')!.textContent=`Idle · ${a.idleLabel}`;card.querySelector('[data-detail]')!.textContent=a.detail;for(const k of ['hp','mental','energy'] as const){const track=card.querySelector<HTMLElement>(`[data-meter=${k}]`)!;track.setAttribute('aria-valuenow',String(a[k]));track.querySelectorAll<HTMLElement>('i').forEach((el,i)=>{if(k==='energy')el.style.width=`${a[k]}%`;else {el.classList.toggle('filled',i<Math.floor(a[k]));el.style.background=resourceSegmentBackground(a[k],i);}});card.querySelector(`[data-value=${k}]`)!.textContent=String(Math.round(a[k]*10)/10);}}
 }return {refresh};
}
