import {placeMapPopover} from './map-popover';
import {cutBuildings} from './map-building-cut';
import {MercatorCoordinate,Marker} from 'maplibre-gl';
import {buildingOutline} from './map-building-outline';
import {connectedBuildingBlock,type BuildingPart} from './map-building-block';
import {convertFilter} from '@maplibre/maplibre-gl-style-spec';
import type {Map as MapLibreMap,GeoJSONSource,FilterSpecification,LayerSpecification} from 'maplibre-gl';
import type {Feature,Polygon,MultiPolygon} from 'geojson';
import {buildingCenter,buildingParts,pickBuildingPart,type BuildingEdit} from './map-building-state';
import {rubbleFeatures} from './map-rubble';
import {icon} from './icons';
import type {JuiceTarget} from './map-juice';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createBuildings(map:MapLibreMap,viewport:HTMLElement,parent:HTMLElement,state:()=>BuildingEdit[],points:()=>{id:string;name:string}[],changed:()=>void,event:(id:string,event:string)=>void=()=>{},select:(id?:string)=>void=()=>{},defaults=()=>({fillColor:'#34434b',color:'#edc25d',showFill:false,showOutline:true})){
 let picking=false,single=false,selected:string|undefined;const handled=new WeakSet<Event>(),original=new Map<string,FilterSpecification|undefined>(),anchors=new Map<string,HTMLElement>();let repaintTimer:ReturnType<typeof setTimeout>|undefined;
 const layerOpacity=new Map<string,unknown>();
 const cutCache=new Map<string,Polygon|MultiPolygon>();let cutRevision='';const dataCache=new Map<string,string>();
 function updateSource(id:string,data:any){const signature=JSON.stringify(data);if(dataCache.get(id)===signature)return;dataCache.set(id,signature);(map.getSource(id) as GeoJSONSource).setData(data);}
 const labels=new Map<string,Marker>();
 const sourceShapes=new Map<string,Map<string,Feature>>();
 const buildingLayerIds=map.getStyle().layers.filter(l=>!l.id.startsWith('scene-')&&((('source-layer'in l)&&l['source-layer']==='building')||/building/i.test(l.id))&&['fill','fill-extrusion','line'].includes(l.type)).map(l=>l.id);
 const layers=()=>buildingLayerIds.flatMap(id=>{const l=map.getLayer(id);return l?[l.serialize() as LayerSpecification]:[];});
 for(const l of layers())original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);
 const panel=document.createElement('details');panel.id='building-tools';panel.open=true;panel.innerHTML='<summary>Bâtiments interactifs</summary><div class="fields"><div class="pair"><button id="pick-building">Choisir un bloc</button><button id="pick-single-building">Choisir un bâtiment unique</button></div><div id="building-list"></div><div id="building-editor"></div><p class="hint">Effets : onglet Juice → Bâtiments. Détruire déclenche « destroyed ».</p></div>';parent.append(panel);const editor=document.createElement('section');editor.id='building-editor';editor.hidden=true;editor.className='map-building-window';viewport.append(editor);panel.querySelector('#building-editor')!.remove();const d=defaults();panel.querySelector('.fields')!.insertAdjacentHTML('afterbegin',`<details><summary>Style par défaut des bâtiments sélectionnés</summary><label class="color-row">Remplissage<input type="color" data-building-default="fillColor" value="${d.fillColor}"></label><label class="color-row">Contour<input type="color" data-building-default="color" value="${d.color}"></label><label class="check"><input type="checkbox" data-building-default="showFill" ${d.showFill?'checked':''}>Afficher le remplissage</label><label class="check"><input type="checkbox" data-building-default="showOutline" ${d.showOutline?'checked':''}>Afficher le contour</label></details>`);panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement,key=el.dataset.buildingDefault;if(key){Object.assign(defaults(),{[key]:el.type==='checkbox'?el.checked:el.value});changed();}});
 map.addSource('scene-buildings',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addSource('scene-building-remainders',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 const color:any=['coalesce',['feature-state','juiceColor'],['get','color']];
 map.addLayer({id:'scene-building-ground',type:'fill',source:'scene-buildings',paint:{'fill-color':color,'fill-opacity':['case',['get','destroyed'],1,['get','showFill'],1,0]}});
 map.addLayer({id:'scene-building-volume',type:'fill-extrusion',source:'scene-buildings',filter:['all',['==',['get','destroyed'],false],['==',['get','showFill'],true]],paint:{'fill-extrusion-color':color,'fill-extrusion-height':['get','height'],'fill-extrusion-opacity':1}});
 map.addLayer({id:'scene-building-edge',type:'line',source:'scene-buildings',paint:{'line-color':['get','outlineColor'],'line-width':2,'line-opacity':.85}});
 for(const id of ['scene-building-outline','scene-hover-outline']){map.addSource(id,{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id,type:'fill-extrusion',source:id,paint:{'fill-extrusion-color':color,'fill-extrusion-height':['get','height'],'fill-extrusion-base':['get','base'],'fill-extrusion-opacity':1}});}
 map.addSource('scene-block-hover',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-block-hover-volume',type:'fill',source:'scene-block-hover',paint:{'fill-color':'#78dcde','fill-opacity':.08}});
 map.addSource('scene-rubble',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-rubble',type:'fill',source:'scene-rubble',paint:{'fill-color':['get','color'],'fill-opacity':1}});
 map.addLayer({id:'scene-block-hover-edge',type:'line',source:'scene-block-hover',paint:{'line-color':'#b8ffff','line-width':2.5}});
 let hoverParts:BuildingPart[]=[],hoverStamp=0,poolCache=new Map<string,BuildingPart[]>();
 const clearHover=()=>{hoverParts=[];(map.getSource('scene-hover-outline') as GeoJSONSource).setData({type:'FeatureCollection',features:[]});(map.getSource('scene-block-hover') as GeoJSONSource).setData({type:'FeatureCollection',features:[]});};
 function pick(point:{x:number;y:number}){
  const feature=map.queryRenderedFeatures([point.x,point.y],{layers:[...layers().map(l=>l.id),...layers().map(l=>`scene-building-copy-${l.id}`),'scene-building-volume','scene-building-ground'].filter(id=>!!map.getLayer(id))}).filter(f=>['Polygon','MultiPolygon'].includes(f.geometry.type)&&!( !f.source.startsWith('scene-')&&state().some(b=>(b.destroyed||b.showFill)&&b.source===f.source&&b.sourceLayer===f.sourceLayer))).sort((a,b)=>Number(b.layer.type==='fill-extrusion')-Number(a.layer.type==='fill-extrusion'))[0];if(!feature)return;
  if(feature.source==='scene-buildings'){const edit=state().find(b=>b.id===String(feature.properties.editId||feature.id));if(edit)return {edit,parts:edit.parts||buildingParts(edit.geometry).map(coordinates=>({geometry:{type:'Polygon' as const,coordinates},height:edit.height})),source:edit.source,sourceLayer:edit.sourceLayer};return;}
  if(!feature.source.startsWith('scene-')){const key=`${feature.source}:${feature.sourceLayer||''}`;if(!sourceShapes.has(key))sourceShapes.set(key,new Map());sourceShapes.get(key)!.set(JSON.stringify(feature.geometry),{type:'Feature',id:feature.id,properties:feature.properties,geometry:feature.geometry});}
  const copy=feature.source==='scene-building-remainders',origin=copy?layers().find(l=>`scene-building-copy-${l.id}`===feature.layer.id):feature.layer;if(!origin||!('source'in origin))return;
  const height=Math.max(0,Math.min(1000,Number(feature.properties.render_height??feature.properties.height??8)||8)),factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1,lat=map.unproject([point.x,point.y]).lat,lift=feature.layer.type==='fill-extrusion'?height*factor*Math.sin(map.getPitch()*Math.PI/180)/(156543.03*Math.cos(lat*Math.PI/180)/2**map.getZoom()):0,geometry=pickBuildingPart(feature.geometry as Polygon|MultiPolygon,[point.x,point.y],p=>{const q=map.project(p as [number,number]);return [q.x,q.y];},lift,p=>{const transform=map._camera.transform as unknown as {coordinatePoint:(c:MercatorCoordinate,h:number)=>{x:number;y:number}};const q=transform.coordinatePoint(MercatorCoordinate.fromLngLat(p as [number,number]),feature.layer.type==='fill-extrusion'?height*factor:0);return [q.x,q.y];}),source=origin.source,sourceLayer='source-layer'in origin?origin['source-layer']:undefined,key=`${source}:${sourceLayer||''}`;
  let pool=poolCache.get(key);if(!pool){pool=[];for(const f of map.queryRenderedFeatures({layers:layers().filter(l=>'source'in l&&l.source===source&&('source-layer'in l?l['source-layer']:undefined)===sourceLayer).map(l=>l.id)})){if(!['Polygon','MultiPolygon'].includes(f.geometry.type))continue;const h=Math.max(0,Math.min(1000,Number(f.properties?.render_height??f.properties?.height??8)||8));for(const coordinates of buildingParts(f.geometry as Polygon|MultiPolygon))pool.push({geometry:{type:'Polygon',coordinates},height:h});}poolCache.set(key,pool);}
  return {parts:single?[{geometry,height}]:connectedBuildingBlock({geometry,height},pool),source,sourceLayer};
 }
 map.on('mousemove',e=>{if(!picking||performance.now()-hoverStamp<80)return;hoverStamp=performance.now();const hit=pick(e.point);hoverParts=hit?.parts||[];const factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1;(map.getSource('scene-block-hover') as GeoJSONSource).setData({type:'FeatureCollection',features:hoverParts.map(part=>({type:'Feature',properties:{height:part.height*factor+.3},geometry:part.geometry}))});const volume=layers().some(l=>l.type==='fill-extrusion'&&map.getLayoutProperty(l.id,'visibility')!=='none');map.setLayoutProperty('scene-hover-outline','visibility',volume?'visible':'none');map.setLayoutProperty('scene-block-hover-edge','visibility',volume?'none':'visible');map.setLayoutProperty('scene-block-hover-volume','visibility',volume?'none':'visible');(map.getSource('scene-hover-outline') as GeoJSONSource).setData({type:'FeatureCollection',features:hoverParts.flatMap((part,i)=>buildingOutline(part.geometry,part.height*factor,'#b8ffff',`hover:${i}`))});map.getCanvas().style.cursor=hit?'pointer':'crosshair';});
 map.getCanvas().addEventListener('mouseleave',clearHover);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&picking){picking=false;clearHover();map.getCanvas().style.cursor='';render();}});
 function render(){panel.querySelector('#pick-building')!.setAttribute('aria-pressed',String(picking&&!single));panel.querySelector('#pick-single-building')!.setAttribute('aria-pressed',String(picking&&single));panel.querySelector('#building-list')!.innerHTML=state().map(b=>`<button class="building-row" data-building="${esc(b.id)}">${icon(b.destroyed?'x':'target')}${esc(b.name)}${b.destroyed?' · détruit':''}</button>`).join('');const b=state().find(b=>b.id===selected);editor.hidden=!b;if(!b)return;editor.innerHTML=`<div class="selection-head"><b>${esc(b.name)}</b><button id="building-close" aria-label="Fermer la fiche">${icon('x')}</button></div><label>Nom<input id="building-name" maxlength="80" value="${esc(b.name)}"></label><label class="check"><input id="building-show-fill" type="checkbox" ${b.showFill?'checked':''}>Afficher le remplissage</label><label class="color-row">Remplissage<input id="building-fill-color" type="color" value="${b.fillColor||'#34434b'}"></label><label class="check"><input id="building-show-outline" type="checkbox" ${b.showOutline!==false?'checked':''}>Afficher le contour</label><label class="color-row">Contour<input id="building-color" type="color" value="${b.color}"></label><label class="color-row">Couleur détruite<input id="building-destroyed-color" type="color" value="${b.destroyedColor||'#34302d'}"></label><label>Point associé<select id="building-point"><option value="">Aucun</option>${points().map(p=>`<option value="${esc(p.id)}" ${b.point===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><div class="pair"><button id="building-center">${icon('target')}Centrer</button><button id="building-destroy" ${b.destroyed?'disabled':''}>${icon('bolt')}Détruire</button></div><button id="building-restore" ${b.destroyed?'':'disabled'}>Restaurer le bâtiment</button><button id="building-forget">Retirer la personnalisation</button>`;placeMapPopover(map,editor,buildingCenter(b));}
 function paint(){const revision=JSON.stringify(state().filter(b=>b.destroyed||b.showFill).map(b=>[b.source,b.sourceLayer,b.geometry]));if(revision!==cutRevision){cutCache.clear();cutRevision=revision;}const remainder:Feature<Polygon|MultiPolygon>[]=[],groups=new Map<string,{features:Feature<Polygon|MultiPolygon>[]}>();for(const l of layers()){if(!('source'in l))continue;if(!original.has(l.id))original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);const sourceLayer='source-layer'in l?l['source-layer']:undefined,key=`${l.source}:${sourceLayer||''}`,edits=state().filter(b=>(b.destroyed||b.showFill)&&b.source===l.source&&b.sourceLayer===sourceLayer);let group=groups.get(key);if(!group){group={features:[]};groups.set(key,group);if(edits.length){const seen=new Set<string>();let fs:Feature[]=[];try{let cache=sourceShapes.get(key);if(!cache){cache=new Map();sourceShapes.set(key,cache);}cache.clear();for(const f of map.queryRenderedFeatures({layers:layers().filter(v=>'source'in v&&v.source===l.source&&('source-layer'in v?v['source-layer']:undefined)===sourceLayer).map(v=>v.id)})){if(['Polygon','MultiPolygon'].includes(f.geometry.type))cache.set(JSON.stringify(f.geometry),{type:'Feature',id:f.id,properties:f.properties,geometry:f.geometry});}fs=[...cache.values()];}catch{}for(const f of fs){if(!['Polygon','MultiPolygon'].includes(f.geometry.type))continue;const signature=JSON.stringify(f.geometry);if(seen.has(signature))continue;seen.add(signature);const cacheKey=key+signature;let cut=cutCache.get(cacheKey);if(!cut){cut=cutBuildings(f.geometry as Polygon|MultiPolygon,edits.map(b=>b.geometry));if(cutCache.size>=512)cutCache.delete(cutCache.keys().next().value!);cutCache.set(cacheKey,cut);}const kept=buildingParts(cut);if(kept.length)group.features.push({type:'Feature',properties:{...f.properties,__group:key},geometry:{type:'MultiPolygon',coordinates:kept}});}}remainder.push(...group.features);}
 const base=original.get(l.id);map.setFilter(l.id,base);const opacityKey=l.type==='fill-extrusion'?'fill-extrusion-opacity':l.type==='fill'?'fill-opacity':'line-opacity',currentOpacity=map.getPaintProperty(l.id,opacityKey as any);if(!layerOpacity.has(l.id)||currentOpacity!==0)layerOpacity.set(l.id,currentOpacity??1);map.setPaintProperty(l.id,opacityKey as any,edits.length?0:layerOpacity.get(l.id));
 const cloneId=`scene-building-copy-${l.id}`,spec:any={...structuredClone(l),id:cloneId,source:'scene-building-remainders',filter:['all',['==',['get','__group'],key],...(base?[convertFilter(base)]:[])]};delete spec['source-layer'];spec.paint={...spec.paint,[opacityKey]:layerOpacity.get(l.id)};if(!map.getLayer(cloneId))map.addLayer(spec as LayerSpecification,l.id);else{for(const [k,v] of Object.entries(spec.paint||{}))map.setPaintProperty(cloneId,k as any,v);map.setLayoutProperty(cloneId,'visibility',map.getLayoutProperty(l.id,'visibility')||'visible');}}
 updateSource('scene-building-remainders',{type:'FeatureCollection',features:remainder});const volume=layers().some(l=>l.type==='fill-extrusion'&&map.getLayoutProperty(l.id,'visibility')!=='none'),visible=layers().some(l=>map.getLayoutProperty(l.id,'visibility')!=='none'),factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1;map.setLayoutProperty('scene-building-volume','visibility',volume?'visible':'none');map.setLayoutProperty('scene-building-outline','visibility',volume?'visible':'none');updateSource('scene-building-outline',{type:'FeatureCollection',features:state().filter(b=>!b.destroyed&&b.showOutline!==false).flatMap(b=>(b.parts||[{geometry:b.geometry,height:b.height}]).flatMap(part=>buildingOutline(part.geometry,part.height*factor,b.color,b.id)))});map.setLayoutProperty('scene-rubble','visibility',visible?'visible':'none');updateSource('scene-rubble',{type:'FeatureCollection',features:state().filter(b=>b.destroyed).flatMap(rubbleFeatures)});for(const id of ['scene-building-ground','scene-building-edge'])map.setLayoutProperty(id,'visibility',visible?'visible':'none');
 updateSource('scene-buildings',{type:'FeatureCollection',features:state().flatMap(b=>(b.parts||[{geometry:b.geometry,height:b.height}]).map((part,i)=>({type:'Feature',id:b.parts?`${b.id}:${i}`:b.id,properties:{editId:b.id,outlineColor:b.color,showOutline:b.showOutline!==false,showFill:!!b.showFill,color:b.destroyed?(b.destroyedColor||'#34302d'):(b.fillColor||'#34434b'),height:b.destroyed?0:part.height*factor,destroyed:b.destroyed},geometry:part.geometry})))});map.setFilter('scene-building-edge',['all',['==',['get','showOutline'],true],...(volume?[['==',['get','destroyed'],true]]:[])] as unknown as FilterSpecification);syncLabels();viewport.dispatchEvent(new Event('buildings-updated'));}
 function focus(id?:string){selected=id;select(id);render();}
 const handleClick=(e:Event)=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;if(button.id==='pick-building'||button.id==='pick-single-building'){const nextSingle=button.id==='pick-single-building';picking=!(picking&&single===nextSingle);single=nextSingle;clearHover();map.getCanvas().style.cursor=picking?'crosshair':'';render();return;}if(button.dataset.building){focus(button.dataset.building);return;}const b=state().find(b=>b.id===selected);if(!b)return;if(button.id==='building-close'){focus(undefined);return;}if(button.id==='building-center'){map.once('moveend',()=>event(b.id,'centered'));map.easeTo({center:buildingCenter(b)});}if(button.id==='building-destroy'&&!b.destroyed){b.destroyed=true;paint();event(b.id,'destroyed');}if(button.id==='building-restore'){b.destroyed=false;event(b.id,'restored');}if(button.id==='building-forget'){state().splice(state().indexOf(b),1);focus(undefined);}paint();render();changed();};panel.addEventListener('click',handleClick);editor.addEventListener('click',handleClick);
 editor.addEventListener('input',e=>{const el=e.target as HTMLInputElement,b=state().find(b=>b.id===selected);if(!b)return;if(el.id==='building-name')b.name=el.value.slice(0,80);if(el.id==='building-show-fill')b.showFill=el.checked;if(el.id==='building-show-outline')b.showOutline=el.checked;if(el.id==='building-fill-color')b.fillColor=el.value;if(el.id==='building-color')b.color=el.value;if(el.id==='building-destroyed-color')b.destroyedColor=el.value;if(el.id==='building-point')b.point=el.value||undefined;paint();changed();});
 map.on('click',e=>{if(!picking){const f=map.queryRenderedFeatures(e.point,{layers:['scene-building-ground','scene-building-volume','scene-building-outline']})[0];let id=f&&(f.properties.editId||String(f.id));if(!id){const hit=pick(e.point);id=hit?.edit?.id||state().find(b=>hit?.parts.some(part=>buildingParts(b.geometry).some(r=>JSON.stringify(r)===JSON.stringify(part.geometry.coordinates))))?.id;}if(id&&state().some(b=>b.id===id)){handled.add(e.originalEvent);focus(id);event(id,'click');}return;}handled.add(e.originalEvent);const hit=pick(e.point);if(!hit)return;let b=hit.edit;if(!b){if(state().length>=100)return;const parts=hit.parts;const geometry:Polygon|MultiPolygon=parts.length===1?parts[0].geometry:{type:'MultiPolygon',coordinates:parts.map(p=>p.geometry.coordinates)};b={id:crypto.randomUUID(),source:hit.source,sourceLayer:hit.sourceLayer,geometry,parts,name:`${single?'Bâtiment':'Bloc'} ${state().length+1}`,...defaults(),destroyedColor:'#34302d',height:Math.max(...parts.map(p=>p.height)),effect:'none',destroyed:false};state().push(b);}focus(b.id);event(b.id,'click');picking=false;clearHover();map.getCanvas().style.cursor='';paint();render();changed();});
 const schedulePaint=()=>{clearTimeout(repaintTimer);if(!map.isMoving())repaintTimer=setTimeout(()=>{if(!map.isMoving())paint();},180);};map.on('movestart',()=>clearTimeout(repaintTimer));map.on('moveend',()=>{if(state().some(b=>b.destroyed||b.showFill))schedulePaint();});
 map.on('sourcedata',e=>{if(e.sourceId&&!e.sourceId.startsWith('scene-')&&e.sourceDataType==='content')poolCache.clear();if(!e.sourceId||e.sourceId.startsWith('scene-')||e.sourceDataType!=='content'||!state().some(b=>b.source===e.sourceId))return;schedulePaint();});
 function targets():JuiceTarget[]{return state().map(b=>{if(!anchors.has(b.id))anchors.set(b.id,document.createElement('span'));return {key:`building:${b.id}`,type:'building',states:()=>b.destroyed?['is_destroyed']:[],name:b.name,position:()=>buildingCenter(b),element:()=>labels.get(b.id)?.getElement()||anchors.get(b.id)!,footprint:()=>b.geometry,apply:(amount:number,color:string)=>{if(!map.getSource('scene-buildings'))return;const ids=b.parts?b.parts.map((_,i)=>`${b.id}:${i}`):[b.id];if(amount<=0){map.removeFeatureState({source:'scene-building-outline',id:b.id},'juiceColor');for(const id of ids)map.removeFeatureState({source:'scene-buildings',id},'juiceColor');return;}const base=b.destroyed?(b.destroyedColor||'#34302d'):b.color,blend=(i:number)=>Math.round(parseInt(base.slice(i,i+2),16)*(1-amount)+parseInt(color.slice(i,i+2),16)*amount).toString(16).padStart(2,'0');map.setFeatureState({source:'scene-building-outline',id:b.id},{juiceColor:`#${blend(1)}${blend(3)}${blend(5)}`});for(const id of ids)map.setFeatureState({source:'scene-buildings',id},{juiceColor:`#${blend(1)}${blend(3)}${blend(5)}`});}};});}
 function syncLabels(){for(const [id,m] of labels)if(!state().some(b=>b.id===id)){m.remove();labels.delete(id);}for(const b of state()){let m=labels.get(b.id);if(!m){const el=document.createElement('button');el.className='building-map-label';el.dataset.buildingId=b.id;el.addEventListener('click',e=>{e.stopPropagation();focus(b.id);event(b.id,'click');});m=new Marker({element:el,anchor:'bottom',offset:[0,-10]}).setLngLat(buildingCenter(b)).addTo(map);labels.set(b.id,m);}m.setLngLat(buildingCenter(b));m.getElement().textContent=b.name;m.getElement().style.setProperty('--building-color',b.color);m.getElement().classList.toggle('destroyed',b.destroyed);}}
 paint();render();return {targets,paint,refresh(){for(const input of panel.querySelectorAll<HTMLInputElement>('[data-building-default]')){const value=defaults()[input.dataset.buildingDefault as keyof ReturnType<typeof defaults>];if(typeof value==='boolean')input.checked=value;else input.value=value;}selected=undefined;picking=false;clearHover();poolCache.clear();sourceShapes.clear();paint();render();},pointsChanged:render,focusPoint(id?:string){select(state().find(b=>b.point===id)?.id);},picking:()=>picking,handled:(event:Event)=>handled.has(event)};
}
