import type {BuildingPart} from './map-building-block';
import type {Polygon,MultiPolygon} from 'geojson';
export type BuildingEdit={id:string;source:string;sourceLayer?:string;featureId?:string|number;geometry:Polygon|MultiPolygon;parts?:BuildingPart[];name:string;color:string;destroyedColor?:string;effect:'none'|'pulse';point?:string;height:number;destroyed:boolean};
export function readBuildings(value:unknown):BuildingEdit[]{if(value===undefined)return [];if(!Array.isArray(value)||value.length>100)throw Error('Bâtiments invalides');const ids=new Set<string>();for(const b of value){if(!b||typeof b.id!=='string'||b.id.length>100||ids.has(b.id)||typeof b.source!=='string'||b.source.length>200||(b.sourceLayer!==undefined&&typeof b.sourceLayer!=='string')||(b.featureId!==undefined&&!['string','number'].includes(typeof b.featureId))||typeof b.name!=='string'||b.name.length>80||!/^#[0-9a-f]{6}$/i.test(b.color)||!['none','pulse'].includes(b.effect)||typeof b.destroyed!=='boolean'||!Number.isFinite(b.height)||b.height<0||b.height>1000||(b.point!==undefined&&(typeof b.point!=='string'||b.point.length>80)))throw Error('Bâtiment invalide');if(b.destroyedColor!==undefined&&!/^#[0-9a-f]{6}$/i.test(b.destroyedColor))throw Error('Couleur détruite invalide');ids.add(b.id);if(!b.geometry||!['Polygon','MultiPolygon'].includes(b.geometry.type))throw Error('Géométrie invalide');const polygons=b.geometry.type==='Polygon'?[b.geometry.coordinates]:b.geometry.coordinates;if(!Array.isArray(polygons)||!polygons.length)throw Error('Géométrie invalide');let count=0;for(const rings of polygons){if(!Array.isArray(rings)||!rings.length)throw Error('Contour invalide');for(const ring of rings){if(!Array.isArray(ring)||ring.length<4)throw Error('Contour invalide');for(const p of ring){count++;if(!Array.isArray(p)||p.length<2||!Number.isFinite(p[0])||!Number.isFinite(p[1])||Math.abs(p[0])>180||Math.abs(p[1])>85)throw Error('Coordonnées invalides');}if(ring[0][0]!==ring.at(-1)[0]||ring[0][1]!==ring.at(-1)[1])throw Error('Contour ouvert');}}if(b.parts&&(!Array.isArray(b.parts)||b.parts.length>300||b.parts.length!==polygons.length||b.parts.some((part:BuildingPart)=>!Number.isFinite(part.height)||part.height<0||part.height>1000||part.geometry?.type!=='Polygon'||!polygons.some((r:unknown)=>JSON.stringify(r)===JSON.stringify(part.geometry.coordinates)))))throw Error('Bloc invalide');if(count>50000)throw Error('Bâtiment trop détaillé');}return structuredClone(value);}
export function buildingCenter(b:BuildingEdit):[number,number]{const points=buildingParts(b.geometry).flatMap(r=>r[0].slice(0,-1));return points.reduce<[number,number]>((sum,p)=>[sum[0]+p[0]/points.length,sum[1]+p[1]/points.length],[0,0]);}
/** Geometry fallback for tiles without feature IDs; expand by centimetres to include boundary vertices. */
export function buildingSelector(b:BuildingEdit):any{const g=structuredClone(b.geometry),polys=buildingParts(g);for(const rings of polys){const ring=rings[0],c=ring.slice(0,-1).reduce((a,p)=>[a[0]+p[0]/(ring.length-1),a[1]+p[1]/(ring.length-1)],[0,0]);const sx=111320*Math.cos(c[1]*Math.PI/180);for(const r of rings)for(const p of r){const dx=(p[0]-c[0])*sx,dy=(p[1]-c[1])*111320,d=Math.hypot(dx,dy)||1;p[0]+=dx/d*.75/sx;p[1]+=dy/d*.75/111320;}}return ['within',g];}
export function polygonContains(p:[number,number],rings:number[][][]){const inside=(ring:number[][])=>{let hit=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;};return inside(rings[0])&&!rings.slice(1).some(inside);}
export function buildingParts(g:Polygon|MultiPolygon){return g.type==='Polygon'?[g.coordinates]:g.coordinates;}
export function pickBuildingPart(g:Polygon|MultiPolygon,p:[number,number],project:(p:number[])=>[number,number],lift=0,projectRoof?:(p:number[])=>[number,number]):Polygon{let best=buildingParts(g)[0],score=Infinity;for(const rings of buildingParts(g)){const ground=rings.map(r=>r.map(project)),roof=projectRoof?rings.map(r=>r.map(projectRoof)):ground.map(r=>r.map(q=>[q[0],q[1]-lift]));let hit=polygonContains(p,ground)||polygonContains(p,roof);for(let i=1;i<ground[0].length&&!hit;i++)hit=polygonContains(p,[[ground[0][i-1],ground[0][i],roof[0][i],roof[0][i-1],ground[0][i-1]]]);const c=roof[0].reduce((a,q)=>[a[0]+q[0]/roof[0].length,a[1]+q[1]/roof[0].length],[0,0]),d=Math.hypot(c[0]-p[0],c[1]-p[1])+(hit?0:1e6);if(d<score){score=d;best=rings;}}return {type:'Polygon',coordinates:structuredClone(best)};}
