import type {Map as MapLibreMap,GeoJSONSource} from 'maplibre-gl';
import {createRoadRouter,roadDistance,type RoadCoord} from './map-roads';
import {defaultRouteStyle,type RouteStyle} from './map-route-style';
export type Journey={path:RoadCoord[];next:number;destination:string;targetPoint?:string;totalDistance?:number;loopStart?:number;loopActive?:boolean};
export type Traveller={id:string;position:RoadCoord;journey?:Journey;color?:string;speed?:number;kind?:string};
/** Advance an existing path only: no routing, timers or allocations at a loop boundary. */
export function advanceJourney(a:Traveller,distance:number){const j=a.journey;if(!j)return {arrived:false,entered:false};let entered=false;
 while(distance>0&&j.next<j.path.length){const to=j.path[j.next],length=roadDistance(a.position,to);if(length<=distance+.001){a.position=[...to];distance-=length;j.next++;if(j.loopStart!==undefined&&!j.loopActive&&j.next>j.loopStart){j.loopActive=true;entered=true;}if(j.next>=j.path.length&&j.loopStart!==undefined)j.next=j.loopStart+1;}else{const t=distance/length;a.position=[a.position[0]+(to[0]-a.position[0])*t,a.position[1]+(to[1]-a.position[1])*t];distance=0;}}
 return {arrived:j.next>=j.path.length,entered};
}
export function journeyProgress(a:Traveller,multiplier:number){const j=a.journey;if(!j||j.loopActive)return {seconds:0,progress:1};const end=j.loopStart??(j.path.length-1);let remaining=roadDistance(a.position,j.path[j.next]);for(let k=j.next+1;k<=end;k++)remaining+=roadDistance(j.path[k-1],j.path[k]);j.totalDistance??=j.path.slice(1,end+1).reduce((sum,p,i)=>sum+roadDistance(j.path[i],p),0);return {seconds:remaining/((a.speed??(a.kind?30:18))/3.6*multiplier),progress:Math.max(0,Math.min(1,1-remaining/(j.totalDistance||1)))};}
export function createTravel(map:MapLibreMap,actors:()=>Traveller[],speed:()=>number,changed:()=>void,arrived:(id:string,targetPoint?:string)=>void,status:(text:string)=>void,positioned:(id:string,position:RoadCoord)=>void,style:()=>RouteStyle=()=>defaultRouteStyle,progressed:(id:string,seconds:number,progress:number)=>void=()=>{}){
 const roads=createRoadRouter(map);let last=0,saved=0,rendered=0,telemetry=0;
 map.addSource('scene-routes',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-route-shadow',type:'line',source:'scene-routes',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#09121b','line-width':7,'line-opacity':.65}});
 map.addLayer({id:'scene-route-line',type:'line',source:'scene-routes',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':['get','color'],'line-width':3,'line-dasharray':[2,1.3]}});
 function draw(){(map.getSource('scene-routes') as GeoJSONSource)?.setData({type:'FeatureCollection',features:actors().filter(a=>a.journey&&!a.journey.loopActive).map(a=>({type:'Feature',properties:{id:a.id,color:style().useActorColor?(a.color||style().color):style().color},geometry:{type:'LineString',coordinates:[a.position,...a.journey!.path.slice(a.journey!.next,a.journey!.loopStart===undefined?undefined:a.journey!.loopStart+1)]}}))});}
 function restyle(){const s=style();map.setPaintProperty('scene-route-line','line-width',s.width);map.setPaintProperty('scene-route-line','line-opacity',s.opacity);map.setPaintProperty('scene-route-line','line-dasharray',s.pattern==='solid'?[1,0]:s.pattern==='dotted'?[.2,1.6]:[2,1.3]);map.setPaintProperty('scene-route-shadow','line-width',s.width+4);map.setPaintProperty('scene-route-shadow','line-opacity',s.shadow?.65:0);draw();}
 function stop(id:string){const a=actors().find(a=>a.id===id);if(a)delete a.journey;draw();}
 function send(id:string,target:RoadCoord,label='Destination',ring?:RoadCoord[],targetPoint?:string){const a=actors().find(a=>a.id===id);if(!a)return false;const path=roads.get().route(a.position,target,!!a.kind,ring);if(path.length<2){stop(id);status('Aucun trajet routier accessible dans les rues chargées. Dézoome pour charger le secteur ou choisis une destination plus proche.');changed();return false;}return follow(id,path,label,targetPoint);}
 function follow(id:string,path:RoadCoord[],label:string,targetPoint?:string,loopStart?:number){const a=actors().find(a=>a.id===id);if(!a||path.length<2)return false;a.position=[...path[0]];a.journey={path,next:1,destination:label,targetPoint,loopStart,loopActive:loopStart===0,totalDistance:path.slice(1,loopStart===undefined?undefined:loopStart+1).reduce((sum,p,i)=>sum+roadDistance(path[i],p),0)};positioned(id,a.position);draw();changed();status(`Trajet vers ${label} · suit les rues.`);return true;}
 function tick(now:number){const dt=document.hidden?0:Math.min(.1,(now-(last||now))/1000);last=now;let moving=false,visibleMoving=false;const done:{id:string;point?:string}[]=[];for(const a of actors()){const j=a.journey;if(!j)continue;moving=true;visibleMoving ||= !j.loopActive;const step=advanceJourney(a,(a.speed??(a.kind?30:18))/3.6*speed()*dt);positioned(a.id,a.position);if(step.entered)done.push({id:a.id});if(step.arrived){delete a.journey;done.push({id:a.id,point:j.targetPoint});}else if(!j.loopActive&&now-telemetry>100){const p=journeyProgress(a,speed());progressed(a.id,p.seconds,p.progress);}}
  if(moving&&now-telemetry>100)telemetry=now;
  if(visibleMoving&&now-rendered>150){draw();if(style().flow&&!matchMedia('(prefers-reduced-motion:reduce)').matches)map.setPaintProperty('scene-route-line','line-opacity',style().opacity*(.75+.25*Math.sin(now/350)));rendered=now;}
  if(moving&&now-saved>1000){changed();saved=now;}for(const d of done){draw();arrived(d.id,d.point);changed();}requestAnimationFrame(tick);
 }
 requestAnimationFrame(tick);restyle();return {send,follow,stop,draw,restyle,network:()=>roads.get()};
}
