import {convertFilter} from '@maplibre/maplibre-gl-style-spec';
import type {Map as MapLibreMap,GeoJSONSource,FilterSpecification} from 'maplibre-gl';
import type {Polygon,MultiPolygon} from 'geojson';
import {buildingCenter,buildingSelector,type BuildingEdit} from './map-building-state';
import {icon} from './icons';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createBuildings(map:MapLibreMap,viewport:HTMLElement,parent:HTMLElement,state:()=>BuildingEdit[],points:()=>{id:string;name:string}[],changed:()=>void){
 let picking=false,selected:string|undefined,linked:string|undefined;const handled=new WeakSet<Event>(),original=new Map<string,FilterSpecification|undefined>();
 const layers=()=>map.getStyle().layers.filter(l=>!l.id.startsWith('scene-')&&((('source-layer'in l)&&l['source-layer']==='building')||/building/i.test(l.id))&&['fill','fill-extrusion','line'].includes(l.type));
 for(const l of layers())original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);
 const panel=document.createElement('details');panel.id='building-tools';panel.open=true;panel.innerHTML='<summary>Bâtiments interactifs</summary><div class="fields"><button id="pick-building">Choisir un bâtiment sur la carte</button><div id="building-list"></div><div id="building-editor"></div><p class="hint">Sélectionne une façade ou un toit. La destruction est locale à cet atelier; Restaurer le fait réapparaître.</p></div>';parent.append(panel);
 map.addSource('scene-buildings',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'scene-building-ground',type:'fill',source:'scene-buildings',paint:{'fill-color':['case',['get','destroyed'],'#151921',['boolean',['feature-state','pulse'],false],'#fff0b6',['get','color']],'fill-opacity':.8}});
 map.addLayer({id:'scene-building-volume',type:'fill-extrusion',source:'scene-buildings',paint:{'fill-extrusion-color':['case',['boolean',['feature-state','pulse'],false],'#fff0b6',['get','color']],'fill-extrusion-height':['case',['get','destroyed'],0,['get','height']],'fill-extrusion-opacity':.95}});
 map.addLayer({id:'scene-building-edge',type:'line',source:'scene-buildings',paint:{'line-color':['get','color'],'line-width':2,'line-opacity':.85}});
 function render(){panel.querySelector('#pick-building')!.setAttribute('aria-pressed',String(picking));panel.querySelector('#building-list')!.innerHTML=state().map(b=>`<button class="building-row" data-building="${esc(b.id)}">${icon(b.destroyed?'x':'target')}${esc(b.name)}${b.destroyed?' · détruit':''}</button>`).join('');const b=state().find(b=>b.id===selected),editor=panel.querySelector<HTMLElement>('#building-editor')!;editor.hidden=!b;if(!b)return;editor.innerHTML=`<label>Nom<input id="building-name" maxlength="80" value="${esc(b.name)}"></label><label class="color-row">Couleur<input id="building-color" type="color" value="${b.color}"></label><label>Effet<select id="building-effect"><option value="none">Aucun</option><option value="pulse" ${b.effect==='pulse'?'selected':''}>Pulsation lumineuse</option></select></label><label>Point associé<select id="building-point"><option value="">Aucun</option>${points().map(p=>`<option value="${esc(p.id)}" ${b.point===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><div class="pair"><button id="building-center">${icon('target')}Centrer</button><button id="building-destroy" ${b.destroyed?'disabled':''}>${icon('bolt')}Détruire</button></div><button id="building-restore" ${b.destroyed?'':'disabled'}>Restaurer le bâtiment</button><button id="building-forget">Retirer la personnalisation</button>`;}
 function paint(){for(const l of layers()){if(!original.has(l.id))original.set(l.id,('filter'in l?l.filter:undefined) as FilterSpecification|undefined);const edits=state().filter(b=>('source'in l)&&b.source===l.source&&b.sourceLayer===(('source-layer'in l)?l['source-layer']:undefined));const filters=edits.map(b=>['!',buildingSelector(b)]);const base=original.get(l.id);map.setFilter(l.id,(filters.length?['all',...(base?[convertFilter(base)]:[]),...filters]:base) as FilterSpecification|undefined);}
 const volume=layers().find(l=>l.type==='fill-extrusion'&&map.getLayoutProperty(l.id,'visibility')!=='none');const anyVisible=layers().some(l=>map.getLayoutProperty(l.id,'visibility')!=='none');const factor=Number((document.querySelector('[data-theme=height]') as HTMLInputElement)?.value)||1;map.setLayoutProperty('scene-building-volume','visibility',volume?'visible':'none');for(const id of ['scene-building-ground','scene-building-edge'])map.setLayoutProperty(id,'visibility',anyVisible?'visible':'none');
 (map.getSource('scene-buildings') as GeoJSONSource).setData({type:'FeatureCollection',features:state().map(b=>({type:'Feature',id:b.id,properties:{color:b.color,height:b.height*factor,destroyed:b.destroyed},geometry:b.geometry}))});viewport.dispatchEvent(new Event('buildings-updated'));}
 function explosion(b:BuildingEdit){const canvas=document.createElement('canvas');canvas.className='building-explosion';viewport.append(canvas);const dpr=Math.min(devicePixelRatio,2);canvas.width=viewport.clientWidth*dpr;canvas.height=viewport.clientHeight*dpr;const ctx=canvas.getContext('2d')!;ctx.scale(dpr,dpr);const start=performance.now(),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,particles=Array.from({length:reduced?12:70},()=>({angle:Math.random()*Math.PI*2,speed:40+Math.random()*160,size:2+Math.random()*7}));function tick(now:number){const t=(now-start)/1500;if(t>=1){canvas.remove();return;}const p=map.project(buildingCenter(b));ctx.clearRect(0,0,canvas.width,canvas.height);for(let i=0;i<9;i++){const a=i/9*Math.PI*2;ctx.globalAlpha=(1-t)*.7;ctx.fillStyle='#10131b';ctx.beginPath();ctx.arc(p.x+Math.cos(a)*t*55,p.y+Math.sin(a)*t*25-t*65,12+t*32,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=Math.max(0,1-t*2);const fire=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,12+t*85);fire.addColorStop(0,'#ffffff');fire.addColorStop(.3,'#fff3a1');fire.addColorStop(.6,'#ff981c');fire.addColorStop(1,'#ff321000');ctx.fillStyle=fire;ctx.beginPath();ctx.arc(p.x,p.y,12+t*85,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1-t;ctx.strokeStyle='#ffe2a0';ctx.lineWidth=3*(1-t);ctx.beginPath();ctx.ellipse(p.x,p.y,8+t*160,4+t*65,0,0,Math.PI*2);ctx.stroke();for(const q of particles){ctx.fillStyle=t<.35?'#fff3b0':'#bd501e';ctx.fillRect(p.x+Math.cos(q.angle)*q.speed*t,p.y+Math.sin(q.angle)*q.speed*t*.6-45*t+80*t*t,q.size*(1-t),q.size*(1-t));}requestAnimationFrame(tick);}requestAnimationFrame(tick);}
 panel.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;if(button.id==='pick-building'){picking=!picking;map.getCanvas().style.cursor=picking?'crosshair':'';render();return;}if(button.dataset.building){selected=button.dataset.building;render();return;}const b=state().find(b=>b.id===selected);if(!b)return;if(button.id==='building-center')map.easeTo({center:buildingCenter(b)});if(button.id==='building-destroy'){b.destroyed=true;explosion(b);}if(button.id==='building-restore')b.destroyed=false;if(button.id==='building-forget'){state().splice(state().indexOf(b),1);selected=undefined;}paint();render();changed();});
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement,b=state().find(b=>b.id===selected);if(!b)return;if(el.id==='building-name')b.name=el.value.slice(0,80);if(el.id==='building-color')b.color=el.value;if(el.id==='building-effect')b.effect=el.value as BuildingEdit['effect'];if(el.id==='building-point')b.point=el.value||undefined;paint();changed();});
 map.on('click',e=>{if(!picking)return;handled.add(e.originalEvent);const feature=map.queryRenderedFeatures(e.point,{layers:[...layers().map(l=>l.id),'scene-building-volume','scene-building-ground']}).find(f=>['Polygon','MultiPolygon'].includes(f.geometry.type));if(!feature)return;if(feature.source==='scene-buildings'){selected=String(feature.id);}else{let b=state().find(b=>b.source===feature.source&&b.sourceLayer===feature.sourceLayer&&b.featureId!==undefined&&b.featureId===feature.id);if(!b){if(state().length>=100)return;b={id:crypto.randomUUID(),source:feature.source,sourceLayer:feature.sourceLayer,featureId:feature.id,geometry:structuredClone(feature.geometry) as Polygon|MultiPolygon,name:`Bâtiment ${state().length+1}`,color:'#edc25d',height:Math.max(0,Math.min(1000,Number(feature.properties.render_height??feature.properties.height??8)||8)),effect:'none',destroyed:false};state().push(b);}selected=b.id;}picking=false;map.getCanvas().style.cursor='';paint();render();changed();});
 setInterval(()=>{if(document.hidden)return;const pulse=!matchMedia('(prefers-reduced-motion:reduce)').matches&&Math.sin(performance.now()/450)>0;for(const b of state())map.setFeatureState({source:'scene-buildings',id:b.id},{pulse:!b.destroyed&&(b.effect==='pulse'||!!(linked&&b.point===linked))&&pulse});},250);
 paint();render();return {paint,refresh(){selected=undefined;picking=false;paint();render();},pointsChanged:render,focusPoint(id?:string){linked=id;},picking:()=>picking,handled:(event:Event)=>handled.has(event)};
}
