import {validateEffectSettings,type EffectSettings} from './map-juice-options';
export const connectedJuiceEvents=['click','arrival','hit','centered','focus','destroyed','restored','idle','low_hp','low_mental','low_energy','moving'];
export const juiceEffects={pop:'Pop',squash:'Squash & stretch',flash:'Flash',shake:'Secousse écran',zoom:'Zoom caméra',travel:'Travelling',burst:'Explosion',rain:'Pluie de particules',temporaryZoom:'Temporary Zoom · aller-retour',objectShake:'Shake de l’objet',pinpoint:'Pinpoint · radar',pulse:'Pulse',glow:'Glow',vignette:'Vignette écran',smoke:'Fumée résiduelle',debris:'Débris'};
export const juiceTypes:Record<string,string>={point:'Tous les points',building:'Tous les bâtiments',hero:'Tous les héros',vehicle:'Tous les véhicules',zone:'Tous les secteurs','point:alert':'Toutes les alertes','point:hq':'Tous les QG','point:police':'Tous les points Police','point:clue':'Tous les indices','point:civil':'Tous les points Civils','point:hospital':'Tous les secours','point:watch':'Tous les points Surveillance',map:'Carte · caméra'};
export type ExplosionStyle={scale:number;smoke:number;rise:number;debris:number};
export const defaultExplosion=():ExplosionStyle=>({scale:1,smoke:.8,rise:1,debris:1});
export type JuiceConfig={effects:(keyof typeof juiceEffects)[];intensity:number;duration:number;color:string;explosion?:ExplosionStyle;effectSettings?:Record<string,EffectSettings>};
export type JuiceRule={id:string;type:string;event:string;config:JuiceConfig;target?:string};
export type JuiceState={version:2;focusVersion?:1;buildingVersion?:1;events:string[];rules:JuiceRule[]};
export const defaultJuiceConfig=():JuiceConfig=>({effects:['pop'],intensity:1,duration:650,color:'#78dcde'});
export const emptyJuice=():JuiceState=>({version:2,focusVersion:1,buildingVersion:1,events:['manual','solved',...connectedJuiceEvents],rules:[{id:'hero-focus',type:'hero',event:'focus',config:{effects:['pulse','glow'],intensity:1,duration:1800,color:'#78dcde'}},{id:'building-destroyed',type:'building',event:'destroyed',config:{effects:['burst','smoke','debris'],intensity:1,duration:1500,color:'#ff991c'}}]});
export function validateJuiceConfig(c:JuiceConfig){validateEffectSettings(c?.effectSettings);if(!c||!Array.isArray(c.effects)||c.effects.length>Object.keys(juiceEffects).length||c.effects.some(e=>!Object.hasOwn(juiceEffects,e))||!Number.isFinite(c.intensity)||c.intensity<.25||c.intensity>2||!Number.isFinite(c.duration)||c.duration<200||c.duration>2000||!/^#[a-f0-9]{6}$/i.test(c.color))throw Error('Effet Juice invalide');if(c.explosion){for(const [key,min,max] of [['scale',.5,2.5],['smoke',0,1],['rise',.2,3],['debris',0,2]] as const){const n=c.explosion[key];if(!Number.isFinite(n)||n<min||n>max)throw Error('Réglage explosion invalide');}}}
export function readJuice(value:unknown):JuiceState{
 if(value===undefined)return emptyJuice();if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Juice invalide');
 const s=value as JuiceState;if(s.version===2){if(!Array.isArray(s.events)||s.events.length>100||s.events.some(e=>typeof e!=='string'||!/^[a-z][a-z0-9_-]{0,39}$/.test(e))||new Set(s.events).size!==s.events.length||!Array.isArray(s.rules)||s.rules.length>500)throw Error('Déclencheurs invalides');const keys=new Set<string>();for(const r of s.rules){if(!r||typeof r.id!=='string'||r.id.length>100||!Object.hasOwn(juiceTypes,r.type)||!s.events.includes(r.event)||(r.target!==undefined&&(typeof r.target!=='string'||r.target.length>100)))throw Error('Règle Juice invalide');const key=JSON.stringify([r.type,r.event,r.target]);if(keys.has(key))throw Error('Règle Juice dupliquée');keys.add(key);validateJuiceConfig(r.config);}const copy=structuredClone(s);if(copy.focusVersion!==1){if(!copy.events.includes('centered'))copy.events.push('centered');if(!copy.events.includes('focus')){copy.events.push('focus');copy.rules.push(emptyJuice().rules.find(r=>r.id==='hero-focus')!);}copy.focusVersion=1;}for(const e of connectedJuiceEvents)if(!copy.events.includes(e))copy.events.push(e);if(copy.buildingVersion!==1){if(!copy.rules.some(r=>r.type==='building'&&r.event==='destroyed'))copy.rules.push(emptyJuice().rules.find(r=>r.id==='building-destroyed')!);copy.buildingVersion=1;}return copy;}
 const next=emptyJuice(),entries=Object.entries(value);if(entries.length>500)throw Error('Trop d’effets');for(const [target,c] of entries){if(target.length>100||!['manual','click','arrival'].includes(c?.trigger))throw Error('Ancien effet invalide');validateJuiceConfig(c);next.rules.push({id:`legacy-${next.rules.length}`,target,type:target.startsWith('hero:')?'hero':target.startsWith('vehicle:')?'vehicle':target.startsWith('zone:')?'zone':target==='map'?'map':'point:alert',event:c.trigger,config:{effects:[...c.effects],intensity:c.intensity,duration:c.duration,color:c.color}});}return next;
}
export function matchingJuice(state:JuiceState,type:string,event:string,target:string){const candidates=state.rules.filter(r=>r.config.effects.length>0&&r.event===event&&(r.target?r.target===target:r.type===type||(r.type==='point'&&type.startsWith('point:'))));const rank=(r:JuiceRule)=>r.target?3:r.type===type?2:1;const best=Math.max(0,...candidates.map(rank));return candidates.filter(r=>rank(r)===best);}


export const continuousJuiceEvents=['low_hp','low_mental','low_energy','moving','focus','idle'];
export const juiceEventLabels:Record<string,string>={low_hp:'Low HP · ≤ 25 %',low_mental:'Low Mental · ≤ 25 %',low_energy:'Low Energy · ≤ 25 %',moving:'Moving',idle:'idle · permanent'};
/** A single winner per visual channel, with target-specific rules breaking equal-priority ties. */
export function continuousJuice(state:JuiceState,type:string,key:string,events:string[]){const used=new Set<string>(),resolved:JuiceRule[]=[];for(const event of continuousJuiceEvents){if(!events.includes(event))continue;const rules=matchingJuice(state,type,event,key).sort((a,b)=>Number(!!b.target)-Number(!!a.target));for(const r of rules){const effects=r.config.effects.filter(effect=>{const channel=type==='building'&&['pulse','glow','flash'].includes(effect)?'material':['pulse','pop','squash'].includes(effect)?'scale':effect==='objectShake'?'translate':effect==='glow'?'shadow':effect==='flash'?'brightness':['zoom','travel','temporaryZoom'].includes(effect)?'camera':effect;if(used.has(channel))return false;used.add(channel);return true;});if(effects.length)resolved.push({...r,config:{...r.config,effects}});}}return resolved;}
