import type {Map as MapLibreMap,LngLat} from 'maplibre-gl';
export const screenDefaults={vignette:.3,vignetteColor:'#000000',vignetteSize:45,vignetteSoftness:100,vignetteRoundness:0,vignetteX:50,vignetteY:50,edgeFeedback:true,edgeColor:'#b5dfe8',edgeStrength:.24,edgeWidth:14,edgeDuration:650};
export type ScreenTheme=typeof screenDefaults;
export function readScreenTheme(value:unknown):ScreenTheme{const s={...screenDefaults,...Object.fromEntries(Object.entries((value||{}) as object).filter(([k])=>k in screenDefaults))};for(const k of ['vignetteColor','edgeColor'] as const)if(!/^#[0-9a-f]{6}$/i.test(s[k]))throw Error('Couleur d’écran invalide');if(typeof s.edgeFeedback!=='boolean')throw Error('Signal de limite invalide');for(const [k,min,max] of [['vignette',0,1],['vignetteSize',0,85],['vignetteSoftness',5,100],['vignetteRoundness',0,1],['vignetteX',0,100],['vignetteY',0,100],['edgeStrength',0,1],['edgeWidth',3,35],['edgeDuration',200,2000]] as const)if(!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw Error('Réglage d’écran invalide');return s;}
export function paintScreenTheme(viewport:HTMLElement,s:ScreenTheme){for(const [key,value] of Object.entries({size:s.vignetteSize,end:s.vignetteSize+(100-s.vignetteSize)*s.vignetteSoftness/100,rx:100-s.vignetteRoundness*30,x:s.vignetteX,y:s.vignetteY}))viewport.style.setProperty(`--vignette-${key}`,`${value}%`);const node=viewport.querySelector<HTMLElement>('.vignette')!;node.style.setProperty('--vignette-color',s.vignetteColor);node.style.opacity=String(s.vignette);}
/** Shared screen-space vignette. Shape follows DA; Juice owns its color, strength and timing. */
export function vignetteOverlay(viewport:HTMLElement,color:string){const node=document.createElement('div');node.className='juice-vignette';node.setAttribute('aria-hidden','true');node.style.setProperty('--vignette-color',color);viewport.append(node);return node;}
export function createBoundaryFeedback(map:MapLibreMap,viewport:HTMLElement,state:()=>ScreenTheme,constrain?:(center:LngLat,zoom:number)=>LngLat){
 const sides=['left','right','top','bottom','zoom'] as const;type Side=typeof sides[number];const nodes=new Map<Side,HTMLElement>(),last=new Map<Side,number>(),animations=new Map<Side,Animation>();let inputUntil=0,zoomIntent=0,pointer:{x:number;y:number}|undefined,touchDistance=0;
 for(const side of sides){const el=document.createElement('div');el.className=`map-boundary boundary-${side}`;el.dataset.boundary=side;el.setAttribute('aria-hidden','true');viewport.append(el);nodes.set(side,el);}
 function flash(side:Side){const s=state(),now=performance.now();if(!s.edgeFeedback||s.edgeStrength===0||now-(last.get(side)??-Infinity)<Math.max(180,s.edgeDuration*.6))return;last.set(side,now);const el=nodes.get(side)!;el.style.setProperty('--edge-color',s.edgeColor);el.style.setProperty('--edge-width',`${s.edgeWidth}%`);animations.get(side)?.cancel();const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;animations.set(side,el.animate([{opacity:0},{opacity:s.edgeStrength*(reduced?.5:1),offset:.22},{opacity:0}],{duration:reduced?Math.max(800,s.edgeDuration):s.edgeDuration,easing:'ease-out'}));}
 function zoomCheck(){if(performance.now()>inputUntil)return;if((zoomIntent<0&&map.getZoom()<=map.getMinZoom()+.015)||(zoomIntent>0&&map.getZoom()>=map.getMaxZoom()-.015))flash('zoom');}
 const canvas=map.getCanvas();canvas.addEventListener('wheel',e=>{if(!map.scrollZoom.isEnabled())return;zoomIntent=e.deltaY>0?-1:1;inputUntil=performance.now()+250;zoomCheck();},{passive:true});
 canvas.addEventListener('keydown',e=>{if(!map.keyboard.isEnabled()||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','-','_','=','+'].includes(e.key)){inputUntil=performance.now()+350;zoomIntent=['-','_'].includes(e.key)?-1:['=','+'].includes(e.key)?1:0;zoomCheck();if(constrain&&!e.shiftKey&&e.key.startsWith('Arrow')){const c=map.project(map.getCenter()),delta={ArrowLeft:[-100,0],ArrowRight:[100,0],ArrowUp:[0,-100],ArrowDown:[0,100]}[e.key]!;const wanted=map.unproject([c.x+delta[0],c.y+delta[1]]);blocked(wanted,constrain(wanted,map.getZoom()));}}});
 canvas.addEventListener('pointerdown',e=>{if(e.button===0)pointer={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{if(pointer&&(e.buttons===1||e.pointerType==='touch')&&map.dragPan.isEnabled()){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>2){inputUntil=performance.now()+200;zoomIntent=0;pointer={x:e.clientX,y:e.clientY};}}});window.addEventListener('pointerup',()=>{pointer=undefined;});window.addEventListener('pointercancel',()=>{pointer=undefined;});
 canvas.addEventListener('touchmove',e=>{if(e.touches.length!==2||!map.touchZoomRotate.isEnabled())return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(touchDistance){zoomIntent=Math.sign(d-touchDistance);inputUntil=performance.now()+250;zoomCheck();}touchDistance=d;},{passive:true});canvas.addEventListener('touchend',()=>{touchDistance=0;});
 map.on('zoom',zoomCheck);
 function blocked(wanted:LngLat,allowed:LngLat){if(performance.now()>inputUntil||!map.dragPan.isEnabled())return;const a=map.project(wanted),b=map.project(allowed),dx=a.x-b.x,dy=a.y-b.y;if(Math.abs(dx)>.35)flash(dx<0?'left':'right');if(Math.abs(dy)>.35)flash(dy<0?'top':'bottom');}
 return {blocked,preview(){for(const side of sides)flash(side);},clear(){inputUntil=0;animations.forEach(a=>a.cancel());last.clear();}};
}
