import {activityForOrder} from './hero-activities';
import {pencilRing} from './map-pencil';
import type {FeatureCollection} from 'geojson';
import {Marker,type Map as MapLibreMap,type GeoJSONSource} from 'maplibre-gl';
import {heroRoster,heroAsset} from './hero-roster';
import {icon} from './icons';
import './map-scene.css';
export type Coord=[number,number];
type Agent={id:string;hero:string;position:Coord;order:'ready'|'watch'|'patrol';zone?:string;hp:number;mental:number;energy:number};
type Vehicle={id:string;kind:'car'|'bike';position:Coord;heading:number};
type Zone={id:string;name:string;ring:Coord[];color:string;agent?:string;order:'watch'|'patrol'};
type Ambience={light:number;lightColor:string;azimuth:number;contrast:number;saturation:number;glow:number;pulse:boolean;shadows:boolean;zoneOpacity:number};
type Floating={open:boolean;agent?:string;x:number;y:number;width:number;height?:number};
export type Scene={ambience:Ambience;agents:Agent[];vehicles:Vehicle[];zones:Zone[];window:Floating;zoneColors?:{watch:string;patrol:string}};
const defaultAmbience:Ambience={light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12};
export const emptyScene=():Scene=>({ambience:{...defaultAmbience},agents:[],vehicles:[],zones:[],window:{open:false,x:.1,y:.12,width:360}});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function readScene(value:unknown):Scene {
 const d=emptyScene();if(value===undefined)return d;
 if(!value||typeof value!=='object')throw Error('Scène invalide');
 const s=value as Scene;
 const number=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
 const coord=(v:unknown)=>Array.isArray(v)&&v.length===2&&number(v[0],-180,180)&&number(v[1],-85,85);
 const id=(v:unknown)=>typeof v==='string'&&v.length>0&&v.length<=80;
 const color=(v:unknown)=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
 if(!s.ambience||!number(s.ambience.light,0,1)||!color(s.ambience.lightColor)||!number(s.ambience.azimuth,0,360)||!number(s.ambience.contrast,.7,1.6)||!number(s.ambience.saturation,0,1.8)||!number(s.ambience.glow,0,1)||typeof s.ambience.pulse!=='boolean'||typeof s.ambience.shadows!=='boolean'||!number(s.ambience.zoneOpacity,0,.5))throw Error('Ambiance invalide');
 if(!Array.isArray(s.agents)||s.agents.length>100||s.agents.some(a=>!id(a.id)||!heroRoster.some(h=>h.id===a.hero)||!coord(a.position)||!['ready','watch','patrol'].includes(a.order)||!number(a.hp,0,8)||!number(a.mental,0,10)||!number(a.energy,0,100)))throw Error('Agents invalides');
 if(!Array.isArray(s.vehicles)||s.vehicles.length>100||s.vehicles.some(v=>!id(v.id)||!['car','bike'].includes(v.kind)||!coord(v.position)||!number(v.heading,0,360)))throw Error('Véhicules invalides');
 if(!Array.isArray(s.zones)||s.zones.length>100||s.zones.some(z=>!id(z.id)||!id(z.name)||!color(z.color)||!['watch','patrol'].includes(z.order)||!Array.isArray(z.ring)||z.ring.length<4||z.ring.length>1500||!z.ring.every(coord)||z.ring[0][0]!==z.ring.at(-1)![0]||z.ring[0][1]!==z.ring.at(-1)![1]))throw Error('Zones invalides');
 if(new Set([...s.agents,...s.vehicles,...s.zones].map(o=>o.id)).size!==s.agents.length+s.vehicles.length+s.zones.length)throw Error('Identifiants dupliqués');
 if(s.zones.some(z=>z.agent!==undefined&&!s.agents.some(a=>a.id===z.agent))||s.agents.some(a=>a.zone!==undefined&&!s.zones.some(z=>z.id===a.zone)))throw Error('Affectation invalide');
 if(!s.window||typeof s.window.open!=='boolean'||!number(s.window.x,0,1)||!number(s.window.y,0,1)||!number(s.window.width,220,640)||(s.window.agent!==undefined&&!s.agents.some(a=>a.id===s.window.agent)))throw Error('Fenêtre invalide');
 if(s.window.height!==undefined&&!number(s.window.height,180,1200))throw Error('Hauteur invalide');
 if(s.zoneColors&&(!color(s.zoneColors.watch)||!color(s.zoneColors.patrol)))throw Error('Couleurs des secteurs invalides');
 return structuredClone(s);
}
const car=`<svg viewBox="0 0 48 78" aria-hidden="true"><rect x="8" y="5" width="32" height="68" rx="10" fill="#67899c" stroke="#c4e5ee" stroke-width="2"/><path d="M12 23h24l-3 12H15zM15 47h18l3 12H12z" fill="#142831" stroke="#8abacb"/><path d="M9 38h30M17 6v6m14-6v6M13 66h6m10 0h6" stroke="#eacb8e" stroke-width="3"/><path d="M6 20v13m36-13v13M6 49v13m36-13v13" stroke="#0b121b" stroke-width="4"/></svg>`;
export function createScene(map:MapLibreMap,initial:Scene,changed:()=>void,status:(s:string)=>void){
 let scene=structuredClone(initial),markers:Marker[]=[],zoneMarkers:Marker[]=[],drawing=false,stroke:Coord[]=[],screenStroke:Coord[]=[],selectedZone:string|undefined,selectedVehicle:string|undefined,suppressClick=false;
 scene.zoneColors??={watch:activityForOrder('watch').color,patrol:activityForOrder('patrol').color};
 const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const viewport=document.querySelector<HTMLElement>('.viewport')!;
 const tools=document.createElement('div');tools.id='scene-tools';tools.innerHTML=`<details open><summary>Héros & véhicules</summary><div class="fields"><label>Héros<select id="map-hero">${heroRoster.map(h=>`<option value="${h.id}" ${h.id==='beton'?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><div class="pair"><button id="add-agent">${icon('users')}Au centre</button><button id="place-agent">${icon('map-pin')}Placer</button></div><div id="agent-list"></div><label>Véhicule<select id="vehicle-kind"><option value="car">Voiture</option><option value="bike">Moto</option></select></label><div class="pair"><button id="add-vehicle">${icon('route')}Au centre</button><button id="place-vehicle">${icon('map-pin')}Placer</button></div><div id="vehicle-list"></div><div id="vehicle-editor" hidden></div><p class="hint">Glisse les tokens. Touche un héros pour ouvrir sa fiche.</p></div></details><details open><summary>Crayon & zones</summary><div class="fields"><button id="draw-zone" aria-pressed="false">${icon('tools')}Encercler un secteur</button><p class="hint">Trace un contour en gardant le bouton ou le doigt appuyé. Le trait se ferme quand tu relâches. Échap annule.</p><label>Nom de la prochaine zone<input id="zone-name" maxlength="80" placeholder="Secteur à surveiller"></label><label class="color-row">Surveillance<input id="zone-color" data-zone-color="watch" type="color" value="${scene.zoneColors.watch}"></label><label class="color-row">Patrouille<input id="patrol-color" data-zone-color="patrol" type="color" value="${scene.zoneColors.patrol}"></label><div id="zone-list"></div></div></details>`;
 const poiDetails=$('point-list').closest('details')!;poiDetails.before(tools);
 const ambiance=document.createElement('div');ambiance.id='ambience-controls';ambiance.innerHTML=`<h2>Ambiance & effets</h2><div class="presets"><button data-mood="neutral">Neutre</button><button data-mood="night">Nuit</button><button data-mood="warm">Chaud</button></div>${[['light','Éclairage des volumes',0,1,.05],['azimuth','Direction de la lumière',0,360,5],['contrast','Contraste',.7,1.6,.05],['saturation','Saturation',0,1.8,.05],['glow','Glow des points & tokens',0,1,.05],['zoneOpacity','Opacité des zones',0,.5,.01]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-effect-out="${key}"></output><input data-effect="${key}" type="range" min="${min}" max="${max}" step="${step}"></label>`).join('')}<label class="color-row">Teinte de la lumière<input data-effect="lightColor" type="color"></label><label class="check"><input data-effect="pulse" type="checkbox">Pulsation des alertes</label><label class="check"><input data-effect="shadows" type="checkbox">Ombre sous les tokens</label><p class="hint">Relief : utilise Bâtiments en volume et Hauteur 3D au-dessus.</p>`;
 $('visual-controls').after(ambiance);
 const zonePanel=document.createElement('section');zonePanel.id='zone-editor';zonePanel.role='dialog';zonePanel.setAttribute('aria-label','Secteur');zonePanel.hidden=true;viewport.append(zonePanel);
 const pencil=document.createElement('div');pencil.className='pencil-toolbar';pencil.innerHTML=`<button id="map-pencil" aria-label="Dessiner une zone" aria-pressed="false">${icon('tools')}Crayon</button><button id="cancel-pencil" hidden>${icon('x')}Annuler</button>`;viewport.append(pencil);
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('pencil-overlay');svg.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');svg.append(path);viewport.append(svg);
 const floating=document.createElement('section');floating.id='hero-window';floating.role='dialog';floating.setAttribute('aria-modal','false');floating.setAttribute('aria-label','Fiche du héros');floating.hidden=true;
 floating.innerHTML=`<div class="hero-window-canvas"><div class="hero-window-bar"><button id="hero-window-drag" aria-label="Déplacer la fiche"><span id="hero-window-title">Fiche du héros</span>${icon('arrows-move')}</button><button id="hero-window-smaller" aria-label="Rapetisser la fiche">−</button><button id="hero-window-larger" aria-label="Agrandir la fiche">+</button><button id="hero-move" aria-label="Déplacer le héros sur la carte">${icon('map-pin')}</button><button id="hero-window-close" aria-label="Fermer la fiche">${icon('x')}</button></div><iframe title="Fiche du Hero Gym" id="hero-frame"></iframe></div><button id="hero-window-resize" aria-label="Redimensionner la fiche">◢</button>`;viewport.append(floating);
 let mode:'agent'|'vehicle'|'move-agent'|'move-vehicle'|undefined,frameKey='',movingId:string|undefined;
 const moving=new Map<string,number>();
 function moveTo(id:string,position:Coord){const a=scene.agents.find(a=>a.id===id)||scene.vehicles.find(v=>v.id===id);if(!a)return;cancelAnimationFrame(moving.get(id)||0);const from=[...a.position] as Coord,start=performance.now();function tick(now:number){const t=Math.min(1,(now-start)/1800);a!.position=[from[0]+(position[0]-from[0])*t,from[1]+(position[1]-from[1])*t];const marker=markers.find(m=>m.getElement().dataset.actor===id);marker?.setLngLat(a!.position);if(t<1)moving.set(id,requestAnimationFrame(tick));else {moving.delete(id);changed();status('Destination atteinte.');}}moving.set(id,requestAnimationFrame(tick));}
 function chooseMove(id:string,vehicle=false){stopDrawing();movingId=id;mode=vehicle?'move-vehicle':'move-agent';scene.window.open=false;windowUI();$('workshop').classList.remove('open');status('Touche la destination sur la carte · déplacement de test en ligne droite.');}
 function syncEffects(){for(const input of ambiance.querySelectorAll<HTMLInputElement>('[data-effect]')){const key=input.dataset.effect as keyof Ambience;if(input.type==='checkbox')input.checked=scene.ambience[key] as boolean;else input.value=String(scene.ambience[key]);const out=ambiance.querySelector(`[data-effect-out="${key}"]`);if(out)out.textContent=String(scene.ambience[key]);}}
 function effects(){const a=scene.ambience;viewport.style.setProperty('--point-glow',`${Math.round(a.glow*32)}px`);viewport.style.setProperty('--glow-alpha',String(a.glow));viewport.classList.toggle('pulse-alerts',a.pulse);viewport.classList.toggle('token-shadows',a.shadows);$('map').style.filter=`contrast(${a.contrast}) saturate(${a.saturation})`;map.setLight({anchor:'map',color:a.lightColor,intensity:a.light,position:[1.5,a.azimuth,45]});if(map.getLayer('scene-zone-fill'))map.setPaintProperty('scene-zone-fill','fill-opacity',a.zoneOpacity);syncEffects();}
 function windowLayout(){
  const v=scene.window,w=Math.min(v.width,viewport.clientWidth-20),scale=w/520,height=Math.min(v.height??w*920/520,viewport.clientHeight-24);
  floating.querySelector<HTMLElement>('.hero-window-canvas')!.style.height=`${height/scale}px`;$<HTMLIFrameElement>('hero-frame').style.height=`${height/scale-48}px`;
  floating.style.width=`${w}px`;floating.style.height=`${height}px`;floating.style.left=`${Math.max(8,Math.min(v.x*viewport.clientWidth,viewport.clientWidth-w-8))}px`;floating.style.top=`${Math.max(8,Math.min(v.y*viewport.clientHeight,viewport.clientHeight-height-8))}px`;floating.querySelector<HTMLElement>('.hero-window-canvas')!.style.transform=`scale(${scale})`;
 }
 function windowUI(){const a=scene.agents.find(a=>a.id===scene.window.agent);floating.hidden=!scene.window.open||!a;windowLayout();if(!a){frameKey='';return;}const name=heroRoster.find(h=>h.id===a.hero)!.name;$('hero-window-title').textContent=name;floating.setAttribute('aria-label',`Fiche de ${name}`);if(frameKey!==a.id){frameKey=a.id;const p=new URLSearchParams({embed:'1',hero:a.hero,agent:a.id,hp:String(a.hp),mental:String(a.mental),energy:String(a.energy),order:a.order});$<HTMLIFrameElement>('hero-frame').src=`./hero-gym.html?${p}`;}}
 function openAgent(id:string){selectedZone=undefined;zoneEditor();scene.window={...scene.window,agent:id,open:true};windowUI();changed();}
 function token(position:Coord,el:HTMLElement,ground=false){const m=new Marker({element:el,draggable:!drawing,anchor:ground?'center':'bottom',pitchAlignment:ground?'map':'viewport',rotationAlignment:ground?'map':'viewport'}).setLngLat(position).addTo(map);markers.push(m);return m;}
 function renderActors(){markers.forEach(m=>m.remove());markers=[];
  for(const a of scene.agents){const h=heroRoster.find(h=>h.id===a.hero)!;const el=document.createElement('button');el.className='agent-token';el.setAttribute('aria-label',`Fiche de ${h.name}`);el.dataset.actor=a.id;el.style.setProperty('--point',activityForOrder(a.order).color);el.innerHTML=`<span class="token-ground"></span><span class="token-stem"></span><span class="token-portrait"><img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span class="token-order">${icon(activityForOrder(a.order).icon)}</span></span><span class="token-caption">${esc(h.name)}</span>`;el.onclick=e=>{e.stopPropagation();if(!drawing&&!suppressClick)openAgent(a.id);};const m=token(a.position,el);m.on('dragstart',()=>{suppressClick=true;cancelAnimationFrame(moving.get(a.id)||0);moving.delete(a.id);});m.on('dragend',()=>{const c=m.getLngLat();a.position=[c.lng,c.lat];setTimeout(()=>suppressClick=false,100);changed();});}
  for(const v of scene.vehicles){const el=document.createElement('button');el.className='vehicle-token';el.dataset.actor=v.id;el.setAttribute('aria-label',v.kind==='car'?'Voiture':'Moto');el.innerHTML=v.kind==='car'?car:icon('motorbike');el.onclick=e=>{e.stopPropagation();selectedVehicle=v.id;vehicleEditor();};const m=token(v.position,el,true);m.setRotation(v.heading);m.on('dragstart',()=>{cancelAnimationFrame(moving.get(v.id)||0);moving.delete(v.id);});m.on('dragend',()=>{const c=m.getLngLat();v.position=[c.lng,c.lat];changed();});}
  perspective();lists();
 }
 function perspective(){for(const el of viewport.querySelectorAll<HTMLElement>('.token-ground')){el.style.transform=`rotateX(${map.getPitch()}deg) rotateZ(${-map.getBearing()}deg)`;}}
 function lists(){
  $('agent-list').innerHTML=scene.agents.map(a=>{const h=heroRoster.find(h=>h.id===a.hero)!;return `<div class="scene-row"><button data-agent="${a.id}"><img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span>${esc(h.name)}<small>${a.order==='watch'?'Surveillance':a.order==='patrol'?'Patrouille':'Disponible'}</small></span></button><button data-move-agent="${a.id}" aria-label="Déplacer ${esc(h.name)}">${icon('map-pin')}</button><button data-remove-agent="${a.id}" aria-label="Retirer ${esc(h.name)}">${icon('x')}</button></div>`;}).join('');
  $('vehicle-list').innerHTML=scene.vehicles.map(v=>`<div class="scene-row"><button data-vehicle="${v.id}">${icon('route')}${v.kind==='car'?'Voiture':'Moto'}</button><button data-move-vehicle="${v.id}" aria-label="Déplacer le véhicule">${icon('map-pin')}</button><button data-remove-vehicle="${v.id}" aria-label="Retirer le véhicule">${icon('x')}</button></div>`).join('');
  $('zone-list').innerHTML=scene.zones.map(z=>`<div class="sector-row"><button class="zone-row" data-zone="${z.id}" style="--zone:${z.color}">${icon(activityForOrder(z.order).icon)}<span>${esc(z.name)}${zonePortrait(z)}<small>${z.order==='watch'?'Surveillance':'Patrouille'}</small></span></button><button data-center-zone="${z.id}" aria-label="Placer ${esc(z.name)} au centre">${icon('target')}</button></div>`).join('');
 }
 function vehicleEditor(){const v=scene.vehicles.find(v=>v.id===selectedVehicle),el=$('vehicle-editor');el.hidden=!v;if(v)el.innerHTML=`<label class="range">Orientation<output>${v.heading}°</output><input id="vehicle-heading" type="range" min="0" max="360" step="5" value="${v.heading}"></label>`;}
 function zonePortrait(z:Zone){const a=scene.agents.find(a=>a.id===z.agent);return a?`<img class="zone-portrait" src="${heroAsset(a.hero,'portrait','dossier')}" alt="${esc(heroRoster.find(h=>h.id===a.hero)!.name)}">`:'';}
 function zoneCenter(z:Zone):Coord{return z.ring.slice(0,-1).reduce((sum,p)=>[sum[0]+p[0]/(z.ring.length-1),sum[1]+p[1]/(z.ring.length-1)] as Coord,[0,0] as Coord);}
 function openZone(id:string){selectedZone=id;$('selection').hidden=true;zoneEditor();}
 function zoneEditor(){const z=scene.zones.find(z=>z.id===selectedZone),el=$('zone-editor');el.hidden=!z;if(!z)return;el.innerHTML=`<div class="selection-head"><b>${icon(activityForOrder(z.order).icon)} Secteur ${zonePortrait(z)}</b><button id="close-zone" aria-label="Fermer le secteur">${icon('x')}</button></div><label>Nom<input id="edit-zone-name" maxlength="80" value="${esc(z.name)}"></label><label>Assigner à<select id="zone-agent"><option value="">Personne</option>${scene.agents.map(a=>`<option value="${a.id}" ${a.id===z.agent?'selected':''}>${esc(heroRoster.find(h=>h.id===a.hero)!.name)}</option>`).join('')}</select></label><label>Ordre<select id="zone-order"><option value="watch" ${z.order==='watch'?'selected':''}>Surveiller cette zone</option><option value="patrol" ${z.order==='patrol'?'selected':''}>Patrouiller dans cette zone</option></select></label><button data-center-zone="${z.id}">${icon('target')}Placer au centre</button><button id="remove-zone" class="danger">${icon('x')}Supprimer la zone</button>`;}

 function assign(z:Zone){z.color=scene.zoneColors![z.order];for(const a of scene.agents)if(a.zone===z.id){delete a.zone;a.order='ready';}const a=scene.agents.find(a=>a.id===z.agent);if(a){for(const other of scene.zones)if(other.id!==z.id&&other.agent===a.id)delete other.agent;a.zone=z.id;a.order=z.order;}const visible=scene.agents.find(a=>a.id===scene.window.agent);if(visible)$<HTMLIFrameElement>('hero-frame').contentWindow?.postMessage({type:'map-hero-order',order:visible.order},location.origin);renderActors();renderZones();zoneEditor();changed();}
 function renderZones(){
  const data:FeatureCollection={type:'FeatureCollection',features:scene.zones.map(z=>({type:'Feature',properties:{id:z.id,color:z.color},geometry:{type:'Polygon',coordinates:[z.ring]}}))};
  (map.getSource('scene-zones') as GeoJSONSource)?.setData(data);zoneMarkers.forEach(m=>m.remove());zoneMarkers=[];
  for(const z of scene.zones){const center=zoneCenter(z);const el=document.createElement('button');el.className='zone-label';el.style.setProperty('--zone',z.color);el.innerHTML=`<span>${esc(z.name)}</span>${zonePortrait(z)}`;el.onclick=e=>{e.stopPropagation();openZone(z.id);};zoneMarkers.push(new Marker({element:el}).setLngLat(center).addTo(map));}lists();
 }
 function addAgent(position:Coord){if(scene.agents.length>=100)return;const hero=$<HTMLSelectElement>('map-hero').value;const a:Agent={id:crypto.randomUUID(),hero,position,order:'ready',hp:6,mental:8,energy:75};scene.agents.push(a);renderActors();zoneEditor();openAgent(a.id);status(`${heroRoster.find(h=>h.id===hero)!.name} placé. Glisse son token pour le déplacer.`);changed();}
 function addVehicle(position:Coord){if(scene.vehicles.length>=100)return;const v:Vehicle={id:crypto.randomUUID(),kind:$<HTMLSelectElement>('vehicle-kind').value as Vehicle['kind'],position,heading:0};scene.vehicles.push(v);selectedVehicle=v.id;renderActors();vehicleEditor();changed();}
 const center=():Coord=>{const c=map.getCenter();return [c.lng,c.lat];};
 function stopDrawing(){drawing=false;stroke=[];screenStroke=[];path.setAttribute('d','');svg.classList.remove('drawing');viewport.classList.remove('drawing-zone');map.dragPan.enable();map.touchZoomRotate.enable();if(map.getContainer().dataset.cameraLocked==='true')map.touchZoomRotate.disableRotation();map.scrollZoom.enable();markers.forEach(m=>m.setDraggable(true));$('draw-zone').setAttribute('aria-pressed','false');$('map-pencil').setAttribute('aria-pressed','false');$('cancel-pencil').hidden=true;}
 function startDrawing(){if(drawing){stopDrawing();return;}selectedZone=undefined;zoneEditor();$('selection').hidden=true;scene.window.open=false;windowUI();mode=undefined;drawing=true;svg.classList.add('drawing');viewport.classList.add('drawing-zone');map.dragPan.disable();map.touchZoomRotate.disable();map.scrollZoom.disable();markers.forEach(m=>m.setDraggable(false));$('draw-zone').setAttribute('aria-pressed','true');$('map-pencil').setAttribute('aria-pressed','true');$('cancel-pencil').hidden=false;status('Crayon actif · encercle un lieu. Échap pour annuler.');}
 function drawPoint(e:PointerEvent){const r=svg.getBoundingClientRect(),p:Coord=[e.clientX-r.left,e.clientY-r.top],last=screenStroke.at(-1);if(last&&Math.hypot(last[0]-p[0],last[1]-p[1])<4)return;if(stroke.length>=1499)return;const c=map.unproject(p);stroke.push([c.lng,c.lat]);screenStroke.push(p);path.setAttribute('d',screenStroke.map((p,i)=>`${i?'L':'M'}${p[0]} ${p[1]}`).join(' '));path.setAttribute('stroke',$<HTMLInputElement>('zone-color').value);}
 let activePointer:number|undefined;
 svg.addEventListener('pointerdown',e=>{if(!drawing||activePointer!==undefined||e.button!==0)return;e.preventDefault();activePointer=e.pointerId;svg.setPointerCapture(e.pointerId);stroke=[];screenStroke=[];drawPoint(e);});
 svg.addEventListener('pointermove',e=>{if(e.pointerId===activePointer)drawPoint(e);});
 svg.addEventListener('pointerup',e=>{if(e.pointerId!==activePointer)return;drawPoint(e);activePointer=undefined;svg.releasePointerCapture(e.pointerId);const area=Math.abs(screenStroke.reduce((sum,p,i)=>{const q=screenStroke[(i+1)%screenStroke.length];return sum+p[0]*q[1]-q[0]*p[1];},0))/2;
  if(stroke.length<4||area<100){stroke=[];screenStroke=[];path.setAttribute('d','');status('Trace un contour plus grand pour créer une zone.');return;}
  if(scene.zones.length>=100){stopDrawing();status('Limite de 100 zones atteinte.');return;}
  const clean=pencilRing(screenStroke);if(clean.length<4){stopDrawing();status('Contour trop petit. Recommence le secteur.');return;}
  const z:Zone={id:crypto.randomUUID(),name:$<HTMLInputElement>('zone-name').value.trim()||`Secteur ${scene.zones.length+1}`,ring:clean.map(p=>{const c=map.unproject(p);return [c.lng,c.lat] as Coord;}),color:scene.zoneColors!.watch,order:'watch'};scene.zones.push(z);selectedZone=z.id;suppressClick=true;setTimeout(()=>suppressClick=false,100);stopDrawing();renderZones();zoneEditor();changed();status(`${z.name} tracé · assigne un héros dans la fenêtre du secteur.`);
 });
 svg.addEventListener('pointercancel',()=>{activePointer=undefined;stopDrawing();});
 $('draw-zone').onclick=startDrawing;$('map-pencil').onclick=startDrawing;$('cancel-pencil').onclick=stopDrawing;
 $('add-agent').onclick=()=>addAgent(center());$('add-vehicle').onclick=()=>addVehicle(center());
 $('place-agent').onclick=()=>{stopDrawing();mode=mode==='agent'?undefined:'agent';status(mode?'Touche la carte pour placer le héros.':'Placement annulé.');};$('place-vehicle').onclick=()=>{stopDrawing();mode=mode==='vehicle'?undefined:'vehicle';status(mode?'Touche la carte pour placer le véhicule.':'Placement annulé.');};
 map.on('click',e=>{if(drawing||suppressClick)return;if(mode){const p:Coord=[e.lngLat.lng,e.lngLat.lat];if(mode==='move-agent'||mode==='move-vehicle'){if(movingId)moveTo(movingId,p);}else mode==='agent'?addAgent(p):addVehicle(p);mode=undefined;movingId=undefined;}});
 function sceneClick(e:Event){const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;
  if(b.dataset.agent)openAgent(b.dataset.agent);
  if(b.dataset.vehicle){selectedVehicle=b.dataset.vehicle;vehicleEditor();}
  if(b.dataset.zone)openZone(b.dataset.zone);
  if(b.dataset.centerZone){const z=scene.zones.find(z=>z.id===b.dataset.centerZone);if(z)map.easeTo({center:zoneCenter(z)});}
  if(b.id==='close-zone'){selectedZone=undefined;zoneEditor();}
  if(b.dataset.moveAgent)chooseMove(b.dataset.moveAgent);if(b.dataset.moveVehicle)chooseMove(b.dataset.moveVehicle,true);
  if(b.dataset.removeAgent){const id=b.dataset.removeAgent;cancelAnimationFrame(moving.get(id)||0);moving.delete(id);scene.agents=scene.agents.filter(a=>a.id!==id);for(const z of scene.zones)if(z.agent===id)delete z.agent;if(scene.window.agent===id){scene.window.open=false;delete scene.window.agent;}renderActors();renderZones();zoneEditor();windowUI();changed();}
  if(b.dataset.removeVehicle){cancelAnimationFrame(moving.get(b.dataset.removeVehicle)||0);moving.delete(b.dataset.removeVehicle);scene.vehicles=scene.vehicles.filter(v=>v.id!==b.dataset.removeVehicle);renderActors();vehicleEditor();changed();}
  if(b.id==='remove-zone'){const z=scene.zones.find(z=>z.id===selectedZone);if(!z)return;delete z.agent;assign(z);scene.zones=scene.zones.filter(z=>z.id!==selectedZone);selectedZone=undefined;renderZones();zoneEditor();changed();}
 }
 tools.addEventListener('click',sceneClick);zonePanel.addEventListener('click',sceneClick);
 tools.addEventListener('input',e=>{const colorInput=e.target as HTMLInputElement;const order=colorInput.dataset.zoneColor as 'watch'|'patrol'|undefined;if(order){scene.zoneColors![order]=colorInput.value;for(const z of scene.zones)if(z.order===order)z.color=colorInput.value;renderZones();zoneEditor();changed();return;}const input=e.target as HTMLInputElement,z=scene.zones.find(z=>z.id===selectedZone);if(input.id==='vehicle-heading'){const v=scene.vehicles.find(v=>v.id===selectedVehicle);if(v){v.heading=Number(input.value);renderActors();$('vehicle-editor').querySelector('output')!.textContent=`${v.heading}°`;changed();}}if(z&&input.id==='edit-zone-color'){z.color=input.value;renderZones();changed();}});
 zonePanel.addEventListener('change',e=>{const input=e.target as HTMLInputElement,z=scene.zones.find(z=>z.id===selectedZone);if(!z)return;if(input.id==='edit-zone-name'){z.name=input.value.trim()||z.name;renderZones();changed();}if(input.id==='zone-agent'){z.agent=input.value||undefined;assign(z);}if(input.id==='zone-order'){z.order=input.value as Zone['order'];assign(z);}});
 ambiance.addEventListener('input',e=>{const input=e.target as HTMLInputElement,key=input.dataset.effect as keyof Ambience;if(!key)return;(scene.ambience as unknown as Record<string,unknown>)[key]=input.type==='checkbox'?input.checked:input.type==='color'?input.value:Number(input.value);effects();changed();});
 ambiance.addEventListener('click',e=>{const mood=(e.target as HTMLElement).closest<HTMLElement>('[data-mood]')?.dataset.mood;if(!mood)return;scene.ambience={...scene.ambience,...defaultAmbience,...(mood==='night'?{light:.25,lightColor:'#a4bce8',azimuth:280,contrast:1.15,saturation:.85,glow:.7}:mood==='warm'?{light:.65,lightColor:'#ffe4bc',azimuth:120,contrast:1.05,saturation:1.15,glow:.3}:{})};effects();changed();});
 $('hero-move').onclick=()=>{if(scene.window.agent)chooseMove(scene.window.agent);};
 $('hero-window-close').onclick=()=>{scene.window.open=false;windowUI();changed();};$('hero-window-smaller').onclick=()=>{scene.window.width=Math.max(220,scene.window.width-40);windowLayout();changed();};$('hero-window-larger').onclick=()=>{scene.window.width=Math.min(640,scene.window.width+40);windowLayout();changed();};
 function manipulate(handle:HTMLElement,resize:boolean){let start:{pointer:number;x:number;y:number;left:number;top:number;width:number;height:number}|undefined;handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;handle.setPointerCapture(e.pointerId);start={pointer:e.pointerId,x:e.clientX,y:e.clientY,left:parseFloat(floating.style.left),top:parseFloat(floating.style.top),width:parseFloat(floating.style.width),height:parseFloat(floating.style.height)};e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!start||e.pointerId!==start.pointer)return;if(resize){scene.window.width=Math.max(220,Math.min(640,start.width+e.clientX-start.x));scene.window.height=Math.max(180,Math.min(1200,start.height+e.clientY-start.y));}else {const w=floating.offsetWidth,h=floating.offsetHeight;scene.window.x=Math.max(8,Math.min(viewport.clientWidth-w-8,start.left+e.clientX-start.x))/viewport.clientWidth;scene.window.y=Math.max(8,Math.min(viewport.clientHeight-h-8,start.top+e.clientY-start.y))/viewport.clientHeight;}windowLayout();});const end=(e:PointerEvent)=>{if(start&&e.pointerId===start.pointer){start=undefined;changed();}};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);}
 manipulate($('hero-window-drag'),false);manipulate($('hero-window-resize'),true);
 window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(drawing){activePointer=undefined;stopDrawing();}else if(scene.window.open){scene.window.open=false;windowUI();changed();}else {selectedZone=undefined;zoneEditor();}mode=undefined;}});
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$<HTMLIFrameElement>('hero-frame').contentWindow||e.data?.type!=='hero-map-state')return;const a=scene.agents.find(a=>a.id===e.data.agent);if(!a)return;for(const key of ['hp','mental','energy'] as const){const v=e.data[key],max=key==='hp'?8:key==='mental'?10:100;if(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max)a[key]=v;}if(['ready','watch','patrol'].includes(e.data.order)&&a.order!==e.data.order){a.order=e.data.order;const z=scene.zones.find(z=>z.id===a.zone);if(a.order==='ready'){if(z)delete z.agent;delete a.zone;}else if(z){z.order=a.order;z.color=scene.zoneColors![z.order];}renderActors();renderZones();zoneEditor();}changed();});
 new ResizeObserver(()=>windowLayout()).observe(viewport);map.on('move',perspective);
 map.addSource('scene-zones',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'scene-zone-fill',type:'fill',source:'scene-zones',layout:{visibility:'visible'},paint:{'fill-color':['get','color'],'fill-opacity':scene.ambience.zoneOpacity}});map.addLayer({id:'scene-zone-line',type:'line',source:'scene-zones',layout:{visibility:'visible','line-join':'round','line-cap':'round'},paint:{'line-color':['get','color'],'line-width':3,'line-opacity':.85}});
 map.on('click','scene-zone-fill',e=>{if(drawing||mode||suppressClick)return;const id=e.features?.[0]?.properties?.id;if(typeof id==='string'){openZone(id);}});
 effects();renderActors();renderZones();windowUI();
 return {snapshot:()=>structuredClone(scene),effects,active:()=>drawing||!!mode,cancelPlacement(){stopDrawing();mode=undefined;},replace(next:Scene){stopDrawing();mode=undefined;for(const id of moving.values())cancelAnimationFrame(id);moving.clear();scene=structuredClone(next);scene.zoneColors??={watch:activityForOrder('watch').color,patrol:activityForOrder('patrol').color};$<HTMLInputElement>('zone-color').value=scene.zoneColors.watch;$<HTMLInputElement>('patrol-color').value=scene.zoneColors.patrol;selectedZone=undefined;selectedVehicle=undefined;frameKey='';effects();renderActors();renderZones();zoneEditor();vehicleEditor();windowUI();}};
}
