import type {Map as MapLibreMap} from 'maplibre-gl';
import type {RoadCoord} from './map-roads';
import {icon} from './icons';
import {juiceEffects,juiceTypes,defaultJuiceConfig,matchingJuice,type JuiceConfig,type JuiceState} from './map-juice-state';
export {readJuice,type JuiceState} from './map-juice-state';
export type JuiceTarget={key:string;type:string;name:string;position:()=>RoadCoord;element:()=>HTMLElement|null};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createJuice(map:MapLibreMap,viewport:HTMLElement,targets:()=>JuiceTarget[],state:()=>JuiceState,changed:()=>void){
 let selectedType='hero',event='click',preview='all',active=false,animations:Animation[]=[],cameraEffect=false;
 const focusKeys=new Set<string>(),focusRuns=new Map<string,{signature:string;el:HTMLElement;animations:Animation[]}>();let temporaryCleanup:(()=>void)|undefined;
 const canvases=new Set<HTMLCanvasElement>(),rafs=new Set<number>();
 const tabs=document.createElement('div');tabs.className='workshop-tabs';tabs.innerHTML=`<button id="settings-tab" aria-pressed="true">${icon('tools')}Atelier</button><button id="juice-tab" aria-pressed="false">${icon('bolt')}Juice</button>`;document.querySelector('.aside-title')!.after(tabs);
 const panel=document.createElement('section');panel.id='juice-panel';panel.hidden=true;document.querySelector('#workshop')!.append(panel);
 const rule=()=>state().rules.find(r=>!r.target&&r.type===selectedType&&r.event===event);
 const config=()=>rule()?.config||defaultJuiceConfig();
 function save(c:JuiceConfig){let r=rule();if(!r){if(state().rules.length>=500)return;r={id:crypto.randomUUID(),type:selectedType,event,config:c};state().rules.push(r);}r.config=c;changed();refreshFocus();}
 function render(){if(!state().events.includes(event))event=state().events[0]||'manual';const c=config(),list=targets().filter(t=>t.type===selectedType);if(preview!=='all'&&!list.some(t=>t.key===preview))preview='all';panel.innerHTML=`<h2>Juice · règles</h2><label>Type d’élément<select id="juice-type">${Object.entries(juiceTypes).map(([key,name])=>`<option value="${key}" ${key===selectedType?'selected':''}>${name}</option>`).join('')}</select></label><label>Déclencheur<select id="juice-trigger">${state().events.map(e=>`<option ${e===event?'selected':''} value="${e}">${e}</option>`).join('')}</select></label><div class="pair"><input id="juice-new-event" maxlength="40" placeholder="ex. blessure" aria-label="Nouveau déclencheur"><button id="juice-add-event">${icon('check')}Créer</button></div><button id="juice-delete-event">Supprimer ce déclencheur…</button><div class="juice-effects">${Object.entries(juiceEffects).filter(([key])=>key!=='rain'||c.effects.includes('rain')).map(([key,label])=>`<label class="check"><input data-juice-effect="${key}" type="checkbox" ${c.effects.includes(key as keyof typeof juiceEffects)?'checked':''}>${label}</label>`).join('')}</div><label class="range">Intensité<output id="juice-intensity-out">${c.intensity}</output><input id="juice-intensity" type="range" min=".25" max="2" step=".25" value="${c.intensity}"></label><label class="range">Durée<output id="juice-duration-out">${c.duration} ms</output><input id="juice-duration" type="range" min="200" max="2000" step="50" value="${c.duration}"></label><label class="color-row">Couleur<input id="juice-color" type="color" value="${c.color}"></label><label>Tester sur<select id="juice-target"><option value="all">Tous les éléments de ce type</option>${list.map(t=>`<option value="${escape(t.key)}" ${t.key===preview?'selected':''}>${escape(t.name)}</option>`).join('')}</select></label><div class="pair"><button id="juice-test">${icon('player-play')}Tester</button><button id="juice-stop">${icon('x')}Arrêter</button></div><button id="juice-clear">Retirer cette règle</button><p class="hint">La règle s’applique à tout ce type, y compris les futurs éléments. Clique un élément sur la map pour le choisir comme cible d’essai.</p><p class="hint">click, arrival et centered sont automatiques; focus reste actif pendant la sélection. hit se déclenche quand les HP baissent. Les autres événements (solved, etc.) sont testables ici et prêts à être appelés par le jeu. La pluie d’ambiance est dans Direction artistique.</p><p class="hint">${state().rules.filter(r=>r.target).length} ancien(s) effet(s) individuel(s) conservé(s).</p><button id="juice-clear-legacy">Retirer les anciens effets individuels…</button><p id="juice-feedback" role="status"></p>`;}
 function stop(){temporaryCleanup?.();for(const r of focusRuns.values())r.animations.forEach(a=>a.cancel());focusRuns.clear();animations.forEach(a=>a.cancel());animations=[];for(const r of rafs)cancelAnimationFrame(r);rafs.clear();for(const c of canvases)c.remove();canvases.clear();if(cameraEffect){map.stop();cameraEffect=false;}}
 function temporary(target:JuiceTarget,c:JuiceConfig){
  if(temporaryCleanup)return;const before={center:map.getCenter(),zoom:map.getZoom(),bearing:map.getBearing(),pitch:map.getPitch()},reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
  const handlers=[map.dragPan,map.scrollZoom,map.boxZoom,map.dragRotate,map.keyboard,map.doubleClickZoom,map.touchZoomRotate,map.touchPitch],enabled=handlers.map(h=>h.isEnabled());handlers.forEach(h=>h.disable());
  let timer:ReturnType<typeof setTimeout>;const unlock=()=>{handlers.forEach((h,i)=>{if(enabled[i])h.enable();});if(map.getContainer().dataset.cameraLocked==='true')map.touchZoomRotate.disableRotation();};
  temporaryCleanup=()=>{clearTimeout(timer);map.stop();map.jumpTo(before);unlock();temporaryCleanup=undefined;};
  const transit=reduced?0:350;map.easeTo({center:target.position(),zoom:Math.min(map.getMaxZoom(),map.getZoom()+.7*c.intensity),duration:transit});
  timer=setTimeout(()=>{play(target,{...c,effects:c.effects.filter(e=>!['temporaryZoom','zoom','travel'].includes(e))});timer=setTimeout(()=>{map.easeTo({...before,duration:transit});timer=setTimeout(()=>{unlock();temporaryCleanup=undefined;},transit+30);},c.duration);},transit+30);
 }
 function refreshFocus(){
  for(const [key,run] of focusRuns){const t=targets().find(t=>t.key===key),sig=t?JSON.stringify(matchingJuice(state(),t.type,'focus',key)):'';if(!focusKeys.has(key)||t?.element()!==run.el||sig!==run.signature){run.animations.forEach(a=>a.cancel());focusRuns.delete(key);}}
  for(const key of focusKeys){if(focusRuns.has(key))continue;const t=targets().find(t=>t.key===key),root=t?.element();if(!t||!root)continue;const rules=matchingJuice(state(),t.type,'focus',key),el=root.querySelector<HTMLElement>('.token-portrait,.poi-symbol,img')||root,as:Animation[]=[],reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
   for(const r of rules){const c=r.config,opts={duration:Math.max(900,c.duration),iterations:Infinity,easing:'ease-in-out'};
    if(c.effects.includes('pulse')&&!reduced)as.push(el.animate([{scale:'1'},{scale:String(1+.1*c.intensity)},{scale:'1'}],opts));
    if(c.effects.includes('glow'))as.push((root.classList.contains('poi-resident')?root:el).animate([{boxShadow:`0 0 ${8*c.intensity}px ${c.color}`},{boxShadow:`0 0 ${reduced?8:22*c.intensity}px ${c.color}`},{boxShadow:`0 0 ${8*c.intensity}px ${c.color}`}],opts));
    const once=c.effects.filter(e=>!['pulse','glow'].includes(e));if(once.length)play(t,{...c,effects:once});
   }focusRuns.set(key,{signature:JSON.stringify(rules),el:root,animations:as});
  }
 }
 function play(target:JuiceTarget,c:JuiceConfig){if(c.effects.includes('temporaryZoom')){temporary(target,c);return;}animations=animations.filter(a=>a.playState==='running');const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,duration=reduced?Math.min(300,c.duration):c.duration,strength=reduced?.2:c.intensity,root=target.element(),el=root?.querySelector<HTMLElement>('.token-portrait,.poi-symbol,img')||root;
  const animate=(node:HTMLElement|undefined|null,frames:Keyframe[])=>{if(node)animations.push(node.animate(frames,{duration,easing:'ease-out'}));};
  if(c.effects.includes('pulse'))animate(el,[{scale:'1'},{scale:String(1+.15*strength),offset:.5},{scale:'1'}]);
  if(c.effects.includes('glow'))animate(el,[{boxShadow:`0 0 0px ${c.color}`},{boxShadow:`0 0 ${28*strength}px ${c.color}`,offset:.4},{boxShadow:`0 0 0px ${c.color}`}]);
  if(c.effects.includes('objectShake')&&!reduced)animate(el,[{translate:'0 0'},...Array.from({length:8},(_,i)=>({translate:`${(i%2?1:-1)*5*strength*(1-i/8)}px ${(i%3-1)*3*strength}px`})),{translate:'0 0'}]);
  if(c.effects.includes('pop')&&!c.effects.includes('squash'))animate(el,[{scale:'1'},{scale:String(1+.25*strength),offset:.35},{scale:'1'}]);
  if(c.effects.includes('squash'))animate(el,[{scale:'1 1'},{scale:`${1+.3*strength} ${1-.25*strength}`,offset:.25},{scale:`${1-.12*strength} ${1+.15*strength}`,offset:.6},{scale:'1 1'}]);
  if(c.effects.includes('flash'))animate(el,[{filter:'brightness(1)'},{filter:`brightness(${1+strength*1.8})`,offset:.2},{filter:'brightness(1)'}]);
  if(c.effects.includes('shake')&&!reduced)animate(document.querySelector<HTMLElement>('#map'),[{translate:'0 0'},...Array.from({length:8},(_,i)=>({translate:`${(i%2?1:-1)*6*strength*(1-i/8)}px ${(i%3-1)*4*strength}px`})),{translate:'0 0'}]);
  if(!temporaryCleanup&&(c.effects.includes('zoom')||c.effects.includes('travel'))){cameraEffect=true;map.easeTo({center:target.position(),zoom:c.effects.includes('zoom')?Math.min(map.getMaxZoom(),map.getZoom()+.6*strength):map.getZoom(),duration:reduced?0:duration});}
  if(c.effects.includes('burst')||c.effects.includes('rain')||c.effects.includes('flash')||c.effects.includes('pinpoint')){if(canvases.size>=32)return;const canvas=document.createElement('canvas');canvas.className='juice-canvas';canvas.setAttribute('aria-hidden','true');viewport.append(canvas);canvases.add(canvas);const ctx=canvas.getContext('2d')!;const dpr=Math.min(2,devicePixelRatio||1);canvas.width=viewport.clientWidth*dpr;canvas.height=viewport.clientHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const rain=c.effects.includes('rain'),burst=c.effects.includes('burst'),count=reduced?8:Math.round((rain?65:35)*strength),particles=Array.from({length:count},(_,i)=>({angle:i/count*Math.PI*2,speed:35+Math.random()*65,offset:(Math.random()-.5)*180*strength,size:2+Math.random()*3})),start=performance.now();canvas.dataset.playing='true';
   const tick=(now:number)=>{const t=Math.min(1,(now-start)/duration),p=map.project(target.position());ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=c.color;ctx.strokeStyle=c.color;if(c.effects.includes('pinpoint')){ctx.lineWidth=2;for(let k=0;k<3;k++){const phase=(t+k/3)%1;ctx.globalAlpha=(1-phase)*.85;ctx.beginPath();ctx.ellipse(p.x,p.y,12+phase*75*strength,6+phase*36*strength,0,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1-t;ctx.beginPath();ctx.moveTo(p.x,p.y-36);ctx.lineTo(p.x,p.y-18);ctx.moveTo(p.x-9,p.y-26);ctx.lineTo(p.x,p.y-18);ctx.lineTo(p.x+9,p.y-26);ctx.stroke();}if(c.effects.includes('flash')){ctx.globalAlpha=(1-t)*.3;ctx.beginPath();ctx.arc(p.x,p.y,15+40*t*strength,0,Math.PI*2);ctx.fill();}if(burst){ctx.globalAlpha=(1-t)*.8;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,8+t*90*strength,0,Math.PI*2);ctx.stroke();}if(burst||rain)for(const q of particles){const x=rain?p.x+q.offset:p.x+Math.cos(q.angle)*q.speed*t*strength,y=rain?p.y-100*strength+200*t*strength:p.y+Math.sin(q.angle)*q.speed*t*strength+20*t*t;ctx.globalAlpha=(1-t)*.9;ctx.fillRect(x,y,q.size,q.size*(rain?2:1));}ctx.globalAlpha=1;if(t<1){const id=requestAnimationFrame(n=>{rafs.delete(id);tick(n);});rafs.add(id);}else{canvas.remove();canvases.delete(canvas);}};const id=requestAnimationFrame(n=>{rafs.delete(id);tick(n);});rafs.add(id);}

 }
 function toggle(on:boolean){active=on;document.querySelector('#workshop')!.classList.toggle('juice-mode',on);panel.hidden=!on;tabs.querySelector('#settings-tab')!.setAttribute('aria-pressed',String(!on));tabs.querySelector('#juice-tab')!.setAttribute('aria-pressed',String(on));if(on)render();}
 tabs.querySelector('#settings-tab')!.addEventListener('click',()=>toggle(false));tabs.querySelector('#juice-tab')!.addEventListener('click',()=>toggle(true));
 panel.addEventListener('change',e=>{const el=e.target as HTMLInputElement;if(el.id==='juice-type'){selectedType=el.value;preview='all';render();}if(el.id==='juice-trigger'){event=el.value;render();}if(el.id==='juice-target')preview=el.value;});
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement;if(!el.matches('[data-juice-effect],#juice-intensity,#juice-duration,#juice-color'))return;const c:JuiceConfig={effects:[...panel.querySelectorAll<HTMLInputElement>('[data-juice-effect]:checked')].map(e=>e.dataset.juiceEffect as keyof typeof juiceEffects),intensity:Number((panel.querySelector('#juice-intensity') as HTMLInputElement).value),duration:Number((panel.querySelector('#juice-duration') as HTMLInputElement).value),color:(panel.querySelector('#juice-color') as HTMLInputElement).value};save(c);panel.querySelector('#juice-intensity-out')!.textContent=String(c.intensity);panel.querySelector('#juice-duration-out')!.textContent=`${c.duration} ms`;});
 panel.addEventListener('click',e=>{const id=(e.target as HTMLElement).closest('button')?.id;
  if(id==='juice-add-event'){const name=(panel.querySelector('#juice-new-event') as HTMLInputElement).value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'_');if(!/^[a-z][a-z0-9_-]{0,39}$/.test(name)){panel.querySelector('#juice-feedback')!.textContent='Utilise un nom court : lettres, chiffres, tirets.';return;}if(!state().events.includes(name)){if(state().events.length>=100)return;state().events.push(name);}event=name;changed();render();refreshFocus();}
  if(id==='juice-delete-event'&&confirm(`Supprimer « ${event} » et ses règles ?`)){state().rules=state().rules.filter(r=>r.event!==event);state().events=state().events.filter(e=>e!==event);if(!state().events.length)state().events.push('manual');changed();render();refreshFocus();}
  if(id==='juice-clear-legacy'&&confirm('Retirer les effets individuels provenant des anciens exports ?')){state().rules=state().rules.filter(r=>!r.target);changed();render();refreshFocus();}
  if(id==='juice-test'){save(structuredClone(config()));stop();const list=targets().filter(t=>t.type===selectedType&&(preview==='all'||t.key===preview));for(const t of list)play(t,config());panel.querySelector('#juice-feedback')!.textContent=list.length?`${config().effects.length} effet(s) · ${event} · ${list.length} cible(s)`:'Place un élément de ce type sur la carte pour tester.';}
  if(id==='juice-stop')stop();if(id==='juice-clear'){state().rules=state().rules.filter(r=>r!==rule());stop();changed();render();refreshFocus();}
 });
 function trigger(key:string,event:string){const t=targets().find(t=>t.key===key);if(t)for(const r of matchingJuice(state(),t.type,event,key))play(t,r.config);}
 window.addEventListener('vigilante:juice',e=>{const d=(e as CustomEvent).detail;if(!d||typeof d.event!=='string')return;for(const t of targets().filter(t=>d.target?t.key===d.target:t.type===d.type))trigger(t.key,d.event);});
 return {focus(keys:string[]){focusKeys.clear();keys.forEach(k=>focusKeys.add(k));refreshFocus();},select(key:string){if(!active)return false;const t=targets().find(t=>t.key===key);if(t){selectedType=t.type;preview=t.key;render();}return true;},trigger,active:()=>active,refresh(){if(active)render();refreshFocus();},stop,reset(){stop();selectedType='hero';event='click';preview='all';render();refreshFocus();}};
}
