import {createHeroDock} from './map-hero-dock';
import {createBuildings} from './map-buildings';
import {readBuildings,type BuildingEdit} from './map-building-state';
import {placeMapPopover} from './map-popover';
import {readRouteStyle,type RouteStyle} from './map-route-style';
import {createRain,readWeather,type Weather} from './map-weather';
import {createTravel,journeyProgress,type Journey} from './map-travel';
import {roadDistance} from './map-roads';
import {createJuice,readJuice,type JuiceState,type JuiceTarget} from './map-juice';
import {HERO_SHEET_WIDTH,heroSheetURL,updateHeroSheet} from './hero-sheet-bridge';
import {activityForOrder,WATCH_ENERGY_PER_SECOND,HQ_RECOVERY_PER_SECOND} from './hero-activities';
import {pencilRing} from './map-pencil';
import type {FeatureCollection} from 'geojson';
import {Marker,type Map as MapLibreMap,type GeoJSONSource} from 'maplibre-gl';
import {heroRoster,heroAsset} from './hero-roster';
import {icon} from './icons';
import './map-scene.css';
export type Coord=[number,number];
type Agent={idle?:{order:'ready'|'watch';zone?:string};resumeIdle?:boolean;point?:string;journey?:Journey;speed?:number;duty?:boolean;color?:string;id:string;hero:string;position:Coord;order:'ready'|'watch'|'patrol';zone?:string;hp:number;mental:number;energy:number};
type Vehicle={journey?:Journey;id:string;kind:'car'|'bike';position:Coord;heading:number};
type Zone={tolerance?:number;id:string;name:string;ring:Coord[];color:string;agent?:string;order:'watch'|'patrol'};
type Ambience={light:number;lightColor:string;azimuth:number;contrast:number;saturation:number;glow:number;pulse:boolean;shadows:boolean;zoneOpacity:number};
type Floating={open:boolean;agent?:string;x:number;y:number;width:number;height?:number};
export type Scene={patrolVersion?:2;buildings?:BuildingEdit[];routeStyle?:RouteStyle;weather?:Weather;juice?:JuiceState;travelSpeed?:number;ambience:Ambience;agents:Agent[];vehicles:Vehicle[];zones:Zone[];window:Floating;zoneColors?:{watch:string;patrol:string}};
const defaultAmbience:Ambience={light:.45,lightColor:'#e9edff',azimuth:210,contrast:1,saturation:1,glow:.45,pulse:false,shadows:true,zoneOpacity:.12};
export const emptyScene=():Scene=>({patrolVersion:2,ambience:{...defaultAmbience},agents:[],vehicles:[],zones:[],window:{open:false,x:.1,y:.12,width:360}});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function readScene(value:unknown):Scene {
 const d=emptyScene();if(value===undefined)return d;
 if(!value||typeof value!=='object')throw Error('Scène invalide');
 const s=value as Scene;
 const number=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
 const coord=(v:unknown)=>Array.isArray(v)&&v.length===2&&number(v[0],-180,180)&&number(v[1],-85,85);
 const id=(v:unknown)=>typeof v==='string'&&v.length>0&&v.length<=80;
 const color=(v:unknown)=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
 if(!s.ambience||!number(s.ambience.light,0,1)||!color(s.ambience.lightColor)||!number(s.ambience.azimuth,0,360)||!number(s.ambience.contrast,.7,1.6)||!number(s.ambience.saturation,0,1.8)||!number(s.ambience.glow,0,1)||typeof s.ambience.pulse!=='boolean'||typeof s.ambience.shadows!=='boolean'||!number(s.ambience.zoneOpacity,0,.5))throw Error('Ambiance invalide');
 if(!Array.isArray(s.agents)||s.agents.length>100||s.agents.some(a=>!id(a.id)||(a.color!==undefined&&!color(a.color))||!heroRoster.some(h=>h.id===a.hero)||!coord(a.position)||!['ready','watch','patrol'].includes(a.order)||!number(a.hp,0,8)||!number(a.mental,0,10)||!number(a.energy,0,100)))throw Error('Agents invalides');
 if(!Array.isArray(s.vehicles)||s.vehicles.length>100||s.vehicles.some(v=>!id(v.id)||!['car','bike'].includes(v.kind)||!coord(v.position)||!number(v.heading,0,360)))throw Error('Véhicules invalides');
 if(!Array.isArray(s.zones)||s.zones.length>100||s.zones.some(z=>!id(z.id)||!id(z.name)||!color(z.color)||!['watch','patrol'].includes(z.order)||!Array.isArray(z.ring)||z.ring.length<4||z.ring.length>1500||!z.ring.every(coord)||z.ring[0][0]!==z.ring.at(-1)![0]||z.ring[0][1]!==z.ring.at(-1)![1]))throw Error('Zones invalides');
 if(new Set([...s.agents,...s.vehicles,...s.zones].map(o=>o.id)).size!==s.agents.length+s.vehicles.length+s.zones.length)throw Error('Identifiants dupliqués');
 if(s.zones.some(z=>z.agent!==undefined&&!s.agents.some(a=>a.id===z.agent))||s.agents.some(a=>a.zone!==undefined&&!s.zones.some(z=>z.id===a.zone)))throw Error('Affectation invalide');
 if(!s.window||typeof s.window.open!=='boolean'||!number(s.window.x,0,1)||!number(s.window.y,0,1)||!number(s.window.width,220,640)||(s.window.agent!==undefined&&!s.agents.some(a=>a.id===s.window.agent)))throw Error('Fenêtre invalide');
 if(s.window.height!==undefined&&!number(s.window.height,180,1200))throw Error('Hauteur invalide');
 if(s.zoneColors&&(!color(s.zoneColors.watch)||!color(s.zoneColors.patrol)))throw Error('Couleurs des secteurs invalides');
 if(s.travelSpeed!==undefined&&!number(s.travelSpeed,1,30))throw Error('Vitesse invalide');
 for(const a of [...s.agents,...s.vehicles])if(a.journey&&(!Array.isArray(a.journey.path)||a.journey.path.length<2||a.journey.path.length>20000||!a.journey.path.every(coord)||!Number.isInteger(a.journey.next)||a.journey.next<1||a.journey.next>=a.journey.path.length||typeof a.journey.destination!=='string'||a.journey.destination.length>120))throw Error('Trajet invalide');
 for(const a of s.agents)if((a.speed!==undefined&&!number(a.speed,1,100))||(a.duty!==undefined&&typeof a.duty!=='boolean'))throw Error('Activité invalide');
 for(const a of [...s.agents,...s.vehicles]){const j=a.journey;if(!j)continue;if(j.loopActive!==undefined&&typeof j.loopActive!=='boolean')throw Error('Boucle invalide');if(j.loopStart!==undefined){if(!Number.isInteger(j.loopStart)||j.loopStart<0||j.loopStart>=j.path.length-1||j.path[j.loopStart][0]!==j.path.at(-1)![0]||j.path[j.loopStart][1]!==j.path.at(-1)![1]||!j.path.slice(j.loopStart+1).some(p=>roadDistance(j.path[j.loopStart!],p)>1))throw Error('Boucle invalide');}else if(j.loopActive)throw Error('Boucle invalide');}
 const next=structuredClone(s);if(next.patrolVersion!==2){for(const a of next.agents)if(a.duty&&a.zone)delete a.journey;next.patrolVersion=2;}next.buildings=readBuildings(s.buildings);next.juice=readJuice(s.juice);next.weather=readWeather(s.weather);next.routeStyle=readRouteStyle(s.routeStyle);for(const a of next.agents)if(a.point!==undefined&&!id(a.point))throw Error('Lieu du héros invalide');for(const a of [...next.agents,...next.vehicles])if(a.journey&&((a.journey.targetPoint!==undefined&&!id(a.journey.targetPoint))||(a.journey.totalDistance!==undefined&&!number(a.journey.totalDistance,0,1e9))))throw Error('Progression invalide');for(const a of next.agents){if(a.order==='patrol')a.order='watch';if(a.idle&&(!['ready','watch'].includes(a.idle.order)||(a.idle.zone!==undefined&&!next.zones.some(z=>z.id===a.idle!.zone))))throw Error('Idle invalide');if(a.resumeIdle!==undefined&&typeof a.resumeIdle!=='boolean')throw Error('Retour idle invalide');a.idle??={order:a.order==='watch'?'watch':'ready',zone:a.zone};if(a.duty===undefined&&(a.zone||(a.order==='ready'&&!a.journey)))a.duty=true;if(a.duty&&a.zone&&a.journey?.loopStart===undefined)delete a.journey;}for(const z of next.zones){if(z.tolerance!==undefined&&!number(z.tolerance,0,80))throw Error('Marge de secteur invalide');z.order='watch';} for(const b of next.buildings!){if(b.geometry.type==='MultiPolygon'&&!b.parts)b.geometry={type:'Polygon',coordinates:b.geometry.coordinates[0]};if(b.effect==='pulse'&&!next.juice!.rules.some(r=>r.target===`building:${b.id}`)){next.juice!.rules.push({id:`building-legacy-${b.id}`,type:'building',event:'focus',target:`building:${b.id}`,config:{effects:['pulse'],color:b.color,intensity:1,duration:1500}});b.effect='none';}}return next;
}
const car=`<svg viewBox="0 0 48 78" aria-hidden="true"><rect x="8" y="5" width="32" height="68" rx="10" fill="#67899c" stroke="#c4e5ee" stroke-width="2"/><path d="M12 23h24l-3 12H15zM15 47h18l3 12H12z" fill="#142831" stroke="#8abacb"/><path d="M9 38h30M17 6v6m14-6v6M13 66h6m10 0h6" stroke="#eacb8e" stroke-width="3"/><path d="M6 20v13m36-13v13M6 49v13m36-13v13" stroke="#0b121b" stroke-width="4"/></svg>`;
export function createScene(map:MapLibreMap,initial:Scene,changed:()=>void,status:(s:string)=>void,getPoints:()=>{id:string;type:string;name:string;lng:number;lat:number}[]=()=>[]){
 let scene=readScene(initial),markers:Marker[]=[],zoneMarkers:Marker[]=[],drawing=false,stroke:Coord[]=[],screenStroke:Coord[]=[],selectedZone:string|undefined,selectedVehicle:string|undefined,suppressClick=false;
 scene.buildings=readBuildings(scene.buildings);scene.juice=readJuice(scene.juice);scene.weather=readWeather(scene.weather);scene.routeStyle=readRouteStyle(scene.routeStyle);
 scene.zoneColors??={watch:activityForOrder('watch').color,patrol:activityForOrder('patrol').color};
 const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const viewport=document.querySelector<HTMLElement>('.viewport')!;
 const tools=document.createElement('div');tools.id='scene-tools';tools.innerHTML=`<details open><summary>Héros & véhicules</summary><div class="fields"><label>Héros<select id="map-hero">${heroRoster.map(h=>`<option value="${h.id}" ${h.id==='beton'?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><div class="pair"><button id="add-agent">${icon('users')}Au centre</button><button id="place-agent">${icon('map-pin')}Placer</button></div><div id="agent-list"></div><label>Véhicule<select id="vehicle-kind"><option value="car">Voiture</option><option value="bike">Moto</option></select></label><div class="pair"><button id="add-vehicle">${icon('route')}Au centre</button><button id="place-vehicle">${icon('map-pin')}Placer</button></div><div id="vehicle-list"></div><div id="vehicle-editor" hidden></div><label class="range">Vitesse de simulation<output id="travel-speed-out">×${scene.travelSpeed??8}</output><input id="travel-speed" type="range" min="1" max="30" step="1" value="${scene.travelSpeed??8}"></label><p class="hint">Sélectionne un héros, choisis Déplacer, puis clique sa destination. Il suit les rues; les points sont rattachés à la rue la plus proche. Glisser un token sert au placement dans l’atelier.</p></div></details><details open><summary>Crayon & zones</summary><div class="fields"><button id="draw-zone" aria-pressed="false">${icon('tools')}Encercler un secteur</button><p class="hint">Trace un contour en gardant le bouton ou le doigt appuyé. Le trait se ferme quand tu relâches. Échap annule.</p><label>Nom de la prochaine zone<input id="zone-name" maxlength="80" placeholder="Secteur à surveiller"></label><label class="color-row">Surveillance<input id="zone-color" data-zone-color="watch" type="color" value="${scene.zoneColors.watch}"></label><div id="zone-list"></div></div></details>`;
 const poiDetails=$('point-list').closest('details')!;poiDetails.before(tools);
 const ambiance=document.createElement('div');ambiance.id='ambience-controls';ambiance.innerHTML=`<h2>Ambiance & effets</h2><div class="presets"><button data-mood="neutral">Neutre</button><button data-mood="night">Nuit</button><button data-mood="warm">Chaud</button></div>${[['light','Éclairage des volumes',0,1,.05],['azimuth','Direction de la lumière',0,360,5],['contrast','Contraste',.7,1.6,.05],['saturation','Saturation',0,1.8,.05],['zoneOpacity','Opacité des zones',0,.5,.01]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-effect-out="${key}"></output><input data-effect="${key}" type="range" min="${min}" max="${max}" step="${step}"></label>`).join('')}<label class="color-row">Teinte de la lumière<input data-effect="lightColor" type="color"></label><p class="hint">Pulse et glow : onglet Juice → focus.</p><label class="check"><input data-effect="shadows" type="checkbox">Ombre sous les tokens</label><p class="hint">Relief : utilise Bâtiments en volume et Hauteur 3D au-dessus.</p>`;
 $('visual-controls').after(ambiance);const rain=createRain(viewport,ambiance,()=>scene.weather!,changed,map);
 const zonePanel=document.createElement('section');zonePanel.id='zone-editor';zonePanel.role='dialog';zonePanel.setAttribute('aria-label','Secteur');zonePanel.hidden=true;viewport.append(zonePanel);
 const pencil=document.createElement('div');pencil.className='pencil-toolbar';pencil.innerHTML=`<button id="map-pencil" aria-label="Dessiner une zone" aria-pressed="false">${icon('tools')}Crayon</button><button id="cancel-pencil" hidden>${icon('x')}Annuler</button>`;viewport.append(pencil);
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('pencil-overlay');svg.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');svg.append(path);viewport.append(svg);
 const floating=document.createElement('section');floating.id='hero-window';floating.role='dialog';floating.setAttribute('aria-modal','false');floating.setAttribute('aria-label','Fiche du héros');floating.hidden=true;
 floating.innerHTML=`<div class="hero-window-canvas"><div class="hero-window-bar"><button id="hero-window-drag" aria-label="Déplacer la fiche"><span id="hero-window-title">Fiche du héros</span>${icon('arrows-move')}</button><button id="hero-window-smaller" aria-label="Rapetisser la fiche">−</button><button id="hero-window-larger" aria-label="Agrandir la fiche">+</button><button id="hero-center" aria-label="Centrer sur le héros">${icon('target')}</button><button id="hero-window-close" aria-label="Fermer la fiche">${icon('x')}</button></div><iframe title="Fiche du Hero Gym" id="hero-frame"></iframe></div><button id="hero-window-resize" aria-label="Redimensionner la fiche">◢</button>`;viewport.append(floating);
 let mode:'agent'|'vehicle'|undefined,frameKey='',moveActor:string|undefined;
 const dutyTimers=new Map<string,ReturnType<typeof setTimeout>>();
 const travel=createTravel(map,()=>[...scene.agents,...scene.vehicles],()=>scene.travelSpeed??8,changed,(id,point)=>{const actor=scene.agents.find(a=>a.id===id);if(actor){actor.point=point;occupants();if(!actor.journey&&actor.resumeIdle)scheduleResume(actor);}syncSheet();juice.trigger(`hero:${id}`,'arrival');juice.trigger(`vehicle:${id}`,'arrival');const a=scene.agents.find(a=>a.id===id);if(a?.duty&&a.zone&&!a.journey)runDuty(a.id);else status('Destination atteinte.');},status,(id,p)=>{const m=markers.find(m=>m.getElement().dataset.actor===id),v=scene.vehicles.find(v=>v.id===id);if(m&&v){const before=m.getLngLat(),dx=(p[0]-before.lng)*Math.cos(p[1]*Math.PI/180),dy=p[1]-before.lat;if(Math.hypot(dx,dy)>1e-9){v.heading=(Math.atan2(dx,dy)*180/Math.PI+360)%360;m.setRotation(v.heading);}}m?.setLngLat(p);},()=>scene.routeStyle!, (id,seconds,progress)=>{if(scene.window.open&&scene.window.agent===id)$<HTMLIFrameElement>('hero-frame').contentWindow?.postMessage({type:'map-hero-progress',agent:id,seconds,progress},location.origin);});
 function juiceTargets():JuiceTarget[]{return [{key:'map',type:'map',name:'Carte · caméra',position:()=>center(),element:()=>map.getCanvas()},...scene.agents.map(a=>({key:`hero:${a.id}`,type:'hero',states:()=>[...(a.hp/8<=.25?['low_hp']:[]),...(a.mental/10<=.25?['low_mental']:[]),...(a.energy<=25?['low_energy']:[]),...(a.journey?['moving']:[])],name:heroRoster.find(h=>h.id===a.hero)!.name,position:()=>a.position,element:()=>document.querySelector<HTMLElement>(`[data-resident="${a.id}"]`)||markers.find(m=>m.getElement().dataset.actor===a.id)?.getElement()||null})),...scene.vehicles.map(v=>({key:`vehicle:${v.id}`,type:'vehicle',name:v.kind==='car'?'Voiture':'Moto',position:()=>v.position,element:()=>markers.find(m=>m.getElement().dataset.actor===v.id)?.getElement()||null})),...scene.zones.map(z=>({key:`zone:${z.id}`,type:'zone',name:z.name,position:()=>zoneCenter(z),element:()=>zoneMarkers.find(m=>m.getElement().dataset.zone===z.id)?.getElement()||null})),...buildings.targets(),...getPoints().map(p=>({key:`point:${p.id}`,type:`point:${p.type}`,name:p.name,position:()=>[p.lng,p.lat] as Coord,element:()=>document.querySelector<HTMLElement>(`[data-poi="${p.id}"]`)}))];}
 const juice=createJuice(map,viewport,juiceTargets,()=>scene.juice!,changed);
 const buildings=createBuildings(map,viewport,tools,()=>scene.buildings!,getPoints,changed,(id,event)=>juice.trigger(`building:${id}`,event),id=>{selectedBuilding=id;syncFocus();});
 const dock=createHeroDock(viewport,()=>scene.agents.map(a=>({...a,selected:scene.window.open&&scene.window.agent===a.id,idleLabel:a.idle?.order==='watch'?`Surveillance · ${scene.zones.find(z=>z.id===a.idle?.zone)?.name||'secteur à choisir'}`:'QG',task:a.journey&&!a.journey.loopActive?'En déplacement':a.duty&&a.order==='watch'?'Surveillance':a.journey?'En déplacement':atHQ(a)?'Au QG':a.duty?'Retour au QG':'Disponible',detail:a.journey&&!a.journey.loopActive?`${a.journey.destination} · ${journeyProgress(a,scene.travelSpeed??8).seconds.toFixed(1)} s`:a.duty&&a.order==='watch'?`${scene.zones.find(z=>z.id===a.zone)?.name||'Secteur à choisir'} · −${WATCH_ENERGY_PER_SECOND.toLocaleString('fr-CA')} énergie/s`:a.journey?`${a.journey.destination} · ${journeyProgress(a,scene.travelSpeed??8).seconds.toFixed(1)} s`:getPoints().find(p=>p.id===a.point)?.name||''})),openAgent,id=>{const a=scene.agents.find(a=>a.id===id);if(a)centerTarget(`hero:${id}`,a.position);});
 let selectedPoint:string|undefined,selectedBuilding:string|undefined;
 function syncFocus(){juice.focus([...(selectedBuilding?[`building:${selectedBuilding}`]:[]),...(scene.window.open&&scene.window.agent?[`hero:${scene.window.agent}`]:[]),...(selectedVehicle?[`vehicle:${selectedVehicle}`]:[]),...(selectedZone?[`zone:${selectedZone}`]:[]),...(selectedPoint?[`point:${selectedPoint}`]:[])]);}
 function centerTarget(key:string,position:Coord){map.once('moveend',()=>juice.trigger(key,'centered'));map.easeTo({center:position,duration:500});}
 function occupants(){for(const el of document.querySelectorAll('.poi-residents'))el.remove();for(const a of scene.agents){const token=markers.find(m=>m.getElement().dataset.actor===a.id)?.getElement(),p=getPoints().find(p=>p.id===a.point),root=p?document.querySelector<HTMLElement>(`[data-poi="${p.id}"]`):null;if(token)token.hidden=!!root&&!a.journey;if(!root||a.journey)continue;let list=root.querySelector<HTMLElement>('.poi-residents');if(!list){list=document.createElement('span');list.className='poi-residents';root.append(list);}const portrait=document.createElement('span');portrait.className='poi-resident';portrait.tabIndex=0;portrait.role='button';portrait.setAttribute('aria-label',`Fiche de ${heroRoster.find(h=>h.id===a.hero)!.name}`);portrait.dataset.resident=a.id;portrait.innerHTML=`<img src="${heroAsset(a.hero,'portrait','dossier')}" alt="">`;portrait.onclick=e=>{e.stopPropagation();openAgent(a.id);};portrait.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();openAgent(a.id);}};list.append(portrait);}syncFocus();}
 const routePanel=document.createElement('section');routePanel.id='route-controls';ambiance.append(routePanel);
 function routeControls(){const s=scene.routeStyle!;routePanel.innerHTML=`<h2>Chemins de déplacement</h2><label class="check"><input data-route="useActorColor" type="checkbox" ${s.useActorColor?'checked':''}>Couleur du héros</label><label class="color-row">Couleur commune<input data-route="color" type="color" value="${s.color}"></label>${[['width','Épaisseur',1,10,.5],['opacity','Opacité',.1,1,.05]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-route-out="${key}">${s[key as keyof RouteStyle]}</output><input data-route="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${s[key as keyof RouteStyle]}"></label>`).join('')}<label>Trait<select data-route="pattern">${[['solid','Continu'],['dashed','Tirets'],['dotted','Points']].map(([k,n])=>`<option value="${k}" ${s.pattern===k?'selected':''}>${n}</option>`).join('')}</select></label><label class="check"><input data-route="shadow" type="checkbox" ${s.shadow?'checked':''}>Contour sombre</label><label class="check"><input data-route="flow" type="checkbox" ${s.flow?'checked':''}>Pulsation du trajet</label>`;}
 routePanel.addEventListener('input',e=>{const el=e.target as HTMLInputElement,key=el.dataset.route;if(!key)return;(scene.routeStyle as unknown as Record<string,unknown>)[key]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;const out=routePanel.querySelector(`[data-route-out="${key}"]`);if(out)out.textContent=el.value;travel.restyle();changed();});routeControls();
 map.on('move',()=>{const z=scene.zones.find(z=>z.id===selectedZone);if(z)placeMapPopover(map,zonePanel,zoneCenter(z),z.ring);});
 function atHQ(a:Agent){return !a.journey&&!!getPoints().find(p=>p.id===a.point&&p.type==='hq');}
 function context(){const a=scene.agents.find(a=>a.id===scene.window.agent);return a?{agent:a.id,hero:a.hero,hp:a.hp,mental:a.mental,energy:a.energy,order:a.order,zone:a.zone,zones:scene.zones.map(z=>({id:z.id,name:z.name})),...journeyProgress(a,scene.travelSpeed??8),atHQ:atHQ(a),idleOrder:a.idle?.order||'ready',idleZone:a.idle?.zone,energyRate:WATCH_ENERGY_PER_SECOND,travel:!!a.journey&&!a.journey.loopActive,duty:!!a.duty,moveArmed:moveActor===a.id,destination:a.journey?.destination||getPoints().find(p=>p.id===a.point)?.name||scene.zones.find(z=>z.id===a.zone)?.name}:undefined;}
 function syncSheet(){dock.refresh();const c=context();if(c)updateHeroSheet($<HTMLIFrameElement>('hero-frame'),c);}
 function cancelDuty(id:string){clearTimeout(dutyTimers.get(id));dutyTimers.delete(id);travel.stop(id);}
 function scheduleDuty(a:Agent){clearTimeout(dutyTimers.get(a.id));dutyTimers.set(a.id,setTimeout(()=>runDuty(a.id),1200));}
 function scheduleResume(a:Agent){clearTimeout(dutyTimers.get(a.id));dutyTimers.set(a.id,setTimeout(()=>{if(!a.resumeIdle||a.journey)return;const pref=a.idle||{order:'ready' as const};delete a.resumeIdle;setDuty(a,pref.order,pref.zone);},1200));}
 function runDuty(id:string){const a=scene.agents.find(a=>a.id===id);if(!a||!a.duty||a.journey)return;const z=scene.zones.find(z=>z.id===a.zone);if(a.order==='ready'){const hq=getPoints().filter(p=>p.type==='hq').sort((p,q)=>roadDistance(a.position,[p.lng,p.lat])-roadDistance(a.position,[q.lng,q.lat]))[0];if(hq){if(a.point===hq.id){syncSheet();return;}delete a.point;travel.send(a.id,[hq.lng,hq.lat],hq.name,undefined,hq.id);occupants();}else status('Place un point QG pour permettre le retour du héros.');syncSheet();return;}if(!z){status('Choisis un secteur dans la fiche du héros.');return;}const network=travel.network(),sector=network.sector(z.ring,z.tolerance??12),loop=sector.patrolPath(a.position);if(loop.length<3){status('Aucune rue accessible dans ce secteur. Augmente sa marge ou charge les rues alentour.');return;}const approach=network.route(a.position,loop[0]);if(approach.length<2){status('Aucun parcours routier continu vers ce secteur.');return;}approach[approach.length-1]=loop[0];const atStart=roadDistance(a.position,loop[0])<1,path=atStart?loop:[...approach,...loop.slice(1)],loopStart=atStart?0:approach.length-1;travel.follow(a.id,path,z.name,undefined,loopStart);syncSheet();}
 function setDuty(a:Agent,order:Agent['order'],zone?:string){a.idle={order:order==='ready'?'ready':'watch',zone:order==='ready'?undefined:zone||undefined};delete a.resumeIdle;moveActor=undefined;if(order==='patrol')order='watch';cancelDuty(a.id);for(const z of scene.zones)if(z.agent===a.id)delete z.agent;a.order=order;a.duty=true;if(!(order==='ready'&&atHQ(a)))delete a.point;delete a.zone;const z=scene.zones.find(z=>z.id===zone);if(order!=='ready'&&z){if(z.agent){const previous=scene.agents.find(x=>x.id===z.agent);if(previous){cancelDuty(previous.id);previous.duty=false;delete previous.zone;previous.order='ready';previous.idle={order:'ready'};}}z.agent=a.id;z.order=order;z.color=scene.zoneColors![order];a.zone=z.id;}renderActors();renderZones();zoneEditor();syncSheet();changed();runDuty(a.id);}
 function dispatch(position:Coord,label='Destination',point?:string){const a=scene.agents.find(a=>a.id===moveActor);const actor=a||scene.vehicles.find(v=>v.id===moveActor);if(!actor)return false;moveActor=undefined;cancelDuty(actor.id);if(a){a.idle??={order:a.order==='ready'?'ready':'watch',zone:a.zone};delete a.point;a.duty=false;a.order='ready';a.resumeIdle=true;renderZones();}const sent=travel.send(actor.id,position,label,undefined,point);if(!sent&&a)scheduleResume(a);renderActors();vehicleEditor();syncSheet();return true;}
 function syncEffects(){for(const input of ambiance.querySelectorAll<HTMLInputElement>('[data-effect]')){const key=input.dataset.effect as keyof Ambience;if(input.type==='checkbox')input.checked=scene.ambience[key] as boolean;else input.value=String(scene.ambience[key]);const out=ambiance.querySelector(`[data-effect-out="${key}"]`);if(out)out.textContent=String(scene.ambience[key]);}}
 function effects(){const a=scene.ambience;viewport.style.setProperty('--point-glow','0px');viewport.classList.remove('pulse-alerts');viewport.classList.toggle('token-shadows',a.shadows);$('map').style.filter=`contrast(${a.contrast}) saturate(${a.saturation})`;map.setLight({anchor:'map',color:a.lightColor,intensity:a.light,position:[1.5,a.azimuth,45]});if(map.getLayer('scene-zone-fill'))map.setPaintProperty('scene-zone-fill','fill-opacity',a.zoneOpacity);syncEffects();}
 function windowLayout(){
  const v=scene.window,w=Math.min(v.width,viewport.clientWidth-20),scale=w/HERO_SHEET_WIDTH,height=Math.min(v.height??w*920/520,viewport.clientHeight-(scene.agents.length?207:24));
  floating.querySelector<HTMLElement>('.hero-window-canvas')!.style.height=`${height/scale}px`;$<HTMLIFrameElement>('hero-frame').style.height=`${(height-18)/scale-48}px`;
  floating.style.width=`${w}px`;floating.style.height=`${height}px`;floating.style.left=`${Math.max(8,Math.min(v.x*viewport.clientWidth,viewport.clientWidth-w-8))}px`;floating.style.top=`${Math.max(8,Math.min(v.y*viewport.clientHeight,viewport.clientHeight-height-(scene.agents.length?207:8)))}px`;floating.querySelector<HTMLElement>('.hero-window-canvas')!.style.transform=`scale(${scale})`;viewport.dispatchEvent(new Event('map-layout'));
 }
 function selectionUI(){for(const v of scene.vehicles){const el=markers.find(m=>m.getElement().dataset.actor===v.id)?.getElement();el?.classList.toggle('is-selected',v.id===selectedVehicle);el?.setAttribute('aria-pressed',String(v.id===selectedVehicle));}for(const a of scene.agents){const el=markers.find(m=>m.getElement().dataset.actor===a.id)?.getElement();if(!el)continue;const selected=scene.window.open&&scene.window.agent===a.id;el.classList.toggle('is-selected',selected);el.setAttribute('aria-pressed',String(selected));el.style.setProperty('--point',a.color||'#78dcde');}}
 function windowUI(){dock.refresh();selectionUI();syncFocus();const a=scene.agents.find(a=>a.id===scene.window.agent);floating.hidden=!scene.window.open||!a;windowLayout();if(!a){frameKey='';return;}const name=heroRoster.find(h=>h.id===a.hero)!.name;$('hero-window-title').textContent=name;floating.setAttribute('aria-label',`Fiche de ${name}`);if(frameKey!==a.id){frameKey=a.id;$<HTMLIFrameElement>('hero-frame').src=heroSheetURL(context()!);}}
 function openAgent(id:string){moveActor=undefined;if(juice.select(`hero:${id}`))return;juice.trigger(`hero:${id}`,'click');selectedVehicle=undefined;selectedZone=undefined;zoneEditor();scene.window={...scene.window,agent:id,open:true};windowUI();syncSheet();changed();}
 function token(position:Coord,el:HTMLElement,ground=false){const m=new Marker({element:el,draggable:!drawing,anchor:ground?'center':'bottom',pitchAlignment:ground?'map':'viewport',rotationAlignment:ground?'map':'viewport'}).setLngLat(position).addTo(map);markers.push(m);return m;}
 function renderActors(){markers.forEach(m=>m.remove());markers=[];
  for(const a of scene.agents){const h=heroRoster.find(h=>h.id===a.hero)!;const el=document.createElement('button');el.className='agent-token';el.setAttribute('aria-label',`Fiche de ${h.name}`);el.dataset.actor=a.id;el.style.setProperty('--point',a.color||'#78dcde');el.innerHTML=`<span class="token-ground"></span><span class="token-stem"></span><span class="token-portrait"><img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span class="token-order">${icon(activityForOrder(a.order).icon)}</span></span><span class="token-caption">${esc(h.name)}</span>`;el.onclick=e=>{e.stopPropagation();if(!drawing&&!suppressClick)openAgent(a.id);};const m=token(a.position,el);m.on('dragstart',()=>{suppressClick=true;cancelDuty(a.id);a.duty=false;delete a.point;occupants();});m.on('dragend',()=>{const c=m.getLngLat();a.position=[c.lng,c.lat];setTimeout(()=>suppressClick=false,100);changed();});}
  for(const v of scene.vehicles){const el=document.createElement('button');el.className='vehicle-token';el.dataset.actor=v.id;el.setAttribute('aria-label',v.kind==='car'?'Voiture':'Moto');el.innerHTML=v.kind==='car'?car:icon('motorbike');el.onclick=e=>{e.stopPropagation();if(juice.select(`vehicle:${v.id}`))return;juice.trigger(`vehicle:${v.id}`,'click');moveActor=undefined;selectedVehicle=v.id;scene.window.open=false;windowUI();vehicleEditor();};const m=token(v.position,el,true);m.setRotation(v.heading);m.on('dragstart',()=>{cancelDuty(v.id);});m.on('dragend',()=>{const c=m.getLngLat();v.position=[c.lng,c.lat];changed();});}
  perspective();lists();selectionUI();occupants();syncFocus();dock.refresh();
 }
 function perspective(){for(const el of viewport.querySelectorAll<HTMLElement>('.token-ground')){el.style.transform=`rotateX(${map.getPitch()}deg) rotateZ(${-map.getBearing()}deg)`;}}
 function lists(){
  $('agent-list').innerHTML=scene.agents.map(a=>{const h=heroRoster.find(h=>h.id===a.hero)!;return `<div class="agent-options"><div class="scene-row"><button data-agent="${a.id}"><img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span>${esc(h.name)}<small>${a.order!=='ready'?'Surveillance':'Disponible'}</small></span></button><button data-center-agent="${a.id}" aria-label="Centrer sur ${esc(h.name)}">${icon('target')}</button><button data-remove-agent="${a.id}" aria-label="Retirer ${esc(h.name)}">${icon('x')}</button></div><label class="color-row hero-token-color">Halo de ${esc(h.name)}<input type="color" data-agent-color="${a.id}" aria-label="Couleur du halo de ${esc(h.name)}" value="${a.color||'#78dcde'}"></label></div>`;}).join('');
  $('vehicle-list').innerHTML=scene.vehicles.map(v=>`<div class="scene-row"><button data-vehicle="${v.id}">${icon('route')}${v.kind==='car'?'Voiture':'Moto'}</button><button data-center-vehicle="${v.id}" aria-label="Centrer sur le véhicule">${icon('target')}</button><button data-remove-vehicle="${v.id}" aria-label="Retirer le véhicule">${icon('x')}</button></div>`).join('');
  $('zone-list').innerHTML=scene.zones.map(z=>`<div class="sector-row"><button class="zone-row" data-zone="${z.id}" style="--zone:${z.color}">${icon(activityForOrder(z.order).icon)}<span>${esc(z.name)}${zonePortrait(z)}<small>Surveillance</small></span></button><button data-center-zone="${z.id}" aria-label="Placer ${esc(z.name)} au centre">${icon('target')}</button></div>`).join('');
 }
 function vehicleEditor(){const v=scene.vehicles.find(v=>v.id===selectedVehicle),el=$('vehicle-editor');el.hidden=!v;if(v)el.innerHTML=`<button id="vehicle-move" aria-pressed="${moveActor===v.id}">${icon('route')}Déplacer le véhicule</button>${v.journey?`<button id="vehicle-cancel">${icon('x')}Annuler le trajet…</button>`:''}<label class="range">Orientation<output>${v.heading}°</output><input id="vehicle-heading" type="range" min="0" max="360" step="5" value="${v.heading}"></label>`;}
 function zonePortrait(z:Zone){const a=scene.agents.find(a=>a.id===z.agent);return a?`<img class="zone-portrait" src="${heroAsset(a.hero,'portrait','dossier')}" alt="${esc(heroRoster.find(h=>h.id===a.hero)!.name)}">`:'';}
 function zoneCenter(z:Zone):Coord{return z.ring.slice(0,-1).reduce((sum,p)=>[sum[0]+p[0]/(z.ring.length-1),sum[1]+p[1]/(z.ring.length-1)] as Coord,[0,0] as Coord);}
 function openZone(id:string){if(juice.select(`zone:${id}`))return;juice.trigger(`zone:${id}`,'click');selectedZone=id;selectedPoint=undefined;$('selection').hidden=true;zoneEditor();syncFocus();}
 function zoneEditor(){const z=scene.zones.find(z=>z.id===selectedZone),el=$('zone-editor');el.hidden=!z;if(!z)return;el.innerHTML=`<div class="selection-head"><b>${icon(activityForOrder(z.order).icon)} Secteur ${zonePortrait(z)}</b><button id="close-zone" aria-label="Fermer le secteur">${icon('x')}</button></div><label>Nom<input id="edit-zone-name" maxlength="80" value="${esc(z.name)}"></label><label>Assigner à<select id="zone-agent"><option value="">Personne</option>${scene.agents.map(a=>`<option value="${a.id}" ${a.id===z.agent?'selected':''}>${esc(heroRoster.find(h=>h.id===a.hero)!.name)}</option>`).join('')}</select></label><label class="range">Marge autour du tracé<output>${z.tolerance??12} m</output><input id="zone-tolerance" type="range" min="0" max="80" step="5" value="${z.tolerance??12}"></label><p class="hint">Le trajet reste dans cette marge et parcourt les rues et ruelles connectées du secteur.</p><button data-center-zone="${z.id}">${icon('target')}Placer au centre</button><button id="remove-zone" class="danger">${icon('x')}Supprimer la zone</button>`;placeMapPopover(map,el,zoneCenter(z),z.ring);}

 function assign(z:Zone){z.color=scene.zoneColors![z.order];const a=scene.agents.find(a=>a.id===z.agent);for(const other of scene.agents)if(other.zone===z.id&&other.id!==a?.id){cancelDuty(other.id);other.duty=false;delete other.zone;other.order='ready';other.idle={order:'ready'};}if(a)setDuty(a,z.order,z.id);else{renderActors();renderZones();zoneEditor();syncSheet();changed();}}

 function renderZones(){
  const data:FeatureCollection={type:'FeatureCollection',features:scene.zones.map(z=>({type:'Feature',properties:{id:z.id,color:z.color},geometry:{type:'Polygon',coordinates:[z.ring]}}))};
  (map.getSource('scene-zones') as GeoJSONSource)?.setData(data);zoneMarkers.forEach(m=>m.remove());zoneMarkers=[];
  for(const z of scene.zones){const center=zoneCenter(z);const el=document.createElement('button');el.className='zone-label';el.dataset.zone=z.id;el.style.setProperty('--zone',z.color);el.innerHTML=`<span>${esc(z.name)}</span>${zonePortrait(z)}`;el.onclick=e=>{e.stopPropagation();openZone(z.id);};zoneMarkers.push(new Marker({element:el,offset:[0,-30]}).setLngLat(center).addTo(map));}lists();syncSheet();juice.refresh();
 }
 function addAgent(position:Coord){if(scene.agents.length>=100)return;const hero=$<HTMLSelectElement>('map-hero').value;const a:Agent={id:crypto.randomUUID(),hero,position,order:'ready',color:'#78dcde',hp:6,mental:8,energy:75};a.duty=true;a.idle={order:'ready'};scene.agents.push(a);scheduleDuty(a);renderActors();zoneEditor();openAgent(a.id);status(`${heroRoster.find(h=>h.id===hero)!.name} placé. Glisse son token pour le déplacer.`);changed();}
 function addVehicle(position:Coord){if(scene.vehicles.length>=100)return;const v:Vehicle={id:crypto.randomUUID(),kind:$<HTMLSelectElement>('vehicle-kind').value as Vehicle['kind'],position,heading:0};scene.vehicles.push(v);moveActor=undefined;selectedVehicle=v.id;scene.window.open=false;windowUI();renderActors();vehicleEditor();changed();}
 const center=():Coord=>{const c=map.getCenter();return [c.lng,c.lat];};
 function stopDrawing(){drawing=false;stroke=[];screenStroke=[];path.setAttribute('d','');svg.classList.remove('drawing');viewport.classList.remove('drawing-zone');map.dragPan.enable();map.touchZoomRotate.enable();if(map.getContainer().dataset.cameraLocked==='true')map.touchZoomRotate.disableRotation();map.scrollZoom.enable();markers.forEach(m=>m.setDraggable(true));$('draw-zone').setAttribute('aria-pressed','false');$('map-pencil').setAttribute('aria-pressed','false');$('cancel-pencil').hidden=true;}
 function startDrawing(){if(drawing){stopDrawing();return;}selectedZone=undefined;zoneEditor();$('selection').hidden=true;scene.window.open=false;windowUI();mode=undefined;drawing=true;svg.classList.add('drawing');viewport.classList.add('drawing-zone');map.dragPan.disable();map.touchZoomRotate.disable();map.scrollZoom.disable();markers.forEach(m=>m.setDraggable(false));$('draw-zone').setAttribute('aria-pressed','true');$('map-pencil').setAttribute('aria-pressed','true');$('cancel-pencil').hidden=false;status('Crayon actif · encercle un lieu. Échap pour annuler.');}
 function drawPoint(e:PointerEvent){const r=svg.getBoundingClientRect(),p:Coord=[e.clientX-r.left,e.clientY-r.top],last=screenStroke.at(-1);if(last&&Math.hypot(last[0]-p[0],last[1]-p[1])<4)return;if(stroke.length>=1499)return;const c=map.unproject(p);stroke.push([c.lng,c.lat]);screenStroke.push(p);path.setAttribute('d',screenStroke.map((p,i)=>`${i?'L':'M'}${p[0]} ${p[1]}`).join(' '));path.setAttribute('stroke',$<HTMLInputElement>('zone-color').value);}
 let activePointer:number|undefined;
 svg.addEventListener('pointerdown',e=>{if(!drawing||activePointer!==undefined||e.button!==0)return;e.preventDefault();activePointer=e.pointerId;svg.setPointerCapture(e.pointerId);stroke=[];screenStroke=[];drawPoint(e);});
 svg.addEventListener('pointermove',e=>{if(e.pointerId===activePointer)drawPoint(e);});
 svg.addEventListener('pointerup',e=>{if(e.pointerId!==activePointer)return;drawPoint(e);activePointer=undefined;svg.releasePointerCapture(e.pointerId);const area=Math.abs(screenStroke.reduce((sum,p,i)=>{const q=screenStroke[(i+1)%screenStroke.length];return sum+p[0]*q[1]-q[0]*p[1];},0))/2;
  if(stroke.length<4||area<100){stroke=[];screenStroke=[];path.setAttribute('d','');status('Trace un contour plus grand pour créer une zone.');return;}
  if(scene.zones.length>=100){stopDrawing();status('Limite de 100 zones atteinte.');return;}
  const clean=pencilRing(screenStroke);if(clean.length<4){stopDrawing();status('Contour trop petit. Recommence le secteur.');return;}
  const z:Zone={id:crypto.randomUUID(),name:$<HTMLInputElement>('zone-name').value.trim()||`Secteur ${scene.zones.length+1}`,ring:clean.map(p=>{const c=map.unproject(p);return [c.lng,c.lat] as Coord;}),color:scene.zoneColors!.watch,order:'watch'};scene.zones.push(z);selectedZone=z.id;suppressClick=true;setTimeout(()=>suppressClick=false,100);stopDrawing();renderZones();zoneEditor();changed();status(`${z.name} tracé · assigne un héros dans la fenêtre du secteur.`);
 });
 svg.addEventListener('pointercancel',()=>{activePointer=undefined;stopDrawing();});
 $('draw-zone').onclick=startDrawing;$('map-pencil').onclick=startDrawing;$('cancel-pencil').onclick=stopDrawing;
 $('add-agent').onclick=()=>addAgent(center());$('add-vehicle').onclick=()=>addVehicle(center());
 $('place-agent').onclick=()=>{stopDrawing();mode=mode==='agent'?undefined:'agent';status(mode?'Touche la carte pour placer le héros.':'Placement annulé.');};$('place-vehicle').onclick=()=>{stopDrawing();mode=mode==='vehicle'?undefined:'vehicle';status(mode?'Touche la carte pour placer le véhicule.':'Placement annulé.');};
 map.on('click',e=>{if(drawing||suppressClick||buildings.picking()||buildings.handled(e.originalEvent))return;const p:Coord=[e.lngLat.lng,e.lngLat.lat];if(mode){mode==='agent'?addAgent(p):addVehicle(p);mode=undefined;return;}if(juice.active())return;if(dispatch(p)){suppressClick=true;setTimeout(()=>suppressClick=false,100);}});

 function sceneClick(e:Event){const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;
  if(b.dataset.agent)openAgent(b.dataset.agent);
  if(b.dataset.vehicle){moveActor=undefined;selectedVehicle=b.dataset.vehicle;scene.window.open=false;windowUI();vehicleEditor();changed();}
  if(b.dataset.zone)openZone(b.dataset.zone);
  if(b.dataset.centerZone){const z=scene.zones.find(z=>z.id===b.dataset.centerZone);if(z)centerTarget(`zone:${z.id}`,zoneCenter(z));}
  if(b.id==='vehicle-move'){moveActor=moveActor===selectedVehicle?undefined:selectedVehicle;vehicleEditor();status(moveActor?'Choisis une destination sur la carte. Échap annule.':'Déplacement annulé.');}if(b.id==='vehicle-cancel'&&selectedVehicle&&confirm('Annuler le trajet de ce véhicule ?')){cancelDuty(selectedVehicle);moveActor=undefined;vehicleEditor();changed();}
  if(b.id==='close-zone'){selectedZone=undefined;zoneEditor();syncFocus();}
  if(b.dataset.centerAgent){const a=scene.agents.find(a=>a.id===b.dataset.centerAgent);if(a)centerTarget(`hero:${a.id}`,a.position);}if(b.dataset.centerVehicle){const v=scene.vehicles.find(v=>v.id===b.dataset.centerVehicle);if(v)centerTarget(`vehicle:${v.id}`,v.position);}
  if(b.dataset.removeAgent){const id=b.dataset.removeAgent;cancelDuty(id);scene.agents=scene.agents.filter(a=>a.id!==id);for(const z of scene.zones)if(z.agent===id)delete z.agent;if(scene.window.agent===id){scene.window.open=false;delete scene.window.agent;}renderActors();renderZones();zoneEditor();windowUI();changed();}
  if(b.dataset.removeVehicle){cancelDuty(b.dataset.removeVehicle);scene.vehicles=scene.vehicles.filter(v=>v.id!==b.dataset.removeVehicle);renderActors();vehicleEditor();changed();}
  if(b.id==='remove-zone'){const z=scene.zones.find(z=>z.id===selectedZone);if(!z)return;delete z.agent;assign(z);scene.zones=scene.zones.filter(z=>z.id!==selectedZone);selectedZone=undefined;renderZones();zoneEditor();changed();}
 }
 tools.addEventListener('click',sceneClick);zonePanel.addEventListener('click',sceneClick);
 tools.addEventListener('input',e=>{const colorInput=e.target as HTMLInputElement;if(colorInput.id==='travel-speed'){scene.travelSpeed=Number(colorInput.value);$('travel-speed-out').textContent=`×${scene.travelSpeed}`;changed();return;}if(colorInput.dataset.agentColor){const a=scene.agents.find(a=>a.id===colorInput.dataset.agentColor);if(a){a.color=colorInput.value;selectionUI();changed();}return;}const order=colorInput.dataset.zoneColor as 'watch'|'patrol'|undefined;if(order){scene.zoneColors![order]=colorInput.value;for(const z of scene.zones)if(z.order===order)z.color=colorInput.value;renderZones();zoneEditor();changed();return;}const input=e.target as HTMLInputElement,z=scene.zones.find(z=>z.id===selectedZone);if(input.id==='vehicle-heading'){const v=scene.vehicles.find(v=>v.id===selectedVehicle);if(v){v.heading=Number(input.value);renderActors();$('vehicle-editor').querySelector('output')!.textContent=`${v.heading}°`;changed();}}if(z&&input.id==='edit-zone-color'){z.color=input.value;renderZones();changed();}});
 zonePanel.addEventListener('change',e=>{const input=e.target as HTMLInputElement,z=scene.zones.find(z=>z.id===selectedZone);if(!z)return;if(input.id==='edit-zone-name'){z.name=input.value.trim()||z.name;renderZones();changed();}if(input.id==='zone-agent'){z.agent=input.value||undefined;assign(z);}if(input.id==='zone-tolerance'){z.tolerance=Number(input.value);assign(z);}});
 ambiance.addEventListener('input',e=>{const input=e.target as HTMLInputElement,key=input.dataset.effect as keyof Ambience;if(!key)return;(scene.ambience as unknown as Record<string,unknown>)[key]=input.type==='checkbox'?input.checked:input.type==='color'?input.value:Number(input.value);effects();changed();});
 ambiance.addEventListener('click',e=>{const mood=(e.target as HTMLElement).closest<HTMLElement>('[data-mood]')?.dataset.mood;if(!mood)return;scene.ambience={...scene.ambience,...defaultAmbience,...(mood==='night'?{light:.25,lightColor:'#a4bce8',azimuth:280,contrast:1.15,saturation:.85,glow:.7}:mood==='warm'?{light:.65,lightColor:'#ffe4bc',azimuth:120,contrast:1.05,saturation:1.15,glow:.3}:{})};effects();changed();});
 $('hero-center').onclick=()=>{const a=scene.agents.find(a=>a.id===scene.window.agent);if(a)centerTarget(`hero:${a.id}`,a.position);};
 $('hero-window-close').onclick=()=>{moveActor=undefined;scene.window.open=false;windowUI();changed();};$('hero-window-smaller').onclick=()=>{scene.window.width=Math.max(220,scene.window.width-40);windowLayout();changed();};$('hero-window-larger').onclick=()=>{scene.window.width=Math.min(640,scene.window.width+40);windowLayout();changed();};
 function manipulate(handle:HTMLElement,resize:boolean){let start:{pointer:number;x:number;y:number;left:number;top:number;width:number;height:number}|undefined;handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;handle.setPointerCapture(e.pointerId);start={pointer:e.pointerId,x:e.clientX,y:e.clientY,left:parseFloat(floating.style.left),top:parseFloat(floating.style.top),width:parseFloat(floating.style.width),height:parseFloat(floating.style.height)};e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!start||e.pointerId!==start.pointer)return;if(resize){scene.window.width=Math.max(220,Math.min(640,start.width+e.clientX-start.x));scene.window.height=Math.max(180,Math.min(1200,start.height+e.clientY-start.y));}else {const w=floating.offsetWidth,h=floating.offsetHeight;scene.window.x=Math.max(8,Math.min(viewport.clientWidth-w-8,start.left+e.clientX-start.x))/viewport.clientWidth;scene.window.y=Math.max(8,Math.min(viewport.clientHeight-h-8,start.top+e.clientY-start.y))/viewport.clientHeight;}windowLayout();});const end=(e:PointerEvent)=>{if(start&&e.pointerId===start.pointer){start=undefined;changed();}};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);}
 manipulate($('hero-window-drag'),false);manipulate($('hero-window-resize'),true);
 window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(moveActor){moveActor=undefined;syncSheet();vehicleEditor();status('Choix de destination annulé.');return;}if(drawing){activePointer=undefined;stopDrawing();}else if(scene.window.open){scene.window.open=false;windowUI();changed();}else {selectedZone=undefined;zoneEditor();}mode=undefined;}});
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$<HTMLIFrameElement>('hero-frame').contentWindow)return;if(e.data?.type==='hero-map-duty'){const a=scene.agents.find(a=>a.id===e.data.agent);if(a&&['ready','watch'].includes(e.data.order))setDuty(a,e.data.order,typeof e.data.zone==='string'?e.data.zone:undefined);return;}if(e.data?.type==='hero-map-ready'){const a=scene.agents.find(a=>a.id===e.data.agent);if(a&&a.speed===undefined&&typeof e.data.speed==='number'&&e.data.speed>=1&&e.data.speed<=100){a.speed=e.data.speed;changed();}syncSheet();return;}if(e.data?.type==='hero-map-move'){const a=scene.agents.find(a=>a.id===e.data.agent);if(a){moveActor=moveActor===a.id?undefined:a.id;syncSheet();status(moveActor?'Choisis une destination sur la carte. Échap annule.':'Choix de destination annulé.');}return;}if(e.data?.type==='hero-map-cancel'){const a=scene.agents.find(a=>a.id===e.data.agent);if(a){cancelDuty(a.id);moveActor=undefined;const resume=!!a.resumeIdle;a.duty=false;a.order='ready';if(resume)scheduleResume(a);renderActors();renderZones();zoneEditor();syncSheet();changed();status(a.resumeIdle?'Action annulée. Reprise de l’activité idle.':'Action suspendue; préférence idle conservée.');}return;}if(e.data?.type!=='hero-map-state')return;const a=scene.agents.find(a=>a.id===e.data.agent);if(!a)return;const oldHP=a.hp;for(const key of ['hp','mental','energy'] as const){const v=e.data[key],max=key==='hp'?8:key==='mental'?10:100;if(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max)a[key]=v;}if(a.hp<oldHP)juice.trigger(`hero:${a.id}`,'hit');if(typeof e.data.speed==='number'&&e.data.speed>=1&&e.data.speed<=100)a.speed=e.data.speed;const zone=typeof e.data.zone==='string'&&scene.zones.some(z=>z.id===e.data.zone)?e.data.zone:undefined;if(['ready','watch','patrol'].includes(e.data.order)&&(a.idle?.zone!==zone||e.data.activityChanged)){setDuty(a,e.data.order,zone);}changed();});

 let resourceTime=performance.now();setInterval(()=>{const now=performance.now(),dt=document.hidden?0:Math.min(1,(now-resourceTime)/1000);resourceTime=now;let dirty=false;for(const a of scene.agents){const before=[a.hp,a.mental,a.energy];if(atHQ(a)){a.hp=Math.min(8,a.hp+HQ_RECOVERY_PER_SECOND.hp*dt);a.mental=Math.min(10,a.mental+HQ_RECOVERY_PER_SECOND.mental*dt);a.energy=Math.min(100,a.energy+HQ_RECOVERY_PER_SECOND.energy*dt);}else if(a.duty&&a.order==='watch'&&a.zone&&(!a.journey||a.journey.loopActive)&&a.energy>0)a.energy=Math.max(0,a.energy-WATCH_ENERGY_PER_SECOND*dt);if(before.some((v,i)=>v!==[a.hp,a.mental,a.energy][i])){dirty=true;if(a.id===scene.window.agent&&scene.window.open)$<HTMLIFrameElement>('hero-frame').contentWindow?.postMessage({type:'map-hero-resources',agent:a.id,hp:a.hp,mental:a.mental,energy:a.energy},location.origin);}}dock.refresh();juice.activity();if(dirty)changed();},1000);
 map.on('sourcedata',e=>{if(!e.sourceId||e.sourceId.startsWith('scene-')||e.sourceDataType!=='content')return;for(const a of scene.agents)if(a.duty&&a.order==='ready'&&!a.journey&&!a.point)scheduleDuty(a);});
 new ResizeObserver(()=>windowLayout()).observe(viewport);map.on('move',perspective);
 map.addSource('scene-zones',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'scene-zone-fill',type:'fill',source:'scene-zones',layout:{visibility:'visible'},paint:{'fill-color':['get','color'],'fill-opacity':scene.ambience.zoneOpacity}});map.addLayer({id:'scene-zone-line',type:'line',source:'scene-zones',layout:{visibility:'visible','line-join':'round','line-cap':'round'},paint:{'line-color':['get','color'],'line-width':3,'line-opacity':.85}});
 map.on('click','scene-zone-fill',e=>{if(drawing||mode||suppressClick||moveActor||buildings.picking()||buildings.handled(e.originalEvent))return;const id=e.features?.[0]?.properties?.id;if(typeof id==='string'){openZone(id);}});
 effects();renderActors();renderZones();windowUI();
 for(const a of scene.agents)if(!a.journey){if(a.resumeIdle)scheduleResume(a);else if(a.duty)scheduleDuty(a)};
 return {buildingPaint:buildings.paint,pointsChanged(){occupants();buildings.pointsChanged();for(const a of scene.agents)if(a.duty&&a.order==='ready'&&!a.journey&&!a.point)scheduleDuty(a);},pointSelected(id?:string){selectedPoint=id;buildings.focusPoint(id);if(id){selectedZone=undefined;zoneEditor();}syncFocus();},centerPoint(id:string){const p=getPoints().find(p=>p.id===id);if(p)centerTarget(`point:${id}`,[p.lng,p.lat]);},pointMoveLabel(){const a=scene.window.open?scene.agents.find(a=>a.id===scene.window.agent):undefined;return a?`Déplacer ${heroRoster.find(h=>h.id===a.hero)!.name} ici`:selectedVehicle?'Déplacer le véhicule ici':undefined;},moveToPoint(id:string){const p=getPoints().find(p=>p.id===id);moveActor=scene.window.open?scene.window.agent:selectedVehicle;if(p)dispatch([p.lng,p.lat],p.name,p.id);},pointClick(id:string){if(juice.select(`point:${id}`))return true;juice.trigger(`point:${id}`,'click');const p=getPoints().find(p=>p.id===id);return p?dispatch([p.lng,p.lat],p.name,p.id):false;},snapshot:()=>structuredClone(scene),effects,active:()=>drawing||!!mode||buildings.picking(),cancelPlacement(){stopDrawing();mode=undefined;moveActor=undefined;scene.window.open=false;selectedVehicle=undefined;windowUI();},replace(next:Scene){stopDrawing();mode=undefined;moveActor=undefined;for(const timer of dutyTimers.values())clearTimeout(timer);dutyTimers.clear();juice.stop();scene=readScene(next);scene.buildings=readBuildings(scene.buildings);scene.juice=readJuice(scene.juice);scene.weather=readWeather(scene.weather);scene.routeStyle=readRouteStyle(scene.routeStyle);scene.zoneColors??={watch:activityForOrder('watch').color,patrol:activityForOrder('patrol').color};$<HTMLInputElement>('zone-color').value=scene.zoneColors.watch;selectedZone=undefined;selectedVehicle=undefined;selectedPoint=undefined;selectedBuilding=undefined;frameKey='';effects();rain.refresh();buildings.refresh();renderActors();renderZones();zoneEditor();vehicleEditor();windowUI();travel.restyle();routeControls();juice.reset();$<HTMLInputElement>('travel-speed').value=String(scene.travelSpeed??8);$('travel-speed-out').textContent=`×${scene.travelSpeed??8}`;for(const a of scene.agents)if(!a.journey){if(a.resumeIdle)scheduleResume(a);else if(a.duty)scheduleDuty(a)};}};
}
