import {heroAsset,heroRoster} from './hero-roster';
import {icon} from './icons';
export type HeroPreview={id:string;hero:string;hp:number;mental:number;energy:number;task:string;detail:string};
export function createHeroDock(viewport:HTMLElement,heroes:()=>HeroPreview[],open:(id:string)=>void,center:(id:string)=>void){
 const bar=document.createElement('nav');bar.id='hero-dock';bar.setAttribute('aria-label','Équipe sur le terrain');viewport.append(bar);let ids='';
 function refresh(){const list=heroes();bar.hidden=!list.length;const key=list.map(a=>a.id).join('|');if(key!==ids){ids=key;bar.replaceChildren();for(const a of list){const card=document.createElement('article');card.className='hero-preview';card.dataset.preview=a.id;const button=document.createElement('button');button.className='hero-preview-open';button.setAttribute('aria-label',`Ouvrir la fiche de ${heroRoster.find(h=>h.id===a.hero)!.name}`);button.innerHTML=`<img src="${heroAsset(a.hero,'portrait','dossier')}" alt=""><span class="preview-info"><strong></strong><span data-task></span><small data-detail></small><span class="preview-resources">${[['hp','HP',8],['mental','Mental',10],['energy','Énergie',100]].map(([k,n,max])=>`<span class="preview-meter ${k}"><span>${n} <b data-value="${k}"></b></span><progress data-meter="${k}" max="${max}"></progress></span>`).join('')}</span></span>`;button.querySelector('strong')!.textContent=heroRoster.find(h=>h.id===a.hero)!.name;button.onclick=()=>open(a.id);const target=document.createElement('button');target.className='hero-preview-center';target.dataset.centerHero=a.id;target.setAttribute('aria-label',`Centrer sur ${heroRoster.find(h=>h.id===a.hero)!.name}`);target.innerHTML=icon('target');target.onclick=()=>center(a.id);card.append(button,target);bar.append(card);}}
 for(const a of list){const card=bar.querySelector<HTMLElement>(`[data-preview="${a.id}"]`)!;card.querySelector('[data-task]')!.textContent=a.task;card.querySelector('[data-detail]')!.textContent=a.detail;for(const k of ['hp','mental','energy'] as const){card.querySelector<HTMLProgressElement>(`[data-meter=${k}]`)!.value=a[k];card.querySelector(`[data-value=${k}]`)!.textContent=String(Math.round(a[k]*10)/10);}}
 }return {refresh};
}
