import type {Map as MapLibreMap} from 'maplibre-gl';
import type {RoadCoord} from './map-roads';
import {icon} from './icons';
export const juiceEffects={pop:'Pop',squash:'Squash & stretch',flash:'Flash',shake:'Secousse écran',zoom:'Zoom caméra',travel:'Travelling',burst:'Explosion',rain:'Pluie de particules'};
export type JuiceConfig={effects:(keyof typeof juiceEffects)[];intensity:number;duration:number;color:string;trigger:'manual'|'click'|'arrival'};
export type JuiceState=Record<string,JuiceConfig>;
export type JuiceTarget={key:string;name:string;position:()=>RoadCoord;element:()=>HTMLElement|null};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function readJuice(value:unknown):JuiceState{if(value===undefined)return {};if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Juice invalide');const entries=Object.entries(value);if(entries.length>500)throw Error('Trop d’effets');for(const [key,c] of entries){if(key.length>100||!c||!Array.isArray(c.effects)||c.effects.length>8||c.effects.some((e:unknown)=>typeof e!=='string'||!Object.hasOwn(juiceEffects,e))||!Number.isFinite(c.intensity)||c.intensity<.25||c.intensity>2||!Number.isFinite(c.duration)||c.duration<200||c.duration>2000||!/^#[a-f0-9]{6}$/i.test(c.color)||!['manual','click','arrival'].includes(c.trigger))throw Error('Effet Juice invalide');}return structuredClone(value) as JuiceState;}
export function createJuice(map:MapLibreMap,viewport:HTMLElement,targets:()=>JuiceTarget[],state:()=>JuiceState,changed:()=>void){
 let selected='map',active=false,animations:Animation[]=[],raf=0,cameraEffect=false;
 const tabs=document.createElement('div');tabs.className='workshop-tabs';tabs.innerHTML=`<button id="settings-tab" aria-pressed="true">${icon('tools')}Atelier</button><button id="juice-tab" aria-pressed="false">${icon('bolt')}Juice</button>`;document.querySelector('.aside-title')!.after(tabs);
 const panel=document.createElement('section');panel.id='juice-panel';panel.hidden=true;document.querySelector('#workshop')!.append(panel);
 const canvas=document.createElement('canvas');canvas.className='juice-canvas';canvas.setAttribute('aria-hidden','true');viewport.append(canvas);const ctx=canvas.getContext('2d')!;
 function config(){return state()[selected]||{effects:['pop'],intensity:1,duration:650,color:'#78dcde',trigger:'manual'} as JuiceConfig;}
 function render(){const list=targets();if(!list.some(t=>t.key===selected))selected='map';const c=config();panel.innerHTML=`<h2>Juice</h2><p class="hint">Choisis un élément sur la map ou dans cette liste, coche les effets, puis teste.</p><label>Cible<select id="juice-target">${list.map(t=>`<option value="${escape(t.key)}" ${t.key===selected?'selected':''}>${escape(t.name)}</option>`).join('')}</select></label><div class="juice-effects">${Object.entries(juiceEffects).map(([key,label])=>`<label class="check"><input data-juice-effect="${key}" type="checkbox" ${c.effects.includes(key as keyof typeof juiceEffects)?'checked':''}>${label}</label>`).join('')}</div><label class="range">Intensité<output id="juice-intensity-out">${c.intensity}</output><input id="juice-intensity" type="range" min="0.25" max="2" step=".25" value="${c.intensity}"></label><label class="range">Durée<output id="juice-duration-out">${c.duration} ms</output><input id="juice-duration" type="range" min="200" max="2000" step="50" value="${c.duration}"></label><label class="color-row">Couleur<input id="juice-color" type="color" value="${c.color}"></label><label>Déclenchement<select id="juice-trigger"><option value="manual" ${c.trigger==='manual'?'selected':''}>Test manuel</option><option value="click" ${c.trigger==='click'?'selected':''}>Au clic</option><option value="arrival" ${c.trigger==='arrival'?'selected':''}>À l’arrivée du héros/véhicule</option></select></label><div class="pair"><button id="juice-test">${icon('player-play')}Tester</button><button id="juice-stop">${icon('x')}Arrêter</button></div><button id="juice-clear">Retirer les effets</button><p class="hint">Chaque élément conserve ses effets dans l’export atelier. Les mouvements de caméra respectent tes limites.</p><p id="juice-feedback" role="status"></p>`;}
 function stop(){animations.forEach(a=>a.cancel());animations=[];cancelAnimationFrame(raf);ctx.clearRect(0,0,canvas.width,canvas.height);if(cameraEffect){map.stop();cameraEffect=false;}canvas.dataset.playing='false';}
 function play(key=selected){const target=targets().find(t=>t.key===key);if(!target)return;const c=state()[key]||(key===selected?config():undefined);if(!c)return;stop();const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,duration=reduced?Math.min(300,c.duration):c.duration,strength=reduced?.2:c.intensity,root=target.element(),el=root?.querySelector<HTMLElement>('.token-portrait,.poi-symbol')||root;
  const animate=(node:HTMLElement|undefined|null,frames:Keyframe[])=>{if(node)animations.push(node.animate(frames,{duration,easing:'ease-out'}));};
  if(c.effects.includes('pop')&&!c.effects.includes('squash'))animate(el,[{scale:'1'},{scale:String(1+.25*strength),offset:.35},{scale:'1'}]);
  if(c.effects.includes('squash'))animate(el,[{scale:'1 1'},{scale:`${1+.3*strength} ${1-.25*strength}`,offset:.25},{scale:`${1-.12*strength} ${1+.15*strength}`,offset:.6},{scale:'1 1'}]);
  if(c.effects.includes('flash'))animate(el,[{filter:'brightness(1)'},{filter:`brightness(${1+strength*1.8})`,offset:.2},{filter:'brightness(1)'}]);
  if(c.effects.includes('shake')&&!reduced)animate(document.querySelector<HTMLElement>('#map'),[{translate:'0 0'},...Array.from({length:8},(_,i)=>({translate:`${(i%2?1:-1)*6*strength*(1-i/8)}px ${(i%3-1)*4*strength}px`})),{translate:'0 0'}]);
  if(c.effects.includes('zoom')||c.effects.includes('travel')){cameraEffect=true;map.easeTo({center:target.position(),zoom:c.effects.includes('zoom')?Math.min(map.getMaxZoom(),map.getZoom()+.6*strength):map.getZoom(),duration:reduced?0:duration});}
  if(c.effects.includes('burst')||c.effects.includes('rain')||c.effects.includes('flash')){const dpr=Math.min(2,devicePixelRatio||1);canvas.width=viewport.clientWidth*dpr;canvas.height=viewport.clientHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const rain=c.effects.includes('rain'),burst=c.effects.includes('burst'),count=reduced?8:Math.round((rain?65:35)*strength),particles=Array.from({length:count},(_,i)=>({angle:i/count*Math.PI*2,speed:35+Math.random()*65,offset:(Math.random()-.5)*180*strength,size:2+Math.random()*3})),start=performance.now();canvas.dataset.playing='true';
   const tick=(now:number)=>{const t=Math.min(1,(now-start)/duration),p=map.project(target.position());ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=c.color;ctx.strokeStyle=c.color;if(c.effects.includes('flash')){ctx.globalAlpha=(1-t)*.3;ctx.beginPath();ctx.arc(p.x,p.y,15+40*t*strength,0,Math.PI*2);ctx.fill();}if(burst){ctx.globalAlpha=(1-t)*.8;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,8+t*90*strength,0,Math.PI*2);ctx.stroke();}if(burst||rain)for(const q of particles){const x=rain?p.x+q.offset:p.x+Math.cos(q.angle)*q.speed*t*strength,y=rain?p.y-100*strength+200*t*strength:p.y+Math.sin(q.angle)*q.speed*t*strength+20*t*t;ctx.globalAlpha=(1-t)*.9;ctx.fillRect(x,y,q.size,q.size*(rain?2:1));}ctx.globalAlpha=1;if(t<1)raf=requestAnimationFrame(tick);else{ctx.clearRect(0,0,canvas.width,canvas.height);canvas.dataset.playing='false';}};raf=requestAnimationFrame(tick);}
  const feedback=panel.querySelector('#juice-feedback');if(feedback)feedback.textContent=`${c.effects.length} effet(s) · ${target.name}`;
 }
 function toggle(on:boolean){active=on;document.querySelector('#workshop')!.classList.toggle('juice-mode',on);panel.hidden=!on;tabs.querySelector('#settings-tab')!.setAttribute('aria-pressed',String(!on));tabs.querySelector('#juice-tab')!.setAttribute('aria-pressed',String(on));if(on)render();}
 tabs.querySelector('#settings-tab')!.addEventListener('click',()=>toggle(false));tabs.querySelector('#juice-tab')!.addEventListener('click',()=>toggle(true));
 panel.addEventListener('change',e=>{const el=e.target as HTMLInputElement;if(el.id==='juice-target'){selected=el.value;render();return;}});
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement;if(el.id==='juice-target')return;const c=structuredClone(config());c.effects=[...panel.querySelectorAll<HTMLInputElement>('[data-juice-effect]:checked')].map(e=>e.dataset.juiceEffect as keyof typeof juiceEffects);c.intensity=Number((panel.querySelector('#juice-intensity') as HTMLInputElement).value);c.duration=Number((panel.querySelector('#juice-duration') as HTMLInputElement).value);c.color=(panel.querySelector('#juice-color') as HTMLInputElement).value;c.trigger=(panel.querySelector('#juice-trigger') as HTMLSelectElement).value as JuiceConfig['trigger'];state()[selected]=c;panel.querySelector('#juice-intensity-out')!.textContent=String(c.intensity);panel.querySelector('#juice-duration-out')!.textContent=`${c.duration} ms`;changed();});
 panel.addEventListener('click',e=>{const id=(e.target as HTMLElement).closest('button')?.id;if(id==='juice-test'){state()[selected]=structuredClone(config());changed();play();}if(id==='juice-stop')stop();if(id==='juice-clear'){delete state()[selected];stop();render();changed();}});
 return {select(key:string){if(!active)return false;selected=key;render();return true;},trigger(key:string,event:'click'|'arrival'){if(state()[key]?.trigger===event)play(key);},active:()=>active,refresh(){if(active)render();},stop,reset(){stop();selected='map';render();}};
}
