export type Weather={enabled:boolean;intensity:number;speed:number;wind:number;opacity:number;color:string;splashes:boolean};
export const defaultWeather:Weather={enabled:false,intensity:.45,speed:1,wind:.2,opacity:.4,color:'#a6c5dd',splashes:true};
export function readWeather(value:unknown):Weather{if(value===undefined)return {...defaultWeather};const w=value as Weather;if(!w||typeof w.enabled!=='boolean'||typeof w.splashes!=='boolean'||!/^#[0-9a-f]{6}$/i.test(w.color)||!Number.isFinite(w.intensity)||w.intensity<0||w.intensity>1||!Number.isFinite(w.opacity)||w.opacity<0||w.opacity>1||!Number.isFinite(w.speed)||w.speed<.25||w.speed>2||!Number.isFinite(w.wind)||Math.abs(w.wind)>1)throw Error('Pluie invalide');return structuredClone(w);}
export function createRain(viewport:HTMLElement,parent:HTMLElement,state:()=>Weather,changed:()=>void){
 const panel=document.createElement('section');panel.className='rain-controls';parent.append(panel);
 const canvas=document.createElement('canvas');canvas.className='weather-rain';canvas.setAttribute('aria-hidden','true');viewport.append(canvas);const ctx=canvas.getContext('2d')!;
 let raf=0,last=0,width=0,height=0,drops:{x:number;y:number;depth:number}[]=[];
 function resize(){width=viewport.clientWidth;height=viewport.clientHeight;const ratio=Math.min(devicePixelRatio,1.5);canvas.width=width*ratio;canvas.height=height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);drops=[];}
 function controls(){const w=state();panel.innerHTML=`<h2>Pluie</h2><label class="check"><input id="rain-enabled" data-rain="enabled" type="checkbox" ${w.enabled?'checked':''}>Pluie sur la carte</label>${[['intensity','Densité',0,1,.05],['speed','Vitesse',.25,2,.05],['wind','Vent',-1,1,.05],['opacity','Visibilité',0,1,.05]].map(([key,label,min,max,step])=>`<label class="range">${label}<output data-rain-out="${key}">${w[key as keyof Weather]}</output><input data-rain="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${w[key as keyof Weather]}"></label>`).join('')}<label class="color-row">Teinte<input data-rain="color" type="color" value="${w.color}"></label><label class="check"><input data-rain="splashes" type="checkbox" ${w.splashes?'checked':''}>Éclaboussures au sol</label>`;}
 function tick(now:number){raf=0;const w=state();ctx.clearRect(0,0,width,height);if(!w.enabled||document.hidden)return;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,dt=Math.min(.05,(now-(last||now))/1000);last=now;const count=Math.min(550,Math.round(width*height/2800*w.intensity*(reduced?.3:1)));while(drops.length<count)drops.push({x:Math.random()*width,y:Math.random()*height,depth:.3+Math.random()*.7});drops.length=count;ctx.strokeStyle=w.color;ctx.lineWidth=1;for(const d of drops){const fall=(280+400*d.depth)*w.speed*(reduced?.35:1),dx=w.wind*fall*.4,dy=fall;d.x+=dx*dt;d.y+=dy*dt;if(d.y>height+20){d.y=-20;d.x=Math.random()*width;}if(d.x<-50)d.x=width+30;if(d.x>width+50)d.x=-30;ctx.globalAlpha=w.opacity*(.25+.65*d.depth);const length=(6+16*d.depth)*w.speed;ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(d.x-dx/dy*length,d.y-length);ctx.stroke();if(w.splashes&&d.depth>.7){const phase=(now/900+d.depth*13)%1;if(phase<.25){ctx.globalAlpha=w.opacity*(1-phase*4)*.3;ctx.beginPath();ctx.ellipse((d.x*1.7)%width,(d.depth*1223)%height,2+phase*15,1+phase*4,0,0,Math.PI*2);ctx.stroke();}}}ctx.globalAlpha=1;raf=requestAnimationFrame(tick);}
 function refresh(){cancelAnimationFrame(raf);raf=0;last=0;canvas.hidden=!state().enabled;controls();if(state().enabled)raf=requestAnimationFrame(tick);else ctx.clearRect(0,0,width,height);}
 panel.addEventListener('input',e=>{const el=e.target as HTMLInputElement,key=el.dataset.rain as keyof Weather;if(!key)return;(state() as unknown as Record<string,unknown>)[key]=el.type==='checkbox'?el.checked:el.type==='color'?el.value:Number(el.value);const out=panel.querySelector(`[data-rain-out="${key}"]`);if(out)out.textContent=el.value;canvas.hidden=!state().enabled;cancelAnimationFrame(raf);raf=0;last=0;if(state().enabled)raf=requestAnimationFrame(tick);else ctx.clearRect(0,0,width,height);changed();});
 new ResizeObserver(resize).observe(viewport);document.addEventListener('visibilitychange',()=>{last=0;cancelAnimationFrame(raf);raf=0;if(!document.hidden&&state().enabled)raf=requestAnimationFrame(tick);});resize();refresh();return {refresh};
}
