export const juiceEffects={pop:'Pop',squash:'Squash & stretch',flash:'Flash',shake:'Secousse écran',zoom:'Zoom caméra',travel:'Travelling',burst:'Explosion',rain:'Pluie de particules'};
export const juiceTypes:Record<string,string>={hero:'Tous les héros',vehicle:'Tous les véhicules',zone:'Tous les secteurs','point:alert':'Toutes les alertes','point:hq':'Tous les QG','point:police':'Tous les points Police','point:clue':'Tous les indices','point:civil':'Tous les points Civils','point:hospital':'Tous les secours','point:watch':'Tous les points Surveillance',map:'Carte · caméra'};
export type JuiceConfig={effects:(keyof typeof juiceEffects)[];intensity:number;duration:number;color:string};
export type JuiceRule={id:string;type:string;event:string;config:JuiceConfig;target?:string};
export type JuiceState={version:2;events:string[];rules:JuiceRule[]};
export const defaultJuiceConfig=():JuiceConfig=>({effects:['pop'],intensity:1,duration:650,color:'#78dcde'});
export const emptyJuice=():JuiceState=>({version:2,events:['manual','click','arrival','hit','solved'],rules:[]});
export function validateJuiceConfig(c:JuiceConfig){if(!c||!Array.isArray(c.effects)||c.effects.length>8||c.effects.some(e=>!Object.hasOwn(juiceEffects,e))||!Number.isFinite(c.intensity)||c.intensity<.25||c.intensity>2||!Number.isFinite(c.duration)||c.duration<200||c.duration>2000||!/^#[a-f0-9]{6}$/i.test(c.color))throw Error('Effet Juice invalide');}
export function readJuice(value:unknown):JuiceState{
 if(value===undefined)return emptyJuice();if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Juice invalide');
 const s=value as JuiceState;if(s.version===2){if(!Array.isArray(s.events)||s.events.length>100||s.events.some(e=>typeof e!=='string'||!/^[a-z][a-z0-9_-]{0,39}$/.test(e))||new Set(s.events).size!==s.events.length||!Array.isArray(s.rules)||s.rules.length>500)throw Error('Déclencheurs invalides');const keys=new Set<string>();for(const r of s.rules){if(!r||typeof r.id!=='string'||r.id.length>100||!Object.hasOwn(juiceTypes,r.type)||!s.events.includes(r.event)||(r.target!==undefined&&(typeof r.target!=='string'||r.target.length>100)))throw Error('Règle Juice invalide');const key=JSON.stringify([r.type,r.event,r.target]);if(keys.has(key))throw Error('Règle Juice dupliquée');keys.add(key);validateJuiceConfig(r.config);}return structuredClone(s);}
 const next=emptyJuice(),entries=Object.entries(value);if(entries.length>500)throw Error('Trop d’effets');for(const [target,c] of entries){if(target.length>100||!['manual','click','arrival'].includes(c?.trigger))throw Error('Ancien effet invalide');validateJuiceConfig(c);next.rules.push({id:`legacy-${next.rules.length}`,target,type:target.startsWith('hero:')?'hero':target.startsWith('vehicle:')?'vehicle':target.startsWith('zone:')?'zone':target==='map'?'map':'point:alert',event:c.trigger,config:{effects:[...c.effects],intensity:c.intensity,duration:c.duration,color:c.color}});}return next;
}
export function matchingJuice(state:JuiceState,type:string,event:string,target:string){return state.rules.filter(r=>r.event===event&&(r.target?r.target===target:r.type===type));}
