import {icon} from './icons';
import './roll-gym.css';
const names=['Ruban','100 cases','Compteur','Curseur'];
let variant=0, running=false, frame=0;
const $=(s:string)=>document.querySelector<HTMLElement>(s)!;
const portrait=(name:string,pos:number)=>`<div class="hero"><div class="portrait" style="background-position:${pos}% center" role="img" aria-label="${name}"></div><strong>${name}</strong></div>`;
$('#gym').innerHTML=`<header><a href="./gyms.html">${icon('arrow-left')} Gyms</a><b>VIGILANTE <em>SQUAD</em></b><span>GYM / 01</span></header><main><section class="controls"><p class="eyebrow">LABORATOIRE DE RÉSOLUTION</p><h1>Quatre façons de sentir le jet.</h1><nav aria-label="Animation du tirage">${names.map((n,i)=>`<button data-variant="${i}" aria-pressed="${i===0}"><small>0${i+1}</small>${n}</button>`).join('')}</nav><div class="settings"><label>Scénario<select id="scenario"><option value="64">Réussite · 64</option><option value="84">Partiel · 84</option><option value="1">Critique positif · 1</option><option value="100">Critique négatif · 100</option><option value="random">Aléatoire · 1–100</option></select></label><label>Animation<select id="duration"><option value="4000">4 secondes</option><option value="1200">1,2 seconde</option><option value="6000">6 secondes</option></select></label></div><p class="note">Exemple de comparaison : 70 % pour les quatre variantes. Valeurs illustratives, indépendantes de la partie.</p></section><section class="console"><div class="mission">${icon('map-pin')}<div><small>GARE EST</small><h2>Protéger les civils</h2></div><span class="tag">TEST</span></div><ol class="steps"><li class="active">01 Préparer</li><li>02 Tirer</li><li>03 Conséquences</li></ol><div id="crew">${portrait('Malik',50)}${portrait('Silas',100)}</div><div id="preparation"><div class="contributions"><h3>Contributions de l’équipe</h3>${[['Base de mission',50,'target'],['Équipe',20,'users'],['Talents',15,'shield-check'],['Risque de la zone',-5,'alert-triangle'],['Fatigue',-10,'battery']].map(([n,v,i])=>`<div>${icon(i as Parameters<typeof icon>[0])}<span>${n}</span><div class="mini"><i style="width:${Math.abs(Number(v))*2}%;background:${Number(v)<0?'var(--red)':'var(--green)'}"></i></div><b class="${Number(v)<0?'bad':'good'}">${Number(v)>0?'+':''}${v}<small> pts</small></b></div>`).join('')}</div></div><div class="chance">${icon('target')}<span>Chance de réussite<strong>70<small>%</small></strong></span><small>Réussite si<br>jet ≤ 70</small></div><div id="stage" hidden></div><div id="outcome" aria-live="polite"></div><div class="action"><p id="status">Un seul jet pour toute l’équipe.</p><button id="roll" class="primary">${icon('player-play')} Lancer le tirage</button></div></section></main>`;
function steps(index:number){document.querySelectorAll('.steps li').forEach((e,i)=>e.classList.toggle('active',i===index));}
function reset(){ $('.console').classList.remove('resolved');cancelAnimationFrame(frame);running=false;$('#preparation').hidden=false;$('#stage').hidden=true;$('#outcome').innerHTML='';$('#crew').innerHTML=portrait('Malik',50)+portrait('Silas',100);$('#roll').innerHTML=icon('player-play')+' Lancer le tirage';$('#status').textContent='Un seul jet pour toute l’équipe.';steps(0);document.querySelectorAll<HTMLButtonElement|HTMLSelectElement>('.controls button,.controls select,#roll').forEach(e=>e.disabled=false);}
document.querySelectorAll<HTMLButtonElement>('[data-variant]').forEach(b=>b.onclick=()=>{variant=Number(b.dataset.variant);reset();document.querySelectorAll('[data-variant]').forEach(e=>e.setAttribute('aria-pressed',String(e===b)));});
function meter(current:number,max:number,mental=false){return `<div class="meter ${mental?'mental':''}" aria-label="${mental?'Mental':'PV'} : ${current} sur ${max}">${icon(mental?'brain':'heart')}<span>${Array.from({length:max},(_,i)=>`<i class="${i<current?'full':''}"></i>`).join('')}</span><b>${current}/${max}</b></div>`;}
function finish(result:number){running=false;$('#stage').hidden=true;$('.console').classList.add('resolved');const success=result<=70;steps(2);$('#status').textContent='Tirage terminé · '+names[variant];$('#roll').innerHTML=icon('player-play')+' Rejouer';document.querySelectorAll<HTMLButtonElement|HTMLSelectElement>('.controls button,.controls select,#roll').forEach(e=>e.disabled=false);$('#outcome').innerHTML=`<p class="eyebrow">RAPPORT D’INTERVENTION</p><div class="verdict ${success?'good':'bad'}"><span>JET <b>${result}</b><small>/ 100</small></span><span>${icon(success?'check':'alert-triangle')}<strong>${result===1?'CRITIQUE POSITIF':result===100?'CRITIQUE NÉGATIF':success?'RÉUSSITE':'RÉSULTAT PARTIEL'}</strong><small>Chance : 70 % · ${result} ${success?'≤':'>'} 70</small></span></div><div class="impacts"><div>${icon('users')}<strong>${success?2:1}</strong><span>Civils sauvés</span></div><div>${icon('shield-check')}<strong>${success?'+1':'0'}</strong><span>Confiance</span></div></div><h3>Effets sur l’équipe</h3><div class="hero-results">${[['Malik',50,8,10],['Silas',100,10,6]].map(([n,p,h,m])=>`<article>${portrait(String(n),Number(p))}<div class="loss">${success?'PV inchangés':'−2 PV'} · −${success?1:2} mental</div>${meter(Number(h)-(success?0:2),Number(h))}${meter(Number(m)-(success?1:2),Number(m),true)}</article>`).join('')}</div>`;}
$('#roll').onclick=()=>{if(running)return;reset();running=true;steps(1);$('#preparation').hidden=true;$('#stage').hidden=false;$('#status').textContent='Tirage en cours…';document.querySelectorAll<HTMLButtonElement|HTMLSelectElement>('.controls button,.controls select,#roll').forEach(e=>e.disabled=true);const scenario=($ ('#scenario') as HTMLSelectElement).value;let random=new Uint32Array(1);do{crypto.getRandomValues(random);}while(random[0]>=4294967200);const result=scenario==='random'?random[0]%100+1:Number(scenario);const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:Number(($('#duration') as HTMLSelectElement).value);const shuffled=(values:number[])=>{for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]];}return values;};
// Full permutation: exactly 70 winning cells and 30 losing cells.
const cells=shuffled(Array.from({length:100},(_,i)=>i+1));
const targetIndex=cells.indexOf(result);const ribbon=cells.concat(cells,cells);const end=100+targetIndex;const begin=end-24;
const cellClass=(v:number)=>`${v<=70?'win':'lose'} ${v===1?'critical-positive':v===100?'critical-negative':''}`;
const mark=(v:number)=>v===1?'★':v===100?'✕':'';
if(variant===0)$('#stage').innerHTML=`<div class="ribbon"><div class="ribbon-track">${ribbon.map(v=>`<span class="${cellClass(v)}">${v}<small>${mark(v)}</small></span>`).join('')}</div><div class="pointer"></div></div><div class="legend"><span>★ 1 · critique positif</span><span>100 · critique négatif ✕</span></div>`;
if(variant===1)$('#stage').innerHTML=`<div class="grid">${cells.map(v=>`<span class="${cellClass(v)}" aria-label="${v}${v===1?' critique positif':v===100?' critique négatif':''}">${mark(v)}</span>`).join('')}</div><div class="legend"><span>★ Critique positif</span><span>✕ Critique négatif</span></div>`;
if(variant===2)$('#stage').innerHTML='<div class="counter"><span>0</span><span>0</span></div><p class="scale">01–99 · 00 = 100</p>';
if(variant===3)$('#stage').innerHTML='<div class="cursor-value">1</div><div class="threshold"><i></i><b></b></div><div class="axis"><span>1</span><span>70</span><span>100</span></div><div class="legend"><span>✓ Réussite</span><span>! Partiel</span></div>';
// Each timeline lands on the actual result before the reveal hold; no final override.
const hops=shuffled(cells.filter(v=>v!==result)).slice(0,24).concat(result);
const gridNodes=Array.from(document.querySelectorAll<HTMLElement>('.grid span'));
const gridByValue=new Map(cells.map((v,i)=>[v,gridNodes[i]]));let activeCell:HTMLElement|undefined;
const rebound=Math.random()<.5;
// All grid beats, including the final result, share the same increasing intervals.
const intervals=Array.from({length:hops.length-1},(_,i)=>1+3*Math.pow(i/(hops.length-2),1.6));
const intervalTotal=intervals.reduce((a,b)=>a+b,0);let beatSum=0;
const beats=[0,...intervals.map(v=>(beatSum+=v)/intervalTotal)];beats[beats.length-1]=1;
const smooth=(u:number)=>u*u*u*(u*(u*6-15)+10);
// One damped trajectory: continuous velocity, no stop/restart at waypoints.
function cursorAt(t:number){const w=3*Math.PI;const oscillation=70-69*Math.exp(-3*t)*(Math.cos(w*t)+3/w*Math.sin(w*t));const blend=smooth(Math.max(0,Math.min(1,(t-.55)/.45)));return oscillation*(1-blend)+result*blend;}
const hold=duration===0?0:variant===2?1100:variant===1?Math.max(650,duration*intervals[intervals.length-1]/intervalTotal):650;
const start=performance.now();let prev=-1,settled=false;
function tick(now:number){const elapsed=now-start;const motion=duration===0?1:Math.min(1,elapsed/duration);const eased=1-Math.pow(1-motion,3);let value=result;
if(variant===0){let position;if(rebound){const u=Math.min(1,motion/.8);position=begin+(end+1-begin)*(1-Math.pow(1-u,3));if(motion>.8)position=end+1-smooth((motion-.8)/.2);}else position=begin+(end-begin)*eased;$('.ribbon-track').style.transform=`translateX(calc(50% - ${position*64+32}px))`;value=ribbon[Math.round(position)];}
if(variant===1){let hop=0;while(hop<beats.length-1&&motion>=beats[hop+1])hop++;value=hops[hop];if(value!==prev){activeCell?.classList.remove('lit');activeCell=gridByValue.get(value);activeCell?.classList.add('lit');}}
if(variant===2){const position=Math.round((200+result)*eased);value=position%100||100;const digits=String(value%100).padStart(2,'0');$('.counter').classList.toggle('good',value<=70);$('.counter').classList.toggle('bad',value>70);document.querySelectorAll('.counter span').forEach((el,i)=>el.textContent=digits[i]);}
if(variant===3){const position=cursorAt(motion);value=Math.round(position);$('.threshold b').style.left=`${position-.5}%`;$('.cursor-value').textContent=String(value);$('.cursor-value').style.color=value<=70?'var(--green)':'var(--red)';}
if(motion===1&&!settled){settled=true;$('#status').textContent=`Jet : ${result} · ${result<=70?'réussite':'résultat partiel'}`;if(variant===2)$('.counter').classList.add('landed');}
$('#stage').dataset.value=String(value);prev=value;if(elapsed<duration+hold)frame=requestAnimationFrame(tick);else finish(result);}
frame=requestAnimationFrame(tick);};
